// Icons with primary category: account
const icons = [
    {
        icon: 'Award',
        name: 'award',
        tags: [
            'achievement',
            'badge',
            'rosette',
            'prize',
            'winner',
        ],
        categories: [
            'account',
            'sports',
            'gaming',
        ],
    },
    {
        icon: 'BadgeAlert',
        name: 'badge-alert',
        tags: [
            'check',
            'verified',
            'unverified',
            'security',
            'safety',
            'issue',
        ],
        categories: [
            'account',
            'social',
        ],
    },
    {
        icon: 'BadgeInfo',
        name: 'badge-info',
        tags: [
            'verified',
            'unverified',
            'help',
        ],
        categories: [
            'account',
            'accessibility',
            'social',
        ],
    },
    {
        icon: 'Badge',
        name: 'badge',
        tags: [
            'check',
            'verified',
            'unverified',
        ],
        categories: [
            'account',
            'social',
            'shapes',
        ],
    },
    {
        icon: 'Ban',
        name: 'ban',
        tags: [
            'cancel',
            'no',
            'stop',
            'forbidden',
            'prohibited',
            'error',
            'incorrect',
            'mistake',
            'wrong',
            'failure',
            'circle',
            'slash',
            'null',
            'void',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'BellDot',
        name: 'bell-dot',
        tags: [
            'alarm',
            'notification',
            'sound',
            'reminder',
            'unread',
        ],
        categories: [
            'account',
            'notifications',
        ],
    },
    {
        icon: 'Bell',
        name: 'bell',
        tags: [
            'alarm',
            'notification',
            'sound',
            'reminder',
        ],
        categories: [
            'account',
            'notifications',
        ],
    },
    {
        icon: 'BookUser',
        name: 'book-user',
        tags: [
            'person',
            'people',
            'family',
            'friends',
            'acquaintances',
            'contacts',
            'details',
            'addresses',
            'phone numbers',
            'directory',
            'listing',
            'networking',
        ],
        categories: [
            'account',
            'connectivity',
            'communication',
            'social',
        ],
    },
    {
        icon: 'BookmarkCheck',
        name: 'bookmark-check',
        tags: [
            'read',
            'finished',
            'complete',
            'clip',
            'marker',
            'tag',
            'task',
            'todo',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'BookmarkMinus',
        name: 'bookmark-minus',
        tags: [
            'delete',
            'remove',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'BookmarkPlus',
        name: 'bookmark-plus',
        tags: [
            'add',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'BookmarkX',
        name: 'bookmark-x',
        tags: [
            'read',
            'clip',
            'marker',
            'tag',
            'cancel',
            'close',
            'delete',
            'remove',
            'clear',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'Bookmark',
        name: 'bookmark',
        tags: [
            'read',
            'clip',
            'marker',
            'tag',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'Building2',
        name: 'building-2',
        tags: [
            'business',
            'company',
            'enterprise',
            'skyscraper',
            'organisation',
            'organization',
            'city',
        ],
        categories: [
            'account',
            'buildings',
        ],
    },
    {
        icon: 'Building',
        name: 'building',
        tags: [
            'organisation',
            'organization',
        ],
        categories: [
            'account',
            'buildings',
        ],
    },
    {
        icon: 'CircleUserRound',
        name: 'circle-user-round',
        tags: [
            'person',
            'account',
            'contact',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'CircleUser',
        name: 'circle-user',
        tags: [
            'person',
            'account',
            'contact',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'Cog',
        name: 'cog',
        tags: [
            'computing',
            'settings',
            'cog',
            'edit',
            'gear',
            'preferences',
            'controls',
            'configuration',
            'fixed',
            'build',
            'construction',
            'parts',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'ContactRound',
        name: 'contact-round',
        tags: [
            'user',
            'person',
            'family',
            'friend',
            'acquaintance',
            'listing',
            'networking',
        ],
        categories: [
            'account',
            'connectivity',
            'communication',
            'social',
        ],
    },
    {
        icon: 'Contact',
        name: 'contact',
        tags: [
            'user',
            'person',
            'family',
            'friend',
            'acquaintance',
            'listing',
            'networking',
        ],
        categories: [
            'account',
            'connectivity',
            'communication',
            'social',
        ],
    },
    {
        icon: 'Cookie',
        name: 'cookie',
        tags: [
            'biscuit',
            'privacy',
            'legal',
            'food',
        ],
        categories: [
            'account',
            'food-beverage',
        ],
    },
    {
        icon: 'CreditCard',
        name: 'credit-card',
        tags: [
            'bank',
            'purchase',
            'payment',
            'cc',
        ],
        categories: [
            'account',
            'finance',
        ],
    },
    {
        icon: 'FileUser',
        name: 'file-user',
        tags: [
            'person',
            'personal information',
            'people',
            'listing',
            'networking',
            'document',
            'contact',
            'cover letter',
            'resume',
            'cv',
            'curriculum vitae',
            'application form',
        ],
        categories: [
            'account',
            'files',
        ],
    },
    {
        icon: 'Fingerprint',
        name: 'fingerprint',
        tags: [
            '2fa',
            'authentication',
            'biometric',
            'identity',
            'security',
        ],
        categories: [
            'account',
            'security',
            'medical',
            'devices',
        ],
    },
    {
        icon: 'FlagOff',
        name: 'flag-off',
        tags: [
            'unflag',
        ],
        categories: [
            'account',
            'social',
        ],
    },
    {
        icon: 'Flag',
        name: 'flag',
        tags: [
            'report',
        ],
        categories: [
            'account',
            'social',
        ],
    },
    {
        icon: 'Handshake',
        name: 'handshake',
        tags: [
            'agreement',
            'partnership',
            'deal',
            'business',
            'assistance',
            'cooperation',
            'friendship',
            'union',
            'terms',
        ],
        categories: [
            'account',
            'social',
            'communication',
            'finance',
            'security',
        ],
    },
    {
        icon: 'Inbox',
        name: 'inbox',
        tags: [
            'email',
        ],
        categories: [
            'account',
            'mail',
        ],
    },
    {
        icon: 'MessageCircleX',
        name: 'message-circle-x',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'clear',
            'close',
            'delete',
            'remove',
            'cancel',
            'silence',
            'mute',
            'moderate',
        ],
        categories: [
            'account',
            'social',
        ],
    },
    {
        icon: 'NotebookTabs',
        name: 'notebook-tabs',
        tags: [
            'notepad',
            'notes',
            'people',
            'family',
            'friends',
            'acquaintances',
            'contacts',
            'details',
            'addresses',
            'phone numbers',
            'directory',
            'listing',
            'networking',
            'alphabetical',
            'a-z',
            'organizer',
            'organiser',
            'planner',
            'diary',
            'stationery',
        ],
        categories: [
            'account',
            'communication',
            'social',
        ],
    },
    {
        icon: 'ScanFace',
        name: 'scan-face',
        tags: [
            'face',
            'biometric',
            'identification',
            'authentication',
            '2fa',
            'access',
            'login',
            'dashed',
        ],
        categories: [
            'account',
            'security',
            'devices',
            'social',
        ],
    },
    {
        icon: 'ScanQrCode',
        name: 'scan-qr-code',
        tags: [
            'barcode',
            'scan',
            'qrcode',
            'url',
            'information',
            'digital',
            'scanner',
        ],
        categories: [
            'account',
            'shopping',
            'devices',
            'security',
        ],
    },
    {
        icon: 'Settings2',
        name: 'settings-2',
        tags: [
            'cog',
            'edit',
            'gear',
            'preferences',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'Settings',
        name: 'settings',
        tags: [
            'cog',
            'edit',
            'gear',
            'preferences',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'Share2',
        name: 'share-2',
        tags: [
            'network',
            'connections',
        ],
        categories: [
            'account',
            'social',
        ],
    },
    {
        icon: 'Share',
        name: 'share',
        tags: [
            'network',
            'connections',
        ],
        categories: [
            'account',
            'social',
        ],
    },
    {
        icon: 'ShieldAlert',
        name: 'shield-alert',
        tags: [
            'unshielded',
            'cybersecurity',
            'insecure',
            'unsecured',
            'safety',
            'unsafe',
            'protection',
            'unprotected',
            'guardian',
            'unguarded',
            'unarmored',
            'unarmoured',
            'defenseless',
            'defenceless',
            'undefended',
            'defender',
            'blocked',
            'stopped',
            'intercepted',
            'interception',
            'saved',
            'thwarted',
            'threat',
            'prevention',
            'unprevented',
            'antivirus',
            'vigilance',
            'vigilant',
            'detection',
            'detected',
            'scanned',
            'found',
            'exploit',
            'vulnerability',
            'vulnerable',
            'weakness',
            'infection',
            'infected',
            'comprimised',
            'data leak',
            'audited',
            'admin',
            'verification',
            'unverified',
            'uncertified',
            'warning',
            'emergency',
            'attention',
            'urgent',
            'alarm',
            'crest',
            'bravery',
            'strength',
            'tough',
            'attacked',
            'damaged',
            'injured',
            'hit',
            'expired',
            'disabled',
            'inactive',
            'error',
            'exclamation mark',
            '!',
        ],
        categories: [
            'account',
            'security',
            'development',
            'notifications',
            'gaming',
        ],
    },
    {
        icon: 'ShieldBan',
        name: 'shield-ban',
        tags: [
            'unshielded',
            'cybersecurity',
            'insecure',
            'unsecured',
            'safety',
            'unsafe',
            'protection',
            'unprotected',
            'guardian',
            'unguarded',
            'unarmored',
            'unarmoured',
            'defenseless',
            'defenceless',
            'undefended',
            'defender',
            'blocked',
            'stopped',
            'intercepted',
            'interception',
            'saved',
            'thwarted',
            'threat',
            'prevention',
            'unprevented',
            'antivirus',
            'vigilance',
            'vigilant',
            'detection',
            'detected',
            'scanned',
            'found',
            'exploit',
            'vulnerability',
            'vulnerable',
            'weakness',
            'infection',
            'infected',
            'comprimised',
            'data leak',
            'audited',
            'admin',
            'verification',
            'unverified',
            'uncertified',
            'cancel',
            'error',
            'crest',
            'bravery',
            'attacked',
            'damaged',
            'injured',
            'hit',
            'expired',
            'eliminated',
            'disabled',
            'inactive',
            '/',
        ],
        categories: [
            'account',
            'security',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'ShieldCheck',
        name: 'shield-check',
        tags: [
            'cybersecurity',
            'secured',
            'safety',
            'protection',
            'protected',
            'guardian',
            'guarded',
            'armored',
            'armoured',
            'defense',
            'defence',
            'defended',
            'blocked',
            'threat',
            'prevention',
            'prevented',
            'antivirus',
            'vigilance',
            'vigilant',
            'active',
            'activated',
            'enabled',
            'detection',
            'scanned',
            'found',
            'strength',
            'strong',
            'tough',
            'invincible',
            'invincibility',
            'invulnerable',
            'undamaged',
            'audited',
            'admin',
            'verification',
            'verified',
            'certification',
            'certified',
            'tested',
            'passed',
            'qualified',
            'cleared',
            'cleaned',
            'disinfected',
            'uninfected',
            'task',
            'completed',
            'todo',
            'done',
            'ticked',
            'checked',
            'crest',
            'bravery',
        ],
        categories: [
            'account',
            'security',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'ShieldEllipsis',
        name: 'shield-ellipsis',
        tags: [
            'cybersecurity',
            'securing',
            'protecting',
            'guarding',
            'armoring',
            'armouring',
            'defending',
            'blocking',
            'preventing',
            'antivirus',
            'detecting',
            'scanning',
            'finding',
            'auditing',
            'admin',
            'verifying',
            'crest',
            'upgrading',
            'loader',
            'loading',
            'throbber',
            'progress',
            'dots',
            'more',
            'etc',
            '...',
            '…',
        ],
        categories: [
            'account',
            'security',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'ShieldHalf',
        name: 'shield-half',
        tags: [
            'cybersecurity',
            'secure',
            'safety',
            'protection',
            'guardian',
            'armored',
            'armoured',
            'defense',
            'defence',
            'defender',
            'block',
            'threat',
            'prevention',
            'antivirus',
            'vigilance',
            'vigilant',
            'detection',
            'scan',
            'strength',
            'strong',
            'tough',
            'invincible',
            'invincibility',
            'invulnerable',
            'undamaged',
            'audit',
            'admin',
            'verification',
            'crest',
            'logo',
            'sigil',
            'flag',
            'team',
            'faction',
            'fraternity',
            'university',
            'college',
            'academy',
            'school',
            'education',
            'uniform',
            'bravery',
            'knight',
            'foot soldier',
            'infantry',
            'trooper',
            'pawn',
            'battle',
            'war',
            'military',
            'ranking',
            'army',
            'cadet',
            'scout',
        ],
        categories: [
            'account',
            'security',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'ShieldMinus',
        name: 'shield-minus',
        tags: [
            'unshield',
            'cybersecurity',
            'unsecure',
            'unguard',
            'unblock',
            'antivirus',
            'clean',
            'clear',
            'disinfect',
            'patch',
            'fix',
            'stop',
            'cancel',
            'remove',
            'relax',
            'admin',
            'crest',
            'bravery',
            'weakened',
            'damaged',
            'hit',
            'unarm',
            'disable',
            'deactivate',
            'decommission',
            'downgraded',
            'minimum',
            '-',
        ],
        categories: [
            'account',
            'security',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'ShieldOff',
        name: 'shield-off',
        tags: [
            'unshielded',
            'cybersecurity',
            'insecure',
            'unsecured',
            'safety',
            'unsafe',
            'protection',
            'unprotected',
            'guardian',
            'unguarded',
            'unarmored',
            'unarmoured',
            'defenseless',
            'defenceless',
            'undefended',
            'defender',
            'interception',
            'threat',
            'prevention',
            'unprevented',
            'antivirus',
            'detection',
            'undetected',
            'exploit',
            'vulnerability',
            'vulnerable',
            'weakness',
            'infected',
            'infection',
            'comprimised',
            'data leak',
            'unaudited',
            'admin',
            'verification',
            'unverified',
            'inactive',
            'cancelled',
            'error',
            'crest',
            'bravery',
            'damaged',
            'injured',
            'hit',
            'expired',
            'eliminated',
        ],
        categories: [
            'account',
            'security',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'ShieldPlus',
        name: 'shield-plus',
        tags: [
            'cybersecurity',
            'secure',
            'safety',
            'protection',
            'guardian',
            'armored',
            'armoured',
            'defense',
            'defence',
            'defender',
            'block',
            'threat',
            'prevention',
            'antivirus',
            'vigilance',
            'vigilant',
            'detection',
            'scan',
            'strength',
            'strong',
            'tough',
            'invincible',
            'invincibility',
            'invulnerable',
            'undamaged',
            'extra',
            'added',
            'professional',
            'enterprise',
            'full',
            'maximum',
            'upgraded',
            'ultra',
            'activate',
            'enable',
            'audit',
            'admin',
            'verification',
            'crest',
            'medic',
            '+',
        ],
        categories: [
            'account',
            'security',
            'development',
            'gaming',
            'medical',
        ],
    },
    {
        icon: 'ShieldQuestion',
        name: 'shield-question',
        tags: [
            'unshielded',
            'cybersecurity',
            'insecure',
            'unsecured',
            'safety',
            'unsafe',
            'protection',
            'unprotected',
            'guardian',
            'unguarded',
            'unarmored',
            'unarmoured',
            'defenseless',
            'defenceless',
            'undefended',
            'defender',
            'threat',
            'prevention',
            'unprevented',
            'antivirus',
            'vigilance',
            'vigilant',
            'detection',
            'undetected',
            'scan',
            'find',
            'exploit',
            'vulnerability',
            'vulnerable',
            'weakness',
            'infection',
            'comprimised',
            'data leak',
            'audit',
            'admin',
            'verification',
            'unverified',
            'uncertified',
            'uncertain',
            'unknown',
            'inactive',
            'crest',
            'question mark',
            '?',
        ],
        categories: [
            'account',
            'security',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'ShieldUser',
        name: 'shield-user',
        tags: [
            'shield',
            'user',
            'admin',
            'protection',
            'protected',
            'safety',
            'guard',
        ],
        categories: [
            'account',
            'security',
            'development',
        ],
    },
    {
        icon: 'ShieldX',
        name: 'shield-x',
        tags: [
            'unshielded',
            'cybersecurity',
            'insecure',
            'unsecured',
            'safety',
            'unsafe',
            'protection',
            'unprotected',
            'guardian',
            'unguarded',
            'unarmored',
            'unarmoured',
            'defenseless',
            'defenceless',
            'undefended',
            'defender',
            'blocked',
            'stopped',
            'intercepted',
            'interception',
            'saved',
            'thwarted',
            'threat',
            'prevention',
            'prevented',
            'antivirus',
            'vigilance',
            'vigilant',
            'detection',
            'detected',
            'scanned',
            'found',
            'exploit',
            'vulnerability',
            'vulnerable',
            'weakness',
            'infection',
            'infected',
            'comprimised',
            'data leak',
            'audited',
            'admin',
            'verification',
            'unverified',
            'inactive',
            'cancel',
            'error',
            'wrong',
            'false',
            'crest',
            'bravery',
            'attacked',
            'damaged',
            'injured',
            'hit',
            'dead',
            'deceased',
            'expired',
            'eliminated',
            'exterminated',
        ],
        categories: [
            'account',
            'security',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'Shield',
        name: 'shield',
        tags: [
            'cybersecurity',
            'secure',
            'safety',
            'protection',
            'guardian',
            'armored',
            'armoured',
            'defense',
            'defence',
            'defender',
            'block',
            'threat',
            'prevention',
            'antivirus',
            'vigilance',
            'vigilant',
            'detection',
            'scan',
            'find',
            'strength',
            'strong',
            'tough',
            'invincible',
            'invincibility',
            'invulnerable',
            'undamaged',
            'audit',
            'admin',
            'verification',
            'crest',
            'bravery',
            'knight',
            'foot soldier',
            'infantry',
            'trooper',
            'pawn',
            'battle',
            'war',
            'military',
            'army',
            'cadet',
            'scout',
        ],
        categories: [
            'account',
            'security',
            'development',
            'gaming',
            'shapes',
        ],
    },
    {
        icon: 'Slack',
        name: 'slack',
        tags: [
            'logo',
        ],
        categories: [
            'account',
            'social',
            'brands',
            'development',
        ],
    },
    {
        icon: 'SlidersHorizontal',
        name: 'sliders-horizontal',
        tags: [
            'settings',
            'filters',
            'controls',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'SlidersVertical',
        name: 'sliders-vertical',
        tags: [
            'settings',
            'controls',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'SquareUserRound',
        name: 'square-user-round',
        tags: [
            'person',
            'account',
            'contact',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'SquareUser',
        name: 'square-user',
        tags: [
            'person',
            'account',
            'contact',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'Star',
        name: 'star',
        tags: [
            'bookmark',
            'favorite',
            'like',
            'review',
            'rating',
        ],
        categories: [
            'account',
            'social',
            'shapes',
            'multimedia',
            'weather',
            'emoji',
            'gaming',
        ],
    },
    {
        icon: 'Tag',
        name: 'tag',
        tags: [
            'label',
            'badge',
            'ticket',
            'mark',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'Tags',
        name: 'tags',
        tags: [
            'labels',
            'badges',
            'tickets',
            'marks',
            'copy',
            'multiple',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'ThumbsDown',
        name: 'thumbs-down',
        tags: [
            'dislike',
            'bad',
            'emotion',
        ],
        categories: [
            'account',
            'social',
            'emoji',
        ],
    },
    {
        icon: 'ThumbsUp',
        name: 'thumbs-up',
        tags: [
            'like',
            'good',
            'emotion',
        ],
        categories: [
            'account',
            'social',
            'emoji',
        ],
    },
    {
        icon: 'Ticket',
        name: 'ticket',
        tags: [
            'entry',
            'pass',
            'voucher',
            'event',
            'concert',
            'show',
            'perforated',
            'dashed',
        ],
        categories: [
            'account',
            'transportation',
        ],
    },
    {
        icon: 'Trello',
        name: 'trello',
        tags: [
            'logo',
            'brand',
        ],
        categories: [
            'account',
            'brands',
            'development',
        ],
    },
    {
        icon: 'UserCheck',
        name: 'user-check',
        tags: [
            'followed',
            'subscribed',
            'done',
            'todo',
            'tick',
            'complete',
            'task',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'UserCog',
        name: 'user-cog',
        tags: [
            'settings',
            'edit',
            'cog',
            'gear',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'UserLock',
        name: 'user-lock',
        tags: [
            'person',
            'lock',
            'locked',
            'account',
            'secure',
        ],
        categories: [
            'account',
            'security',
        ],
    },
    {
        icon: 'UserMinus',
        name: 'user-minus',
        tags: [
            'delete',
            'remove',
            'unfollow',
            'unsubscribe',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'UserPen',
        name: 'user-pen',
        tags: [
            'person',
            'account',
            'contact',
            'profile',
            'edit',
            'change',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'UserPlus',
        name: 'user-plus',
        tags: [
            'new',
            'add',
            'create',
            'follow',
            'subscribe',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'UserRoundCheck',
        name: 'user-round-check',
        tags: [
            'followed',
            'subscribed',
            'done',
            'todo',
            'tick',
            'complete',
            'task',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'UserRoundCog',
        name: 'user-round-cog',
        tags: [
            'settings',
            'edit',
            'cog',
            'gear',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'UserRoundMinus',
        name: 'user-round-minus',
        tags: [
            'delete',
            'remove',
            'unfollow',
            'unsubscribe',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'UserRoundPen',
        name: 'user-round-pen',
        tags: [
            'person',
            'account',
            'contact',
            'profile',
            'edit',
            'change',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'UserRoundPlus',
        name: 'user-round-plus',
        tags: [
            'new',
            'add',
            'create',
            'follow',
            'subscribe',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'UserRoundSearch',
        name: 'user-round-search',
        tags: [
            'person',
            'account',
            'contact',
            'find',
            'scan',
            'magnifier',
            'magnifying glass',
            'lens',
        ],
        categories: [
            'account',
            'social',
        ],
    },
    {
        icon: 'UserRoundX',
        name: 'user-round-x',
        tags: [
            'delete',
            'remove',
            'unfollow',
            'unsubscribe',
            'unavailable',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'UserRound',
        name: 'user-round',
        tags: [
            'person',
            'account',
            'contact',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'UserSearch',
        name: 'user-search',
        tags: [
            'person',
            'account',
            'contact',
            'find',
            'scan',
            'magnifier',
            'magnifying glass',
            'lens',
        ],
        categories: [
            'account',
            'social',
        ],
    },
    {
        icon: 'UserX',
        name: 'user-x',
        tags: [
            'delete',
            'remove',
            'unfollow',
            'unsubscribe',
            'unavailable',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'User',
        name: 'user',
        tags: [
            'person',
            'account',
            'contact',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'UsersRound',
        name: 'users-round',
        tags: [
            'group',
            'people',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'Users',
        name: 'users',
        tags: [
            'group',
            'people',
        ],
        categories: [
            'account',
        ],
    },
    {
        icon: 'VenetianMask',
        name: 'venetian-mask',
        tags: [
            'mask',
            'masquerade',
            'impersonate',
            'secret',
            'incognito',
        ],
        categories: [
            'account',
            'gaming',
        ],
    },
    {
        icon: 'WalletCards',
        name: 'wallet-cards',
        tags: [
            'money',
            'finance',
            'pocket',
            'credit',
            'purchase',
            'payment',
            'shopping',
            'retail',
            'consumer',
            'cc',
        ],
        categories: [
            'account',
            'finance',
        ],
    },
    {
        icon: 'WalletMinimal',
        name: 'wallet-minimal',
        tags: [
            'finance',
            'pocket',
        ],
        categories: [
            'account',
            'finance',
        ],
    },
    {
        icon: 'Wallet',
        name: 'wallet',
        tags: [
            'money',
            'finance',
            'pocket',
        ],
        categories: [
            'account',
            'finance',
        ],
    },
    {
        icon: 'Wallpaper',
        name: 'wallpaper',
        tags: [
            'cover',
            'lock screen',
        ],
        categories: [
            'account',
            'devices',
        ],
    },
    {
        icon: 'Wrench',
        name: 'wrench',
        tags: [
            'account',
            'settings',
            'spanner',
            'diy',
            'toolbox',
            'build',
            'construction',
        ],
        categories: [
            'account',
            'development',
            'tools',
        ],
    },
];
export default icons;
