// Icons with primary category: animals
const icons = [
    {
        icon: 'Bird',
        name: 'bird',
        tags: [
            'peace',
            'freedom',
            'wing',
            'avian',
            'tweet',
        ],
        categories: [
            'animals',
        ],
    },
    {
        icon: 'Bone',
        name: 'bone',
        tags: [
            'health',
            'skeleton',
            'skull',
            'death',
            'pets',
            'dog',
        ],
        categories: [
            'animals',
            'medical',
            'gaming',
        ],
    },
    {
        icon: 'Cat',
        name: 'cat',
        tags: [
            'animal',
            'pet',
            'kitten',
            'feline',
        ],
        categories: [
            'animals',
        ],
    },
    {
        icon: 'Dog',
        name: 'dog',
        tags: [
            'animal',
            'pet',
            'puppy',
            'hound',
            'canine',
        ],
        categories: [
            'animals',
        ],
    },
    {
        icon: 'Origami',
        name: 'origami',
        tags: [
            'paper',
            'bird',
        ],
        categories: [
            'animals',
            'design',
        ],
    },
    {
        icon: 'Panda',
        name: 'panda',
        tags: [
            'animal',
            'wildlife',
            'bear',
            'zoo',
            'bamboo',
        ],
        categories: [
            'animals',
        ],
    },
    {
        icon: 'PawPrint',
        name: 'paw-print',
        tags: [
            'pets',
            'vets',
            'veterinarian',
            'domesticated',
            'cat',
            'dog',
            'bear',
        ],
        categories: [
            'animals',
        ],
    },
    {
        icon: 'Rabbit',
        name: 'rabbit',
        tags: [
            'animal',
            'rodent',
            'pet',
            'pest',
            'bunny',
            'hare',
            'fast',
            'speed',
            'hop',
        ],
        categories: [
            'animals',
        ],
    },
    {
        icon: 'Rat',
        name: 'rat',
        tags: [
            'mouse',
            'mice',
            'gerbil',
            'rodent',
            'pet',
            'pest',
            'plague',
            'disease',
        ],
        categories: [
            'animals',
        ],
    },
    {
        icon: 'Shell',
        name: 'shell',
        tags: [
            'beach',
            'sand',
            'holiday',
            'sealife',
            'fossil',
            'ammonite',
            'biology',
            'ocean',
            'terminal',
            'command line',
            'session',
            'bash',
            'zsh',
            'roll',
            'wrap',
            'chewing gum',
            'bubble gum',
            'sweet',
            'sugar',
            'hosepipe',
            'carpet',
            'string',
            'spiral',
            'spinner',
            'hypnotise',
            'hypnosis',
        ],
        categories: [
            'animals',
            'development',
            'nature',
            'science',
            'travel',
            'food-beverage',
            'home',
        ],
    },
    {
        icon: 'Shrimp',
        name: 'shrimp',
        tags: [
            'seafood',
            'shellfish',
            'crustacean',
            'prawn',
            'scallop',
            'whelk',
            'arthropod',
            'littleneck',
            'quahog',
            'cherrystone',
        ],
        categories: [
            'animals',
        ],
    },
    {
        icon: 'Snail',
        name: 'snail',
        tags: [
            'animal',
            'insect',
            'slow',
            'speed',
            'delicacy',
            'spiral',
        ],
        categories: [
            'animals',
            'food-beverage',
        ],
    },
    {
        icon: 'Squirrel',
        name: 'squirrel',
        tags: [
            'animal',
            'rodent',
            'pet',
            'pest',
            'nuts',
            'retrieve',
            'updates',
            'storage',
            'stash',
        ],
        categories: [
            'animals',
        ],
    },
    {
        icon: 'Turtle',
        name: 'turtle',
        tags: [
            'animal',
            'pet',
            'tortoise',
            'slow',
            'speed',
        ],
        categories: [
            'animals',
        ],
    },
    {
        icon: 'Worm',
        name: 'worm',
        tags: [
            'invertebrate',
            'grub',
            'larva',
            'snake',
            'crawl',
            'wiggle',
            'slither',
            'pest control',
            'computer virus',
            'malware',
        ],
        categories: [
            'animals',
            'security',
        ],
    },
];
export default icons;
