// Icons with primary category: arrows
const icons = [
    {
        icon: 'ArrowBigDownDash',
        name: 'arrow-big-down-dash',
        tags: [
            'backwards',
            'reverse',
            'slow',
            'direction',
            'south',
            'download',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
            'files',
        ],
    },
    {
        icon: 'ArrowBigDown',
        name: 'arrow-big-down',
        tags: [
            'backwards',
            'reverse',
            'direction',
            'south',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'ArrowBigLeftDash',
        name: 'arrow-big-left-dash',
        tags: [
            'previous',
            'back',
            'direction',
            'west',
            'turn',
            'corner',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'ArrowBigLeft',
        name: 'arrow-big-left',
        tags: [
            'previous',
            'back',
            'direction',
            'west',
            'indicate turn',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'ArrowBigRightDash',
        name: 'arrow-big-right-dash',
        tags: [
            'next',
            'forward',
            'direction',
            'east',
            'turn',
            'corner',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'ArrowBigRight',
        name: 'arrow-big-right',
        tags: [
            'next',
            'forward',
            'direction',
            'east',
            'indicate turn',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'ArrowBigUpDash',
        name: 'arrow-big-up-dash',
        tags: [
            'caps lock',
            'capitals',
            'keyboard',
            'button',
            'mac',
            'forward',
            'direction',
            'north',
            'faster',
            'speed',
            'boost',
        ],
        categories: [
            'arrows',
            'navigation',
            'text',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'ArrowBigUp',
        name: 'arrow-big-up',
        tags: [
            'shift',
            'keyboard',
            'button',
            'mac',
            'capitalize',
            'capitalise',
            'forward',
            'direction',
            'north',
        ],
        categories: [
            'arrows',
            'navigation',
            'text',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'ArrowDownFromLine',
        name: 'arrow-down-from-line',
        tags: [
            'backwards',
            'reverse',
            'direction',
            'south',
            'download',
            'expand',
            'fold',
            'vertical',
        ],
        categories: [
            'arrows',
            'navigation',
            'files',
        ],
    },
    {
        icon: 'ArrowDownLeft',
        name: 'arrow-down-left',
        tags: [
            'direction',
            'south-west',
            'diagonal',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowDownRight',
        name: 'arrow-down-right',
        tags: [
            'direction',
            'south-east',
            'diagonal',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowDownToDot',
        name: 'arrow-down-to-dot',
        tags: [
            'direction',
            'south',
            'waypoint',
            'location',
            'step',
            'into',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowDownToLine',
        name: 'arrow-down-to-line',
        tags: [
            'behind',
            'direction',
            'south',
            'download',
            'save',
            'git',
            'version control',
            'pull',
            'collapse',
            'fold',
            'vertical',
        ],
        categories: [
            'arrows',
            'navigation',
            'files',
            'development',
        ],
    },
    {
        icon: 'ArrowDownUp',
        name: 'arrow-down-up',
        tags: [
            'bidirectional',
            'two-way',
            '2-way',
            'swap',
            'switch',
            'network',
            'traffic',
            'flow',
            'mobile data',
            'internet',
            'sort',
            'reorder',
            'move',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowDown',
        name: 'arrow-down',
        tags: [
            'backwards',
            'reverse',
            'direction',
            'south',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowLeftFromLine',
        name: 'arrow-left-from-line',
        tags: [
            'previous',
            'back',
            'direction',
            'west',
            'expand',
            'fold',
            'horizontal',
            '<-|',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowLeftRight',
        name: 'arrow-left-right',
        tags: [
            'bidirectional',
            'two-way',
            '2-way',
            'swap',
            'switch',
            'transaction',
            'reorder',
            'move',
            '<-',
            '->',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowLeftToLine',
        name: 'arrow-left-to-line',
        tags: [
            'previous',
            'back',
            'direction',
            'west',
            'collapse',
            'fold',
            'horizontal',
            '|<-',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowLeft',
        name: 'arrow-left',
        tags: [
            'previous',
            'back',
            'direction',
            'west',
            '<-',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowRightFromLine',
        name: 'arrow-right-from-line',
        tags: [
            'next',
            'forward',
            'direction',
            'east',
            'export',
            'expand',
            'fold',
            'horizontal',
            '|->',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowRightLeft',
        name: 'arrow-right-left',
        tags: [
            'bidirectional',
            'two-way',
            '2-way',
            'swap',
            'switch',
            'transaction',
            'reorder',
            'move',
            '<-',
            '->',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowRightToLine',
        name: 'arrow-right-to-line',
        tags: [
            'next',
            'forward',
            'direction',
            'east',
            'tab',
            'keyboard',
            'mac',
            'indent',
            'collapse',
            'fold',
            'horizontal',
            '->|',
        ],
        categories: [
            'arrows',
            'navigation',
            'development',
        ],
    },
    {
        icon: 'ArrowRight',
        name: 'arrow-right',
        tags: [
            'forward',
            'next',
            'direction',
            'east',
            '->',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowUpDown',
        name: 'arrow-up-down',
        tags: [
            'bidirectional',
            'two-way',
            '2-way',
            'swap',
            'switch',
            'network',
            'mobile data',
            'internet',
            'sort',
            'reorder',
            'move',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowUpFromDot',
        name: 'arrow-up-from-dot',
        tags: [
            'direction',
            'north',
            'step',
            'out',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowUpFromLine',
        name: 'arrow-up-from-line',
        tags: [
            'forward',
            'direction',
            'north',
            'upload',
            'git',
            'version control',
            'push',
            'expand',
            'fold',
            'vertical',
        ],
        categories: [
            'arrows',
            'navigation',
            'files',
            'development',
        ],
    },
    {
        icon: 'ArrowUpLeft',
        name: 'arrow-up-left',
        tags: [
            'direction',
            'north-west',
            'diagonal',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowUpRight',
        name: 'arrow-up-right',
        tags: [
            'direction',
            'north-east',
            'diagonal',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowUpToLine',
        name: 'arrow-up-to-line',
        tags: [
            'forward',
            'direction',
            'north',
            'upload',
            'collapse',
            'fold',
            'vertical',
        ],
        categories: [
            'arrows',
            'navigation',
            'files',
        ],
    },
    {
        icon: 'ArrowUp',
        name: 'arrow-up',
        tags: [
            'forward',
            'direction',
            'north',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ArrowsUpFromLine',
        name: 'arrows-up-from-line',
        tags: [
            'direction',
            'orientation',
            'this way up',
            'vertical',
            'package',
            'box',
            'fragile',
            'postage',
            'shipping',
        ],
        categories: [
            'arrows',
            'transportation',
            'mail',
        ],
    },
    {
        icon: 'CalendarSync',
        name: 'calendar-sync',
        tags: [
            'repeat',
            'refresh',
            'reconnect',
            'transfer',
            'backup',
            'date',
            'month',
            'year',
            'event',
            'subscribe',
            'recurring',
            'schedule',
            'reminder',
            'automatic',
            'auto',
        ],
        categories: [
            'arrows',
            'time',
        ],
    },
    {
        icon: 'ChevronDown',
        name: 'chevron-down',
        tags: [
            'backwards',
            'reverse',
            'slow',
            'dropdown',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'ChevronFirst',
        name: 'chevron-first',
        tags: [
            'previous',
            'music',
        ],
        categories: [
            'arrows',
            'multimedia',
        ],
    },
    {
        icon: 'ChevronLast',
        name: 'chevron-last',
        tags: [
            'skip',
            'next',
            'music',
        ],
        categories: [
            'arrows',
            'multimedia',
        ],
    },
    {
        icon: 'ChevronLeft',
        name: 'chevron-left',
        tags: [
            'back',
            'previous',
            'less than',
            'fewer',
            'menu',
            '<',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'ChevronRight',
        name: 'chevron-right',
        tags: [
            'forward',
            'next',
            'more than',
            'greater',
            'menu',
            'code',
            'coding',
            'command line',
            'terminal',
            'prompt',
            'shell',
            '>',
        ],
        categories: [
            'arrows',
            'navigation',
            'math',
            'development',
        ],
    },
    {
        icon: 'ChevronUp',
        name: 'chevron-up',
        tags: [
            'caret',
            'keyboard',
            'mac',
            'control',
            'ctrl',
            'superscript',
            'exponential',
            'power',
            'ahead',
            'fast',
            '^',
            'dropdown',
        ],
        categories: [
            'arrows',
            'navigation',
            'math',
            'gaming',
        ],
    },
    {
        icon: 'ChevronsDownUp',
        name: 'chevrons-down-up',
        tags: [
            'collapse',
            'fold',
            'vertical',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'ChevronsDown',
        name: 'chevrons-down',
        tags: [
            'backwards',
            'reverse',
            'slower',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'ChevronsLeftRight',
        name: 'chevrons-left-right',
        tags: [
            'expand',
            'horizontal',
            'unfold',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'ChevronsLeft',
        name: 'chevrons-left',
        tags: [
            'turn',
            'corner',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'ChevronsRightLeft',
        name: 'chevrons-right-left',
        tags: [
            'collapse',
            'fold',
            'horizontal',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'ChevronsRight',
        name: 'chevrons-right',
        tags: [
            'turn',
            'corner',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'ChevronsUpDown',
        name: 'chevrons-up-down',
        tags: [
            'expand',
            'unfold',
            'vertical',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'ChevronsUp',
        name: 'chevrons-up',
        tags: [
            'forward',
            'ahead',
            'faster',
            'speed',
            'boost',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'CircleArrowDown',
        name: 'circle-arrow-down',
        tags: [
            'backwards',
            'reverse',
            'direction',
            'south',
            'sign',
            'button',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'CircleArrowLeft',
        name: 'circle-arrow-left',
        tags: [
            'previous',
            'back',
            'direction',
            'west',
            'sign',
            'turn',
            'button',
            '<-',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'CircleArrowOutDownLeft',
        name: 'circle-arrow-out-down-left',
        tags: [
            'outwards',
            'direction',
            'south-west',
            'diagonal',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'CircleArrowOutDownRight',
        name: 'circle-arrow-out-down-right',
        tags: [
            'outwards',
            'direction',
            'south-east',
            'diagonal',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'CircleArrowOutUpLeft',
        name: 'circle-arrow-out-up-left',
        tags: [
            'outwards',
            'direction',
            'north-west',
            'diagonal',
            'keyboard',
            'button',
            'escape',
        ],
        categories: [
            'arrows',
            'navigation',
            'development',
        ],
    },
    {
        icon: 'CircleArrowOutUpRight',
        name: 'circle-arrow-out-up-right',
        tags: [
            'outwards',
            'direction',
            'north-east',
            'diagonal',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'CircleArrowRight',
        name: 'circle-arrow-right',
        tags: [
            'next',
            'forward',
            'direction',
            'east',
            'sign',
            'turn',
            'button',
            '->',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'CircleArrowUp',
        name: 'circle-arrow-up',
        tags: [
            'forward',
            'direction',
            'north',
            'sign',
            'button',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'CircleChevronDown',
        name: 'circle-chevron-down',
        tags: [
            'back',
            'menu',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'CircleChevronLeft',
        name: 'circle-chevron-left',
        tags: [
            'back',
            'previous',
            'less than',
            'fewer',
            'menu',
            '<',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'CircleChevronRight',
        name: 'circle-chevron-right',
        tags: [
            'back',
            'more than',
            'greater',
            'menu',
            '>',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'CircleChevronUp',
        name: 'circle-chevron-up',
        tags: [
            'caret',
            'ahead',
            'menu',
            '^',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'CircleFadingArrowUp',
        name: 'circle-fading-arrow-up',
        tags: [
            'north',
            'up',
            'upgrade',
            'improve',
            'circle',
            'button',
        ],
        categories: [
            'arrows',
            'development',
        ],
    },
    {
        icon: 'CloudDownload',
        name: 'cloud-download',
        tags: [
            'import',
        ],
        categories: [
            'arrows',
            'files',
        ],
    },
    {
        icon: 'CloudUpload',
        name: 'cloud-upload',
        tags: [
            'file',
        ],
        categories: [
            'arrows',
            'files',
        ],
    },
    {
        icon: 'CornerDownLeft',
        name: 'corner-down-left',
        tags: [
            'arrow',
            'return',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'CornerDownRight',
        name: 'corner-down-right',
        tags: [
            'arrow',
            'indent',
            'tab',
        ],
        categories: [
            'arrows',
            'text',
            'development',
        ],
    },
    {
        icon: 'CornerLeftDown',
        name: 'corner-left-down',
        tags: [
            'arrow',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'CornerLeftUp',
        name: 'corner-left-up',
        tags: [
            'arrow',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'CornerRightDown',
        name: 'corner-right-down',
        tags: [
            'arrow',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'CornerRightUp',
        name: 'corner-right-up',
        tags: [
            'arrow',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'CornerUpLeft',
        name: 'corner-up-left',
        tags: [
            'arrow',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'CornerUpRight',
        name: 'corner-up-right',
        tags: [
            'arrow',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'Download',
        name: 'download',
        tags: [
            'import',
            'export',
            'save',
        ],
        categories: [
            'arrows',
            'files',
        ],
    },
    {
        icon: 'ExternalLink',
        name: 'external-link',
        tags: [
            'outbound',
            'open',
            'share',
        ],
        categories: [
            'arrows',
            'text',
            'social',
        ],
    },
    {
        icon: 'FoldHorizontal',
        name: 'fold-horizontal',
        tags: [
            'arrow',
            'collapse',
            'fold',
            'vertical',
            'dashed',
        ],
        categories: [
            'arrows',
            'layout',
        ],
    },
    {
        icon: 'FoldVertical',
        name: 'fold-vertical',
        tags: [
            'arrow',
            'collapse',
            'fold',
            'vertical',
            'dashed',
        ],
        categories: [
            'arrows',
            'layout',
        ],
    },
    {
        icon: 'History',
        name: 'history',
        tags: [
            'time',
            'redo',
            'undo',
            'rewind',
            'timeline',
            'version',
            'time machine',
            'backup',
            'rotate',
            'ccw',
        ],
        categories: [
            'arrows',
            'time',
        ],
    },
    {
        icon: 'Import',
        name: 'import',
        tags: [
            'save',
        ],
        categories: [
            'arrows',
            'files',
        ],
    },
    {
        icon: 'IterationCcw',
        name: 'iteration-ccw',
        tags: [
            'arrow',
            'right',
        ],
        categories: [
            'arrows',
            'design',
        ],
    },
    {
        icon: 'IterationCw',
        name: 'iteration-cw',
        tags: [
            'arrow',
            'left',
        ],
        categories: [
            'arrows',
            'design',
        ],
    },
    {
        icon: 'LassoSelect',
        name: 'lasso-select',
        tags: [
            'select',
            'cursor',
        ],
        categories: [
            'arrows',
            'design',
            'cursors',
        ],
    },
    {
        icon: 'LogIn',
        name: 'log-in',
        tags: [
            'sign in',
            'arrow',
            'enter',
            'auth',
        ],
        categories: [
            'arrows',
            'account',
        ],
    },
    {
        icon: 'LogOut',
        name: 'log-out',
        tags: [
            'sign out',
            'arrow',
            'exit',
            'auth',
        ],
        categories: [
            'arrows',
            'account',
        ],
    },
    {
        icon: 'Maximize2',
        name: 'maximize-2',
        tags: [
            'fullscreen',
            'arrows',
            'expand',
        ],
        categories: [
            'arrows',
            'layout',
            'design',
        ],
    },
    {
        icon: 'Milestone',
        name: 'milestone',
        tags: [
            'signpost',
            'direction',
            'right',
            'east',
            'forward',
            'version control',
            'waypoint',
        ],
        categories: [
            'arrows',
            'navigation',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'Minimize2',
        name: 'minimize-2',
        tags: [
            'exit fullscreen',
            'arrows',
            'close',
            'shrink',
        ],
        categories: [
            'arrows',
            'layout',
            'design',
        ],
    },
    {
        icon: 'MousePointer2',
        name: 'mouse-pointer-2',
        tags: [
            'click',
            'select',
        ],
        categories: [
            'arrows',
            'cursors',
        ],
    },
    {
        icon: 'MousePointerBan',
        name: 'mouse-pointer-ban',
        tags: [
            'wait',
            'busy',
            'loading',
            'blocked',
            'frozen',
            'freeze',
        ],
        categories: [
            'arrows',
            'cursors',
        ],
    },
    {
        icon: 'MousePointerClick',
        name: 'mouse-pointer-click',
        tags: [
            'click',
            'select',
        ],
        categories: [
            'arrows',
            'cursors',
        ],
    },
    {
        icon: 'MousePointer',
        name: 'mouse-pointer',
        tags: [
            'click',
            'select',
        ],
        categories: [
            'arrows',
            'cursors',
        ],
    },
    {
        icon: 'MoveDiagonal2',
        name: 'move-diagonal-2',
        tags: [
            'double',
            'arrow',
        ],
        categories: [
            'arrows',
            'cursors',
        ],
    },
    {
        icon: 'MoveDiagonal',
        name: 'move-diagonal',
        tags: [
            'double',
            'arrow',
        ],
        categories: [
            'arrows',
            'cursors',
        ],
    },
    {
        icon: 'MoveDownLeft',
        name: 'move-down-left',
        tags: [
            'arrow',
            'direction',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'MoveDownRight',
        name: 'move-down-right',
        tags: [
            'arrow',
            'direction',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'MoveDown',
        name: 'move-down',
        tags: [
            'arrow',
            'direction',
            'downwards',
            'south',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'MoveHorizontal',
        name: 'move-horizontal',
        tags: [
            'double',
            'arrow',
        ],
        categories: [
            'arrows',
            'cursors',
        ],
    },
    {
        icon: 'MoveLeft',
        name: 'move-left',
        tags: [
            'arrow',
            'direction',
            'back',
            'west',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'MoveRight',
        name: 'move-right',
        tags: [
            'arrow',
            'direction',
            'trend flat',
            'east',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'MoveUpLeft',
        name: 'move-up-left',
        tags: [
            'arrow',
            'direction',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'MoveUpRight',
        name: 'move-up-right',
        tags: [
            'arrow',
            'direction',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'MoveUp',
        name: 'move-up',
        tags: [
            'arrow',
            'direction',
            'upwards',
            'north',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'MoveVertical',
        name: 'move-vertical',
        tags: [
            'double',
            'arrow',
        ],
        categories: [
            'arrows',
            'cursors',
        ],
    },
    {
        icon: 'Move',
        name: 'move',
        tags: [
            'arrows',
        ],
        categories: [
            'arrows',
            'cursors',
        ],
    },
    {
        icon: 'PhoneForwarded',
        name: 'phone-forwarded',
        tags: [
            'call',
        ],
        categories: [
            'arrows',
            'connectivity',
            'devices',
            'communication',
        ],
    },
    {
        icon: 'PhoneIncoming',
        name: 'phone-incoming',
        tags: [
            'call',
        ],
        categories: [
            'arrows',
            'connectivity',
            'devices',
            'communication',
        ],
    },
    {
        icon: 'PhoneOutgoing',
        name: 'phone-outgoing',
        tags: [
            'call',
        ],
        categories: [
            'arrows',
            'connectivity',
            'devices',
            'communication',
        ],
    },
    {
        icon: 'Play',
        name: 'play',
        tags: [
            'music',
            'audio',
            'video',
            'start',
            'run',
        ],
        categories: [
            'arrows',
            'multimedia',
        ],
    },
    {
        icon: 'RefreshCcwDot',
        name: 'refresh-ccw-dot',
        tags: [
            'arrows',
            'rotate',
            'reload',
            'synchronise',
            'synchronize',
            'circular',
            'cycle',
            'issue',
            'code',
            'coding',
            'version control',
        ],
        categories: [
            'arrows',
            'development',
        ],
    },
    {
        icon: 'RefreshCcw',
        name: 'refresh-ccw',
        tags: [
            'arrows',
            'rotate',
            'reload',
            'rerun',
            'synchronise',
            'synchronize',
            'circular',
            'cycle',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'RefreshCwOff',
        name: 'refresh-cw-off',
        tags: [
            'rotate',
            'reload',
            'rerun',
            'synchronise',
            'synchronize',
            'arrows',
            'circular',
            'cycle',
            'cancel',
            'no',
            'stop',
            'error',
            'disconnect',
            'ignore',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'RefreshCw',
        name: 'refresh-cw',
        tags: [
            'rotate',
            'reload',
            'rerun',
            'synchronise',
            'synchronize',
            'arrows',
            'circular',
            'cycle',
        ],
        categories: [
            'arrows',
        ],
    },
    {
        icon: 'Repeat2',
        name: 'repeat-2',
        tags: [
            'arrows',
            'retweet',
            'repost',
            'share',
            'repeat',
            'loop',
        ],
        categories: [
            'arrows',
            'social',
            'multimedia',
        ],
    },
    {
        icon: 'Repeat',
        name: 'repeat',
        tags: [
            'loop',
            'arrows',
        ],
        categories: [
            'arrows',
            'multimedia',
        ],
    },
    {
        icon: 'Rewind',
        name: 'rewind',
        tags: [
            'music',
        ],
        categories: [
            'arrows',
            'multimedia',
        ],
    },
    {
        icon: 'RotateCcw',
        name: 'rotate-ccw',
        tags: [
            'arrow',
            'left',
            'counter-clockwise',
            'restart',
            'reload',
            'rerun',
            'refresh',
            'backup',
            'undo',
            'replay',
            'redo',
            'retry',
            'rewind',
            'reverse',
        ],
        categories: [
            'arrows',
            'design',
            'photography',
        ],
    },
    {
        icon: 'RotateCw',
        name: 'rotate-cw',
        tags: [
            'arrow',
            'right',
            'clockwise',
            'refresh',
            'reload',
            'rerun',
            'redo',
        ],
        categories: [
            'arrows',
            'design',
            'photography',
        ],
    },
    {
        icon: 'SignpostBig',
        name: 'signpost-big',
        tags: [
            'bidirectional',
            'left',
            'right',
            'east',
            'west',
        ],
        categories: [
            'arrows',
            'navigation',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'Signpost',
        name: 'signpost',
        tags: [
            'bidirectional',
            'left',
            'right',
            'east',
            'west',
        ],
        categories: [
            'arrows',
            'navigation',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'SplinePointer',
        name: 'spline-pointer',
        tags: [
            'path',
            'tool',
            'curve',
            'node',
            'click',
            'pointer',
            'target',
            'vector',
        ],
        categories: [
            'arrows',
            'cursors',
            'design',
            'tools',
        ],
    },
    {
        icon: 'SquareArrowDownLeft',
        name: 'square-arrow-down-left',
        tags: [
            'direction',
            'south-west',
            'diagonal',
            'sign',
            'turn',
            'keyboard',
            'button',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'SquareArrowDownRight',
        name: 'square-arrow-down-right',
        tags: [
            'direction',
            'south-east',
            'diagonal',
            'sign',
            'turn',
            'keyboard',
            'button',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'SquareArrowDown',
        name: 'square-arrow-down',
        tags: [
            'backwards',
            'reverse',
            'direction',
            'south',
            'sign',
            'keyboard',
            'button',
        ],
        categories: [
            'arrows',
            'navigation',
            'gaming',
        ],
    },
    {
        icon: 'SquareArrowLeft',
        name: 'square-arrow-left',
        tags: [
            'previous',
            'back',
            'direction',
            'west',
            'sign',
            'keyboard',
            'button',
            '<-',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'SquareArrowOutDownLeft',
        name: 'square-arrow-out-down-left',
        tags: [
            'outwards',
            'direction',
            'south-west',
            'diagonal',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'SquareArrowOutDownRight',
        name: 'square-arrow-out-down-right',
        tags: [
            'outwards',
            'direction',
            'south-east',
            'diagonal',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'SquareArrowOutUpLeft',
        name: 'square-arrow-out-up-left',
        tags: [
            'outwards',
            'direction',
            'north-west',
            'diagonal',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'SquareArrowOutUpRight',
        name: 'square-arrow-out-up-right',
        tags: [
            'outwards',
            'direction',
            'north-east',
            'diagonal',
            'share',
            'open',
            'external',
            'link',
        ],
        categories: [
            'arrows',
            'navigation',
            'social',
        ],
    },
    {
        icon: 'SquareArrowRight',
        name: 'square-arrow-right',
        tags: [
            'next',
            'forward',
            'direction',
            'west',
            'sign',
            'keyboard',
            'button',
            '->',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'SquareArrowUpLeft',
        name: 'square-arrow-up-left',
        tags: [
            'direction',
            'north-west',
            'diagonal',
            'sign',
            'keyboard',
            'button',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'SquareArrowUpRight',
        name: 'square-arrow-up-right',
        tags: [
            'direction',
            'north-east',
            'diagonal',
            'sign',
            'keyboard',
            'button',
            'share',
        ],
        categories: [
            'arrows',
            'navigation',
            'social',
        ],
    },
    {
        icon: 'SquareArrowUp',
        name: 'square-arrow-up',
        tags: [
            'forward',
            'direction',
            'north',
            'sign',
            'keyboard',
            'button',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'SquareChevronDown',
        name: 'square-chevron-down',
        tags: [
            'back',
            'menu',
            'panel',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'SquareChevronLeft',
        name: 'square-chevron-left',
        tags: [
            'back',
            'previous',
            'less than',
            'fewer',
            'menu',
            'panel',
            'button',
            'keyboard',
            '<',
        ],
        categories: [
            'arrows',
            'navigation',
        ],
    },
    {
        icon: 'SquareChevronRight',
        name: 'square-chevron-right',
        tags: [
            'forward',
            'next',
            'more than',
            'greater',
            'menu',
            'panel',
            'code',
            'coding',
            'command line',
            'terminal',
            'prompt',
            'shell',
            'console',
            '>',
        ],
        categories: [
            'arrows',
            'navigation',
            'development',
        ],
    },
    {
        icon: 'SquareChevronUp',
        name: 'square-chevron-up',
        tags: [
            'caret',
            'keyboard',
            'button',
            'mac',
            'control',
            'ctrl',
            'superscript',
            'exponential',
            'power',
            'ahead',
            'menu',
            'panel',
            '^',
        ],
        categories: [
            'arrows',
            'navigation',
            'math',
        ],
    },
    {
        icon: 'SquareDashedMousePointer',
        name: 'square-dashed-mouse-pointer',
        tags: [
            'inspector',
            'element',
            'mouse',
            'click',
            'pointer',
            'box',
            'browser',
            'selector',
            'target',
            'dom',
            'node',
        ],
        categories: [
            'arrows',
            'cursors',
            'development',
            'tools',
        ],
    },
    {
        icon: 'SquareMousePointer',
        name: 'square-mouse-pointer',
        tags: [
            'inspector',
            'element',
            'mouse',
            'click',
            'pointer',
            'box',
            'browser',
            'selector',
            'target',
            'dom',
            'node',
        ],
        categories: [
            'arrows',
            'cursors',
            'development',
            'tools',
        ],
    },
    {
        icon: 'SquarePlay',
        name: 'square-play',
        tags: [
            'music',
            'audio',
            'video',
            'start',
            'run',
        ],
        categories: [
            'arrows',
            'multimedia',
        ],
    },
    {
        icon: 'Sunrise',
        name: 'sunrise',
        tags: [
            'weather',
            'time',
            'morning',
            'day',
        ],
        categories: [
            'arrows',
            'weather',
            'time',
        ],
    },
    {
        icon: 'Sunset',
        name: 'sunset',
        tags: [
            'weather',
            'time',
            'evening',
            'night',
        ],
        categories: [
            'arrows',
            'weather',
        ],
    },
    {
        icon: 'UnfoldHorizontal',
        name: 'unfold-horizontal',
        tags: [
            'arrow',
            'collapse',
            'fold',
            'vertical',
            'dashed',
        ],
        categories: [
            'arrows',
            'layout',
        ],
    },
    {
        icon: 'UnfoldVertical',
        name: 'unfold-vertical',
        tags: [
            'arrow',
            'expand',
            'vertical',
            'dashed',
        ],
        categories: [
            'arrows',
            'layout',
        ],
    },
    {
        icon: 'Upload',
        name: 'upload',
        tags: [
            'file',
        ],
        categories: [
            'arrows',
            'files',
        ],
    },
];
export default icons;
