// Icons with primary category: buildings
const icons = [
    {
        icon: 'Anvil',
        name: 'anvil',
        tags: [
            'metal',
            'iron',
            'alloy',
            'materials',
            'heavy',
            'weight',
            'blacksmith',
            'forge',
            'acme',
        ],
        categories: [
            'buildings',
            'tools',
            'gaming',
        ],
    },
    {
        icon: 'BrickWall',
        name: 'brick-wall',
        tags: [
            'bricks',
            'mortar',
            'cement',
            'materials',
            'construction',
            'builder',
            'labourer',
            'quantity surveyor',
            'blocks',
            'stone',
        ],
        categories: [
            'buildings',
            'home',
        ],
    },
    {
        icon: 'Castle',
        name: 'castle',
        tags: [
            'fortress',
            'stronghold',
            'palace',
            'chateau',
            'building',
        ],
        categories: [
            'buildings',
            'gaming',
        ],
    },
    {
        icon: 'Church',
        name: 'church',
        tags: [
            'temple',
            'building',
        ],
        categories: [
            'buildings',
            'navigation',
        ],
    },
    {
        icon: 'Dam',
        name: 'dam',
        tags: [
            'electricity',
            'energy',
            'water',
        ],
        categories: [
            'buildings',
            'sustainability',
        ],
    },
    {
        icon: 'Factory',
        name: 'factory',
        tags: [
            'building',
            'business',
            'energy',
            'industry',
            'manufacture',
            'sector',
        ],
        categories: [
            'buildings',
        ],
    },
    {
        icon: 'GraduationCap',
        name: 'graduation-cap',
        tags: [
            'school',
            'university',
            'learn',
            'study',
            'mortarboard',
            'education',
            'ceremony',
            'academic',
            'hat',
            'diploma',
            'bachlor\'s',
            'master\'s',
            'doctorate',
        ],
        categories: [
            'buildings',
        ],
    },
    {
        icon: 'Hotel',
        name: 'hotel',
        tags: [
            'building',
            'hostel',
            'motel',
            'inn',
        ],
        categories: [
            'buildings',
            'navigation',
            'travel',
        ],
    },
    {
        icon: 'HousePlug',
        name: 'house-plug',
        tags: [
            'home',
            'living',
            'building',
            'residence',
            'architecture',
            'autarky',
            'energy',
        ],
        categories: [
            'buildings',
            'home',
            'sustainability',
        ],
    },
    {
        icon: 'HousePlus',
        name: 'house-plus',
        tags: [
            'home',
            'living',
            'medical',
            'new',
            'addition',
            'building',
            'residence',
            'architecture',
        ],
        categories: [
            'buildings',
            'medical',
        ],
    },
    {
        icon: 'House',
        name: 'house',
        tags: [
            'home',
            'living',
            'building',
            'residence',
            'architecture',
        ],
        categories: [
            'buildings',
            'home',
        ],
    },
    {
        icon: 'School',
        name: 'school',
        tags: [
            'building',
            'education',
            'childhood',
            'university',
            'learning',
            'campus',
            'scholar',
            'student',
            'lecture',
            'degree',
            'course',
            'academia',
            'study',
            'knowledge',
            'classroom',
            'research',
            'diploma',
            'graduation',
            'professor',
            'tutorial',
            'homework',
            'assignment',
            'exam',
        ],
        categories: [
            'buildings',
            'navigation',
        ],
    },
    {
        icon: 'Store',
        name: 'store',
        tags: [
            'shop',
            'supermarket',
            'stand',
            'boutique',
            'building',
        ],
        categories: [
            'buildings',
            'navigation',
            'shopping',
        ],
    },
    {
        icon: 'Theater',
        name: 'theater',
        tags: [
            'theater',
            'theatre',
            'entertainment',
            'podium',
            'stage',
            'musical',
        ],
        categories: [
            'buildings',
            'social',
        ],
    },
    {
        icon: 'University',
        name: 'university',
        tags: [
            'building',
            'education',
            'childhood',
            'school',
        ],
        categories: [
            'buildings',
            'navigation',
        ],
    },
    {
        icon: 'UtilityPole',
        name: 'utility-pole',
        tags: [
            'electricity',
            'energy',
            'transmission line',
            'telegraph pole',
            'power lines',
            'phone',
        ],
        categories: [
            'buildings',
            'home',
            'sustainability',
        ],
    },
    {
        icon: 'Warehouse',
        name: 'warehouse',
        tags: [
            'storage',
            'logistics',
            'building',
        ],
        categories: [
            'buildings',
            'navigation',
        ],
    },
];
export default icons;
