// Icons with primary category: charts
const icons = [
    {
        icon: 'ChartArea',
        name: 'chart-area',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
            'area',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartBarBig',
        name: 'chart-bar-big',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartBarDecreasing',
        name: 'chart-bar-decreasing',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
            'trending down',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartBarIncreasing',
        name: 'chart-bar-increasing',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
            'trending up',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartBarStacked',
        name: 'chart-bar-stacked',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
            'multivariate',
            'categorical',
            'comparison',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartBar',
        name: 'chart-bar',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartCandlestick',
        name: 'chart-candlestick',
        tags: [
            'trading',
            'trader',
            'financial',
            'markets',
            'portfolio',
            'assets',
            'prices',
            'value',
            'valuation',
            'commodities',
            'currencies',
            'currency',
            'stocks',
            'exchange',
            'hedge fund',
            'statistics',
            'analytics',
            'diagram',
            'graph',
        ],
        categories: [
            'charts',
            'finance',
        ],
    },
    {
        icon: 'ChartColumnBig',
        name: 'chart-column-big',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartColumnDecreasing',
        name: 'chart-column-decreasing',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
            'trending down',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartColumnIncreasing',
        name: 'chart-column-increasing',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
            'trending up',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartColumnStacked',
        name: 'chart-column-stacked',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
            'multivariate',
            'categorical',
            'comparison',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartColumn',
        name: 'chart-column',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartGantt',
        name: 'chart-gantt',
        tags: [
            'diagram',
            'graph',
            'timeline',
            'planning',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartLine',
        name: 'chart-line',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartNetwork',
        name: 'chart-network',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
            'topology',
            'cluster',
            'web',
            'nodes',
            'connections',
            'edges',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartNoAxesColumnDecreasing',
        name: 'chart-no-axes-column-decreasing',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
            'trending down',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartNoAxesColumnIncreasing',
        name: 'chart-no-axes-column-increasing',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
            'trending up',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartNoAxesColumn',
        name: 'chart-no-axes-column',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartNoAxesCombined',
        name: 'chart-no-axes-combined',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
            'trending up',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartNoAxesGantt',
        name: 'chart-no-axes-gantt',
        tags: [
            'projects',
            'manage',
            'overview',
            'roadmap',
            'plan',
            'intentions',
            'timeline',
            'deadline',
            'date',
            'event',
            'range',
            'period',
            'productivity',
            'work',
            'agile',
            'code',
            'coding',
        ],
        categories: [
            'charts',
            'time',
            'development',
            'design',
        ],
    },
    {
        icon: 'ChartPie',
        name: 'chart-pie',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'presentation',
        ],
        categories: [
            'charts',
            'files',
        ],
    },
    {
        icon: 'ChartScatter',
        name: 'chart-scatter',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'ChartSpline',
        name: 'chart-spline',
        tags: [
            'statistics',
            'analytics',
            'diagram',
            'graph',
            'curve',
            'continuous',
            'smooth',
            'polynomial',
            'quadratic',
            'function',
            'interpolation',
        ],
        categories: [
            'charts',
        ],
    },
    {
        icon: 'FolderKanban',
        name: 'folder-kanban',
        tags: [
            'projects',
            'manage',
            'overview',
            'board',
            'tickets',
            'issues',
            'roadmap',
            'plan',
            'intentions',
            'productivity',
            'work',
            'agile',
            'code',
            'coding',
            'directory',
            'project',
            'root',
        ],
        categories: [
            'charts',
            'development',
            'design',
            'files',
        ],
    },
    {
        icon: 'Kanban',
        name: 'kanban',
        tags: [
            'projects',
            'manage',
            'overview',
            'board',
            'tickets',
            'issues',
            'roadmap',
            'plan',
            'intentions',
            'productivity',
            'work',
            'agile',
            'code',
            'coding',
        ],
        categories: [
            'charts',
            'development',
            'design',
        ],
    },
    {
        icon: 'SquareChartGantt',
        name: 'square-chart-gantt',
        tags: [
            'projects',
            'manage',
            'overview',
            'roadmap',
            'plan',
            'intentions',
            'timeline',
            'deadline',
            'date',
            'event',
            'range',
            'period',
            'productivity',
            'work',
            'agile',
            'code',
            'coding',
            'toolbar',
            'button',
        ],
        categories: [
            'charts',
            'time',
            'development',
            'design',
        ],
    },
    {
        icon: 'SquareDashedKanban',
        name: 'square-dashed-kanban',
        tags: [
            'projects',
            'manage',
            'overview',
            'board',
            'tickets',
            'issues',
            'roadmap',
            'plan',
            'intentions',
            'productivity',
            'work',
            'agile',
            'draft',
            'template',
            'boilerplate',
            'code',
            'coding',
        ],
        categories: [
            'charts',
            'development',
            'design',
        ],
    },
    {
        icon: 'SquareKanban',
        name: 'square-kanban',
        tags: [
            'projects',
            'manage',
            'overview',
            'board',
            'tickets',
            'issues',
            'roadmap',
            'plan',
            'intentions',
            'productivity',
            'work',
            'agile',
            'code',
            'coding',
            'toolbar',
            'button',
        ],
        categories: [
            'charts',
            'development',
            'design',
        ],
    },
    {
        icon: 'TrendingDown',
        name: 'trending-down',
        tags: [
            'statistics',
        ],
        categories: [
            'charts',
            'arrows',
        ],
    },
    {
        icon: 'TrendingUpDown',
        name: 'trending-up-down',
        tags: [
            'arrows',
            'estimated',
            'indeterminate',
            'data fluctuation',
            'uncertain',
            'forecast',
            'variable',
            'prediction',
            'dynamic',
            'volatile',
        ],
        categories: [
            'charts',
            'arrows',
        ],
    },
    {
        icon: 'TrendingUp',
        name: 'trending-up',
        tags: [
            'statistics',
        ],
        categories: [
            'charts',
            'arrows',
        ],
    },
];
export default icons;
