// Icons with primary category: communication
const icons = [
    {
        icon: 'ChevronsLeftRightEllipsis',
        name: 'chevrons-left-right-ellipsis',
        tags: [
            'internet',
            'network',
            'connection',
            'cable',
            'lan',
            'port',
            'router',
            'switch',
            'hub',
            'modem',
            'web',
            'online',
            'networking',
            'communication',
            'socket',
            'plug',
            'slot',
            'controller',
            'connector',
            'interface',
            'console',
            'signal',
            'data',
            'input',
            'output',
        ],
        categories: [
            'communication',
            'devices',
            'multimedia',
            'gaming',
        ],
    },
    {
        icon: 'CircleFadingPlus',
        name: 'circle-fading-plus',
        tags: [
            'stories',
            'social media',
            'instagram',
            'facebook',
            'meta',
            'snapchat',
            'sharing',
            'content',
        ],
        categories: [
            'communication',
            'social',
        ],
    },
    {
        icon: 'EthernetPort',
        name: 'ethernet-port',
        tags: [
            'internet',
            'network',
            'connection',
            'cable',
            'lan',
            'port',
            'router',
            'switch',
            'hub',
            'modem',
            'web',
            'online',
            'networking',
            'communication',
            'socket',
            'plug',
            'slot',
            'controller',
            'connector',
            'interface',
            'console',
            'signal',
            'data',
            'input',
            'output',
        ],
        categories: [
            'communication',
            'devices',
            'multimedia',
            'gaming',
        ],
    },
    {
        icon: 'Lectern',
        name: 'lectern',
        tags: [
            'pulpit',
            'podium',
            'stand',
        ],
        categories: [
            'communication',
            'multimedia',
        ],
    },
    {
        icon: 'Nfc',
        name: 'nfc',
        tags: [
            'contactless',
            'payment',
            'near-field communication',
        ],
        categories: [
            'communication',
            'finance',
            'devices',
        ],
    },
    {
        icon: 'SmartphoneNfc',
        name: 'smartphone-nfc',
        tags: [
            'contactless',
            'payment',
            'near-field communication',
            'screen',
        ],
        categories: [
            'communication',
            'finance',
            'devices',
        ],
    },
    {
        icon: 'SwitchCamera',
        name: 'switch-camera',
        tags: [
            'photo',
            'selfie',
            'front',
            'back',
        ],
        categories: [
            'communication',
            'devices',
        ],
    },
];
export default icons;
