// Icons with primary category: connectivity
const icons = [
    {
        icon: 'BatteryCharging',
        name: 'battery-charging',
        tags: [
            'power',
            'electricity',
            'energy',
            'accumulator',
            'charge',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'BatteryFull',
        name: 'battery-full',
        tags: [
            'power',
            'electricity',
            'energy',
            'accumulator',
            'charge',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'BatteryLow',
        name: 'battery-low',
        tags: [
            'power',
            'electricity',
            'energy',
            'accumulator',
            'charge',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'BatteryMedium',
        name: 'battery-medium',
        tags: [
            'power',
            'electricity',
            'energy',
            'accumulator',
            'charge',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'BatteryWarning',
        name: 'battery-warning',
        tags: [
            'power',
            'electricity',
            'energy',
            'accumulator',
            'charge',
            'exclamation mark',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'Battery',
        name: 'battery',
        tags: [
            'power',
            'electricity',
            'energy',
            'accumulator',
            'charge',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'BluetoothConnected',
        name: 'bluetooth-connected',
        tags: [
            'paired',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'BluetoothOff',
        name: 'bluetooth-off',
        tags: [
            'lost',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'BluetoothSearching',
        name: 'bluetooth-searching',
        tags: [
            'pairing',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'Bluetooth',
        name: 'bluetooth',
        tags: [
            'wireless',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'Cable',
        name: 'cable',
        tags: [
            'cord',
            'wire',
            'connector',
            'connection',
            'link',
            'signal',
            'console',
            'computer',
            'equipment',
            'electricity',
            'energy',
            'electronics',
            'recharging',
            'charger',
            'power',
            'supply',
            'disconnected',
            'unplugged',
            'plugs',
            'interface',
            'input',
            'output',
            'audio video',
            'av',
            'rca',
            'scart',
            'tv',
            'television',
            'optical',
        ],
        categories: [
            'connectivity',
            'devices',
            'multimedia',
        ],
    },
    {
        icon: 'CassetteTape',
        name: 'cassette-tape',
        tags: [
            'audio',
            'music',
            'recording',
            'play',
        ],
        categories: [
            'connectivity',
            'devices',
            'multimedia',
            'communication',
            'files',
        ],
    },
    {
        icon: 'CirclePower',
        name: 'circle-power',
        tags: [
            'on',
            'off',
            'device',
            'switch',
            'toggle',
            'binary',
            'boolean',
            'reboot',
            'restart',
            'button',
            'keyboard',
            'troubleshoot',
        ],
        categories: [
            'connectivity',
        ],
    },
    {
        icon: 'CloudOff',
        name: 'cloud-off',
        tags: [
            'disconnect',
        ],
        categories: [
            'connectivity',
            'weather',
        ],
    },
    {
        icon: 'MonitorCheck',
        name: 'monitor-check',
        tags: [
            'tv',
            'screen',
            'display',
            'desktop',
            'running',
            'active',
            'virtual machine',
            'vm',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'MonitorCog',
        name: 'monitor-cog',
        tags: [
            'tv',
            'screen',
            'display',
            'virtual machine',
            'vm',
            'executable',
            'settings',
            'cog',
            'edit',
            'gear',
            'configuration',
            'preferences',
            'system',
            'control panel',
            'network',
            'computing',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'MonitorDot',
        name: 'monitor-dot',
        tags: [
            'tv',
            'screen',
            'display',
            'desktop',
            'running',
            'active',
            'virtual machine',
            'vm',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'MonitorDown',
        name: 'monitor-down',
        tags: [
            'tv',
            'screen',
            'display',
            'desktop',
            'download',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'MonitorOff',
        name: 'monitor-off',
        tags: [
            'share',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'MonitorPause',
        name: 'monitor-pause',
        tags: [
            'tv',
            'screen',
            'display',
            'desktop',
            'video',
            'movie',
            'film',
            'suspend',
            'hibernate',
            'boot',
            'virtual machine',
            'vm',
        ],
        categories: [
            'connectivity',
            'devices',
            'multimedia',
        ],
    },
    {
        icon: 'MonitorPlay',
        name: 'monitor-play',
        tags: [
            'tv',
            'screen',
            'display',
            'desktop',
            'video',
            'movie',
            'film',
            'running',
            'start',
            'boot',
            'virtual machine',
            'vm',
        ],
        categories: [
            'connectivity',
            'devices',
            'multimedia',
        ],
    },
    {
        icon: 'MonitorSmartphone',
        name: 'monitor-smartphone',
        tags: [
            'smartphone',
            'phone',
            'cellphone',
            'device',
            'mobile',
            'desktop',
            'monitor',
            'responsive',
            'screens',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'MonitorSpeaker',
        name: 'monitor-speaker',
        tags: [
            'devices',
            'connect',
            'cast',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'MonitorStop',
        name: 'monitor-stop',
        tags: [
            'tv',
            'screen',
            'display',
            'desktop',
            'video',
            'movie',
            'film',
            'stop',
            'shutdown',
            'virtual machine',
            'vm',
        ],
        categories: [
            'connectivity',
            'devices',
            'multimedia',
        ],
    },
    {
        icon: 'MonitorUp',
        name: 'monitor-up',
        tags: [
            'tv',
            'screen',
            'display',
            'upload',
            'connect',
            'remote',
            'screen share',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'MonitorX',
        name: 'monitor-x',
        tags: [
            'tv',
            'screen',
            'display',
            'desktop',
            'virtual machine',
            'vm',
            'close',
            'stop',
            'suspend',
            'remove',
            'delete',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'Monitor',
        name: 'monitor',
        tags: [
            'tv',
            'screen',
            'display',
            'virtual machine',
            'vm',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'PhoneCall',
        name: 'phone-call',
        tags: [
            'ring',
        ],
        categories: [
            'connectivity',
            'devices',
            'communication',
        ],
    },
    {
        icon: 'PhoneMissed',
        name: 'phone-missed',
        tags: [
            'call',
        ],
        categories: [
            'connectivity',
            'devices',
            'communication',
        ],
    },
    {
        icon: 'PhoneOff',
        name: 'phone-off',
        tags: [
            'call',
            'mute',
        ],
        categories: [
            'connectivity',
            'devices',
            'communication',
        ],
    },
    {
        icon: 'PowerOff',
        name: 'power-off',
        tags: [
            'on',
            'off',
            'device',
            'switch',
        ],
        categories: [
            'connectivity',
        ],
    },
    {
        icon: 'Power',
        name: 'power',
        tags: [
            'on',
            'off',
            'device',
            'switch',
            'toggle',
            'binary',
            'boolean',
            'reboot',
            'restart',
            'button',
            'keyboard',
            'troubleshoot',
        ],
        categories: [
            'connectivity',
        ],
    },
    {
        icon: 'SatelliteDish',
        name: 'satellite-dish',
        tags: [
            'antenna',
            'receiver',
            'dish aerial',
            'saucer',
        ],
        categories: [
            'connectivity',
            'devices',
            'multimedia',
        ],
    },
    {
        icon: 'Satellite',
        name: 'satellite',
        tags: [
            'space station',
            'orbit',
            'transmitter',
        ],
        categories: [
            'connectivity',
            'science',
        ],
    },
    {
        icon: 'ScreenShareOff',
        name: 'screen-share-off',
        tags: [
            'desktop',
            'disconnect',
            'monitor',
        ],
        categories: [
            'connectivity',
            'devices',
            'communication',
        ],
    },
    {
        icon: 'ScreenShare',
        name: 'screen-share',
        tags: [
            'host',
            'desktop',
            'monitor',
        ],
        categories: [
            'connectivity',
            'devices',
            'communication',
        ],
    },
    {
        icon: 'SignalHigh',
        name: 'signal-high',
        tags: [
            'connection',
            'wireless',
            'gsm',
            'phone',
            '2g',
            '3g',
            '4g',
            '5g',
        ],
        categories: [
            'connectivity',
        ],
    },
    {
        icon: 'SignalLow',
        name: 'signal-low',
        tags: [
            'connection',
            'wireless',
            'gsm',
            'phone',
            '2g',
            '3g',
            '4g',
            '5g',
        ],
        categories: [
            'connectivity',
        ],
    },
    {
        icon: 'SignalMedium',
        name: 'signal-medium',
        tags: [
            'connection',
            'wireless',
            'gsm',
            'phone',
            '2g',
            '3g',
            '4g',
            '5g',
        ],
        categories: [
            'connectivity',
        ],
    },
    {
        icon: 'SignalZero',
        name: 'signal-zero',
        tags: [
            'connection',
            'wireless',
            'gsm',
            'phone',
            '2g',
            '3g',
            '4g',
            '5g',
            'lost',
        ],
        categories: [
            'connectivity',
        ],
    },
    {
        icon: 'Signal',
        name: 'signal',
        tags: [
            'connection',
            'wireless',
            'gsm',
            'phone',
            '2g',
            '3g',
            '4g',
            '5g',
        ],
        categories: [
            'connectivity',
        ],
    },
    {
        icon: 'SmartphoneCharging',
        name: 'smartphone-charging',
        tags: [
            'phone',
            'cellphone',
            'device',
            'power',
            'screen',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'Smartphone',
        name: 'smartphone',
        tags: [
            'phone',
            'cellphone',
            'device',
            'screen',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'SquarePower',
        name: 'square-power',
        tags: [
            'on',
            'off',
            'device',
            'switch',
            'toggle',
            'binary',
            'boolean',
            'reboot',
            'restart',
            'button',
            'keyboard',
            'troubleshoot',
        ],
        categories: [
            'connectivity',
        ],
    },
    {
        icon: 'Voicemail',
        name: 'voicemail',
        tags: [
            'phone',
            'cassette',
            'tape',
            'reel',
            'recording',
            'audio',
        ],
        categories: [
            'connectivity',
            'devices',
            'social',
        ],
    },
    {
        icon: 'Volume1',
        name: 'volume-1',
        tags: [
            'music',
            'sound',
            'speaker',
        ],
        categories: [
            'connectivity',
            'communication',
            'multimedia',
        ],
    },
    {
        icon: 'Volume2',
        name: 'volume-2',
        tags: [
            'music',
            'sound',
            'speaker',
        ],
        categories: [
            'connectivity',
            'communication',
            'multimedia',
        ],
    },
    {
        icon: 'VolumeOff',
        name: 'volume-off',
        tags: [
            'music',
            'sound',
            'mute',
            'speaker',
        ],
        categories: [
            'connectivity',
            'communication',
            'multimedia',
        ],
    },
    {
        icon: 'VolumeX',
        name: 'volume-x',
        tags: [
            'music',
            'sound',
            'mute',
            'speaker',
        ],
        categories: [
            'connectivity',
            'communication',
            'multimedia',
        ],
    },
    {
        icon: 'Volume',
        name: 'volume',
        tags: [
            'music',
            'sound',
            'mute',
            'speaker',
        ],
        categories: [
            'connectivity',
            'communication',
            'multimedia',
        ],
    },
    {
        icon: 'Webcam',
        name: 'webcam',
        tags: [
            'camera',
            'security',
        ],
        categories: [
            'connectivity',
            'devices',
            'communication',
        ],
    },
    {
        icon: 'WifiHigh',
        name: 'wifi-high',
        tags: [
            'connection',
            'signal',
            'wireless',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'WifiLow',
        name: 'wifi-low',
        tags: [
            'connection',
            'signal',
            'wireless',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'WifiOff',
        name: 'wifi-off',
        tags: [
            'disabled',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'WifiPen',
        name: 'wifi-pen',
        tags: [
            'edit',
            'wifi',
            'pen',
            'change',
            'network',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'WifiZero',
        name: 'wifi-zero',
        tags: [
            'connection',
            'signal',
            'wireless',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'Wifi',
        name: 'wifi',
        tags: [
            'connection',
            'signal',
            'wireless',
        ],
        categories: [
            'connectivity',
            'devices',
        ],
    },
    {
        icon: 'ZapOff',
        name: 'zap-off',
        tags: [
            'flash',
            'camera',
            'lightning',
            'electricity',
            'energy',
        ],
        categories: [
            'connectivity',
            'devices',
            'photography',
            'weather',
        ],
    },
    {
        icon: 'Zap',
        name: 'zap',
        tags: [
            'flash',
            'camera',
            'lightning',
            'electricity',
            'energy',
        ],
        categories: [
            'connectivity',
            'devices',
            'photography',
            'weather',
        ],
    },
];
export default icons;
