// Icons with primary category: design
const icons = [
    {
        icon: 'Axis3d',
        name: 'axis-3d',
        tags: [
            'gizmo',
            'coordinates',
        ],
        categories: [
            'design',
        ],
    },
    {
        icon: 'Blend',
        name: 'blend',
        tags: [
            'mode',
            'overlay',
            'multiply',
            'screen',
            'opacity',
            'transparency',
            'alpha',
            'filters',
            'lenses',
            'mixed',
            'shades',
            'tints',
            'hues',
            'saturation',
            'brightness',
            'overlap',
            'colors',
            'colours',
        ],
        categories: [
            'design',
            'photography',
            'tools',
            'development',
        ],
    },
    {
        icon: 'BringToFront',
        name: 'bring-to-front',
        tags: [
            'bring',
            'send',
            'move',
            'over',
            'forward',
            'front',
            'overlap',
            'layer',
            'order',
        ],
        categories: [
            'design',
            'layout',
        ],
    },
    {
        icon: 'Component',
        name: 'component',
        tags: [
            'design',
            'element',
            'group',
            'module',
            'part',
            'symbol',
        ],
        categories: [
            'design',
            'development',
        ],
    },
    {
        icon: 'DecimalsArrowLeft',
        name: 'decimals-arrow-left',
        tags: [
            'numerical',
            'decimal',
            'decrease',
            'less',
            'fewer',
            'precision',
            'rounding',
            'digits',
            'fraction',
            'float',
            'number',
        ],
        categories: [
            'design',
            'text',
            'arrows',
            'math',
        ],
    },
    {
        icon: 'DecimalsArrowRight',
        name: 'decimals-arrow-right',
        tags: [
            'numerical',
            'decimal',
            'increase',
            'more',
            'precision',
            'rounding',
            'digits',
            'fraction',
            'float',
            'number',
        ],
        categories: [
            'design',
            'text',
            'arrows',
            'math',
        ],
    },
    {
        icon: 'FileAxis3d',
        name: 'file-axis-3d',
        tags: [
            'model',
            '3d',
            'axis',
            'coordinates',
        ],
        categories: [
            'design',
            'files',
        ],
    },
    {
        icon: 'FlipHorizontal2',
        name: 'flip-horizontal-2',
        tags: [
            'reflect',
            'mirror',
            'alignment',
            'dashed',
        ],
        categories: [
            'design',
            'photography',
        ],
    },
    {
        icon: 'FlipHorizontal',
        name: 'flip-horizontal',
        tags: [
            'reflect',
            'mirror',
            'alignment',
            'dashed',
        ],
        categories: [
            'design',
            'photography',
        ],
    },
    {
        icon: 'FlipVertical2',
        name: 'flip-vertical-2',
        tags: [
            'reflect',
            'mirror',
            'alignment',
            'dashed',
        ],
        categories: [
            'design',
            'photography',
        ],
    },
    {
        icon: 'FlipVertical',
        name: 'flip-vertical',
        tags: [
            'reflect',
            'mirror',
            'alignment',
            'dashed',
        ],
        categories: [
            'design',
            'photography',
        ],
    },
    {
        icon: 'Frame',
        name: 'frame',
        tags: [
            'logo',
            'design',
            'tool',
        ],
        categories: [
            'design',
            'photography',
        ],
    },
    {
        icon: 'LandPlot',
        name: 'land-plot',
        tags: [
            'area',
            'surface',
            'square metres',
            'allotment',
            'parcel',
            'property',
            'plane',
            'acres',
            'measure',
            'distance',
            'isometric',
            'flag',
            'golf course',
            'hole',
        ],
        categories: [
            'design',
            'tools',
            'math',
            'sports',
            'gaming',
        ],
    },
    {
        icon: 'Lasso',
        name: 'lasso',
        tags: [
            'select',
            'cursor',
        ],
        categories: [
            'design',
            'cursors',
        ],
    },
    {
        icon: 'Layers2',
        name: 'layers-2',
        tags: [
            'stack',
            'pile',
            'pages',
            'sheets',
            'paperwork',
            'copies',
            'copy',
            'duplicate',
            'double',
            'shortcuts',
        ],
        categories: [
            'design',
            'layout',
        ],
    },
    {
        icon: 'Layers',
        name: 'layers',
        tags: [
            'stack',
            'pile',
            'pages',
            'sheets',
            'paperwork',
            'copies',
            'copy',
        ],
        categories: [
            'design',
            'layout',
        ],
    },
    {
        icon: 'LayoutDashboard',
        name: 'layout-dashboard',
        tags: [
            'masonry',
            'brick',
        ],
        categories: [
            'design',
            'layout',
        ],
    },
    {
        icon: 'LayoutGrid',
        name: 'layout-grid',
        tags: [
            'app',
            'home',
            'start',
        ],
        categories: [
            'design',
            'layout',
        ],
    },
    {
        icon: 'LayoutList',
        name: 'layout-list',
        tags: [
            'todo',
            'tasks',
            'items',
            'pending',
            'image',
            'photo',
        ],
        categories: [
            'design',
            'layout',
            'photography',
            'text',
        ],
    },
    {
        icon: 'LayoutPanelLeft',
        name: 'layout-panel-left',
        tags: [
            'app',
            'home',
            'start',
            'grid',
        ],
        categories: [
            'design',
            'layout',
        ],
    },
    {
        icon: 'Magnet',
        name: 'magnet',
        tags: [
            'horseshoe',
            'lock',
            'science',
            'snap',
        ],
        categories: [
            'design',
        ],
    },
    {
        icon: 'Move3d',
        name: 'move-3d',
        tags: [
            'arrows',
            'axis',
            'gizmo',
            'coordinates',
            'transform',
            'translate',
        ],
        categories: [
            'design',
        ],
    },
    {
        icon: 'PaintBucket',
        name: 'paint-bucket',
        tags: [
            'fill',
            'paint',
            'bucket',
            'color',
            'colour',
        ],
        categories: [
            'design',
            'tools',
        ],
    },
    {
        icon: 'PencilOff',
        name: 'pencil-off',
        tags: [
            'disabled',
            'inactive',
            'non-editable',
            'locked',
            'read-only',
            'unmodifiable',
            'frozen',
            'restricted',
            'rubber',
            'edit',
            'create',
            'draw',
            'sketch',
            'draft',
            'writer',
            'writing',
            'stationery',
            'artist',
        ],
        categories: [
            'design',
            'cursors',
            'tools',
            'text',
        ],
    },
    {
        icon: 'Pencil',
        name: 'pencil',
        tags: [
            'rubber',
            'edit',
            'create',
            'draw',
            'sketch',
            'draft',
            'writer',
            'writing',
            'stationery',
            'artist',
        ],
        categories: [
            'design',
            'cursors',
            'tools',
            'text',
        ],
    },
    {
        icon: 'Rotate3d',
        name: 'rotate-3d',
        tags: [
            'gizmo',
            'transform',
            'orientation',
            'orbit',
            'axis',
        ],
        categories: [
            'design',
        ],
    },
    {
        icon: 'Scale3d',
        name: 'scale-3d',
        tags: [
            'gizmo',
            'transform',
            'size',
            'axis',
        ],
        categories: [
            'design',
        ],
    },
    {
        icon: 'Scaling',
        name: 'scaling',
        tags: [
            'scale',
            'resize',
            'design',
        ],
        categories: [
            'design',
        ],
    },
    {
        icon: 'ScissorsLineDashed',
        name: 'scissors-line-dashed',
        tags: [
            'cut here',
            'along',
            'snip',
            'chop',
            'stationery',
            'crafts',
            'instructions',
            'diagram',
        ],
        categories: [
            'design',
            'tools',
        ],
    },
    {
        icon: 'SendToBack',
        name: 'send-to-back',
        tags: [
            'bring',
            'send',
            'move',
            'under',
            'back',
            'backwards',
            'overlap',
            'layer',
            'order',
        ],
        categories: [
            'design',
            'layout',
        ],
    },
    {
        icon: 'Slice',
        name: 'slice',
        tags: [
            'cutter',
            'scalpel',
            'knife',
        ],
        categories: [
            'design',
        ],
    },
    {
        icon: 'Spline',
        name: 'spline',
        tags: [
            'path',
            'pen',
            'tool',
            'shape',
            'curve',
            'draw',
        ],
        categories: [
            'design',
        ],
    },
    {
        icon: 'SprayCan',
        name: 'spray-can',
        tags: [
            'paint',
            'color',
            'graffiti',
            'decoration',
            'aerosol',
            'deodorant',
            'shaving foam',
            'air freshener',
        ],
        categories: [
            'design',
            'tools',
        ],
    },
    {
        icon: 'SquareRoundCorner',
        name: 'square-round-corner',
        tags: [
            'border',
            'radius',
            'style',
            'design',
            'corner',
            'layout',
            'round',
            'rounded',
        ],
        categories: [
            'design',
            'development',
            'layout',
        ],
    },
    {
        icon: 'SquaresExclude',
        name: 'squares-exclude',
        tags: [
            'sqaure',
            'pathfinder',
            'path',
            'exclude',
            'invert',
            'xor',
            'shape',
            'vector',
        ],
        categories: [
            'design',
        ],
    },
    {
        icon: 'SquaresIntersect',
        name: 'squares-intersect',
        tags: [
            'sqaure',
            'pathfinder',
            'path',
            'intersect',
            'shape',
            'include',
            'vector',
        ],
        categories: [
            'design',
        ],
    },
    {
        icon: 'SquaresSubtract',
        name: 'squares-subtract',
        tags: [
            'sqaure',
            'pathfinder',
            'path',
            'minus',
            'subtract',
            'subtraction',
            'shape',
            'front',
            'vector',
        ],
        categories: [
            'design',
        ],
    },
    {
        icon: 'SquaresUnite',
        name: 'squares-unite',
        tags: [
            'sqaure',
            'pathfinder',
            'path',
            'unite',
            'union',
            'shape',
            'merge',
            'vector',
        ],
        categories: [
            'design',
        ],
    },
    {
        icon: 'Stamp',
        name: 'stamp',
        tags: [
            'mark',
            'print',
            'clone',
            'loyalty',
            'library',
        ],
        categories: [
            'design',
            'cursors',
            'tools',
        ],
    },
    {
        icon: 'SwatchBook',
        name: 'swatch-book',
        tags: [
            'colors',
            'colours',
            'swatches',
            'pantone',
            'shades',
            'tint',
            'hue',
            'saturation',
            'brightness',
            'theme',
            'scheme',
            'palette',
            'samples',
            'textile',
            'carpet',
        ],
        categories: [
            'design',
            'home',
            'photography',
        ],
    },
    {
        icon: 'View',
        name: 'view',
        tags: [
            'eye',
            'look',
        ],
        categories: [
            'design',
            'photography',
        ],
    },
    {
        icon: 'WandSparkles',
        name: 'wand-sparkles',
        tags: [
            'magic',
            'wizard',
            'magician',
        ],
        categories: [
            'design',
            'gaming',
            'cursors',
            'photography',
        ],
    },
    {
        icon: 'Wand',
        name: 'wand',
        tags: [
            'magic',
            'selection',
        ],
        categories: [
            'design',
            'gaming',
            'cursors',
            'photography',
        ],
    },
];
export default icons;
