// Icons with primary category: development
const icons = [
    {
        icon: 'Blocks',
        name: 'blocks',
        tags: [
            'addon',
            'plugin',
            'integration',
            'extension',
            'package',
            'build',
            'stack',
            'toys',
            'kids',
            'children',
            'learning',
        ],
        categories: [
            'development',
            'shapes',
        ],
    },
    {
        icon: 'BookCopy',
        name: 'book-copy',
        tags: [
            'code',
            'coding',
            'version control',
            'git',
            'repository',
            'clone',
            'fork',
            'duplicate',
            'multiple',
            'books',
            'library',
            'copies',
            'copied',
            'plagiarism',
            'plagiarised',
            'plagiarized',
            'reading list',
            'information',
            'informed',
            'knowledge',
            'knowledgeable',
            'knowledgable',
            'education',
            'high school',
            'university',
            'college',
            'academy',
            'student',
            'study',
            'learning',
            'research',
            'smart',
            'intelligent',
            'intellectual',
        ],
        categories: [
            'development',
            'text',
            'gaming',
        ],
    },
    {
        icon: 'BookDashed',
        name: 'book-dashed',
        tags: [
            'code',
            'coding',
            'version control',
            'git',
            'repository',
            'template',
            'draft',
            'script',
            'screenplay',
            'writing',
            'writer',
            'author',
            'unwritten',
            'unpublished',
            'untold',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'BookDown',
        name: 'book-down',
        tags: [
            'code',
            'coding',
            'version control',
            'git',
            'repository',
            'pull',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'BookKey',
        name: 'book-key',
        tags: [
            'code',
            'coding',
            'version control',
            'git',
            'repository',
            'private',
            'public',
            'secret',
            'unlocked',
            'hidden',
            'revealed',
            'knowledge',
            'learning',
        ],
        categories: [
            'development',
            'security',
            'gaming',
        ],
    },
    {
        icon: 'BookLock',
        name: 'book-lock',
        tags: [
            'code',
            'coding',
            'version control',
            'git',
            'repository',
            'private',
            'secret',
            'hidden',
            'knowledge',
        ],
        categories: [
            'development',
            'security',
            'gaming',
        ],
    },
    {
        icon: 'BookMinus',
        name: 'book-minus',
        tags: [
            'code',
            'coding',
            'version control',
            'git',
            'repository',
            'remove',
            'delete',
            'censor',
            'cancel',
            'forbid',
            'prohibit',
            'ban',
            'uneducated',
            're-educate',
            'unlearn',
            'downgrade',
        ],
        categories: [
            'development',
            'text',
            'gaming',
        ],
    },
    {
        icon: 'BookPlus',
        name: 'book-plus',
        tags: [
            'code',
            'coding',
            'version control',
            'git',
            'repository',
            'remove',
            'delete',
            'read',
            'write',
            'author',
            'publish',
            'inform',
            'graduate',
            're-educate',
            'study',
            'learn',
            'research',
            'knowledge',
            'improve',
            'upgrade',
            'level up',
        ],
        categories: [
            'development',
            'text',
            'gaming',
        ],
    },
    {
        icon: 'BookUp2',
        name: 'book-up-2',
        tags: [
            'code',
            'coding',
            'version control',
            'git',
            'repository',
            'push',
            'force',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'BookUp',
        name: 'book-up',
        tags: [
            'code',
            'coding',
            'version control',
            'git',
            'repository',
            'push',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'BotMessageSquare',
        name: 'bot-message-square',
        tags: [
            'robot',
            'ai',
            'chat',
            'assistant',
        ],
        categories: [
            'development',
            'social',
        ],
    },
    {
        icon: 'BotOff',
        name: 'bot-off',
        tags: [
            'robot',
            'ai',
            'chat',
            'assistant',
        ],
        categories: [
            'development',
            'social',
        ],
    },
    {
        icon: 'Bot',
        name: 'bot',
        tags: [
            'robot',
            'ai',
            'chat',
            'assistant',
        ],
        categories: [
            'development',
            'social',
        ],
    },
    {
        icon: 'Braces',
        name: 'braces',
        tags: [
            'json',
            'code',
            'token',
            'curly brackets',
            'data',
            '{',
            '}',
        ],
        categories: [
            'development',
            'files',
        ],
    },
    {
        icon: 'Brackets',
        name: 'brackets',
        tags: [
            'code',
            'token',
            'array',
            'list',
            'square',
            '[',
            ']',
        ],
        categories: [
            'development',
            'files',
        ],
    },
    {
        icon: 'BugOff',
        name: 'bug-off',
        tags: [
            'debug',
            'code',
            'insect',
            'kill',
            'exterminate',
            'pest control',
        ],
        categories: [
            'development',
            'animals',
        ],
    },
    {
        icon: 'BugPlay',
        name: 'bug-play',
        tags: [
            'debug',
            'code',
            'insect',
        ],
        categories: [
            'development',
            'animals',
        ],
    },
    {
        icon: 'Bug',
        name: 'bug',
        tags: [
            'issue',
            'report',
            'debug',
            'code',
            'insect',
        ],
        categories: [
            'development',
            'animals',
        ],
    },
    {
        icon: 'CircleDashed',
        name: 'circle-dashed',
        tags: [
            'pending',
            'dot',
            'progress',
            'issue',
            'draft',
            'code',
            'coding',
            'version control',
        ],
        categories: [
            'development',
            'shapes',
        ],
    },
    {
        icon: 'CircleDotDashed',
        name: 'circle-dot-dashed',
        tags: [
            'pending',
            'dot',
            'progress',
            'issue',
            'draft',
            'code',
            'coding',
            'version control',
        ],
        categories: [
            'development',
            'shapes',
        ],
    },
    {
        icon: 'CircleDot',
        name: 'circle-dot',
        tags: [
            'pending',
            'dot',
            'progress',
            'issue',
            'code',
            'coding',
            'version control',
            'choices',
            'multiple choice',
            'choose',
        ],
        categories: [
            'development',
            'shapes',
        ],
    },
    {
        icon: 'CircleSlash',
        name: 'circle-slash',
        tags: [
            'diameter',
            'zero',
            'Ø',
            'nothing',
            'null',
            'void',
            'cancel',
            'ban',
            'no',
            'stop',
            'forbidden',
            'prohibited',
            'error',
            'incorrect',
            'mistake',
            'wrong',
            'failure',
            'divide',
            'division',
            'or',
            '/',
        ],
        categories: [
            'development',
            'math',
        ],
    },
    {
        icon: 'CloudAlert',
        name: 'cloud-alert',
        tags: [
            'weather',
            'danger',
            'warning',
            'alert',
            'error',
            'sync',
            'network',
            'exclamation',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'CloudCog',
        name: 'cloud-cog',
        tags: [
            'computing',
            'ai',
            'cluster',
            'network',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'Combine',
        name: 'combine',
        tags: [
            'cubes',
            'packages',
            'parts',
            'units',
            'collection',
            'cluster',
            'combine',
            'gather',
            'merge',
        ],
        categories: [
            'development',
            'files',
        ],
    },
    {
        icon: 'Command',
        name: 'command',
        tags: [
            'keyboard',
            'key',
            'mac',
            'cmd',
            'button',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'Construction',
        name: 'construction',
        tags: [
            'roadwork',
            'maintenance',
            'blockade',
            'barricade',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'Container',
        name: 'container',
        tags: [
            'storage',
            'shipping',
            'freight',
            'supply chain',
            'docker',
            'environment',
            'devops',
            'code',
            'coding',
        ],
        categories: [
            'development',
            'transportation',
            'mail',
        ],
    },
    {
        icon: 'Diff',
        name: 'diff',
        tags: [
            'patch',
            'difference',
            'compare',
            'plus',
            'minus',
            'plus-minus',
            'math',
        ],
        categories: [
            'development',
            'files',
        ],
    },
    {
        icon: 'FlagTriangleLeft',
        name: 'flag-triangle-left',
        tags: [
            'report',
            'timeline',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'FlagTriangleRight',
        name: 'flag-triangle-right',
        tags: [
            'report',
            'timeline',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'GitBranchPlus',
        name: 'git-branch-plus',
        tags: [
            'add',
            'create',
            '+',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'GitBranch',
        name: 'git-branch',
        tags: [
            'code',
            'version control',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'GitCommitHorizontal',
        name: 'git-commit-horizontal',
        tags: [
            'code',
            'version control',
            'waypoint',
            'stop',
            'station',
        ],
        categories: [
            'development',
            'navigation',
        ],
    },
    {
        icon: 'GitCommitVertical',
        name: 'git-commit-vertical',
        tags: [
            'code',
            'version control',
            'waypoint',
            'stop',
            'station',
        ],
        categories: [
            'development',
            'navigation',
        ],
    },
    {
        icon: 'GitCompareArrows',
        name: 'git-compare-arrows',
        tags: [
            'code',
            'version control',
            'diff',
        ],
        categories: [
            'development',
            'arrows',
        ],
    },
    {
        icon: 'GitCompare',
        name: 'git-compare',
        tags: [
            'code',
            'version control',
            'diff',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'GitFork',
        name: 'git-fork',
        tags: [
            'code',
            'version control',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'GitGraph',
        name: 'git-graph',
        tags: [
            'code',
            'version control',
            'commit graph',
            'commits',
            'gitlens',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'GitMerge',
        name: 'git-merge',
        tags: [
            'code',
            'version control',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'GitPullRequestArrow',
        name: 'git-pull-request-arrow',
        tags: [
            'code',
            'version control',
            'open',
        ],
        categories: [
            'development',
            'arrows',
        ],
    },
    {
        icon: 'GitPullRequestClosed',
        name: 'git-pull-request-closed',
        tags: [
            'code',
            'version control',
            'rejected',
            'closed',
            'cancelled',
            'x',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'GitPullRequestCreateArrow',
        name: 'git-pull-request-create-arrow',
        tags: [
            'code',
            'version control',
            'open',
            'plus',
            'add',
            '+',
        ],
        categories: [
            'development',
            'arrows',
        ],
    },
    {
        icon: 'GitPullRequestCreate',
        name: 'git-pull-request-create',
        tags: [
            'code',
            'version control',
            'open',
            'plus',
            'add',
            '+',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'GitPullRequestDraft',
        name: 'git-pull-request-draft',
        tags: [
            'code',
            'version control',
            'open',
            'draft',
            'dashed',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'GitPullRequest',
        name: 'git-pull-request',
        tags: [
            'code',
            'version control',
            'open',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'HardDriveDownload',
        name: 'hard-drive-download',
        tags: [
            'computer',
            'server',
            'memory',
            'data',
            'ssd',
            'disk',
            'hard disk',
            'save',
        ],
        categories: [
            'development',
            'devices',
            'arrows',
            'files',
        ],
    },
    {
        icon: 'HardDriveUpload',
        name: 'hard-drive-upload',
        tags: [
            'computer',
            'server',
            'memory',
            'data',
            'ssd',
            'disk',
            'hard disk',
            'save',
        ],
        categories: [
            'development',
            'devices',
            'arrows',
            'files',
        ],
    },
    {
        icon: 'HardDrive',
        name: 'hard-drive',
        tags: [
            'computer',
            'server',
            'memory',
            'data',
            'ssd',
            'disk',
            'hard disk',
        ],
        categories: [
            'development',
            'devices',
        ],
    },
    {
        icon: 'Merge',
        name: 'merge',
        tags: [
            'combine',
            'join',
            'unite',
        ],
        categories: [
            'development',
            'arrows',
        ],
    },
    {
        icon: 'MessageCircleCode',
        name: 'message-circle-code',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'code review',
            'coding',
        ],
        categories: [
            'development',
            'social',
        ],
    },
    {
        icon: 'MessageSquareCode',
        name: 'message-square-code',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'code review',
            'coding',
        ],
        categories: [
            'development',
            'social',
        ],
    },
    {
        icon: 'MessageSquareDiff',
        name: 'message-square-diff',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'add',
            'patch',
            'difference',
            'plus',
            'minus',
            'plus-minus',
            'math',
            'code review',
            'coding',
            'version control',
            'git',
        ],
        categories: [
            'development',
            'files',
            'social',
        ],
    },
    {
        icon: 'Network',
        name: 'network',
        tags: [
            'tree',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'Option',
        name: 'option',
        tags: [
            'keyboard',
            'key',
            'mac',
            'alt',
            'button',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'PackageCheck',
        name: 'package-check',
        tags: [
            'confirm',
            'verified',
            'done',
            'todo',
            'tick',
            'complete',
            'task',
            'delivered',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'PackageMinus',
        name: 'package-minus',
        tags: [
            'delete',
            'remove',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'PackagePlus',
        name: 'package-plus',
        tags: [
            'new',
            'add',
            'create',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'PackageX',
        name: 'package-x',
        tags: [
            'delete',
            'remove',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'Parentheses',
        name: 'parentheses',
        tags: [
            'code',
            'token',
            'parenthesis',
            'parens',
            'brackets',
            'parameters',
            'arguments',
            'args',
            'input',
            'call',
            'math',
            'formula',
            'function',
            '(',
            ')',
        ],
        categories: [
            'development',
            'files',
            'math',
        ],
    },
    {
        icon: 'Pi',
        name: 'pi',
        tags: [
            'constant',
            'code',
            'coding',
            'programming',
            'symbol',
            'trigonometry',
            'geometry',
            'formula',
        ],
        categories: [
            'development',
            'math',
        ],
    },
    {
        icon: 'Puzzle',
        name: 'puzzle',
        tags: [
            'component',
            'module',
            'part',
            'piece',
        ],
        categories: [
            'development',
            'gaming',
        ],
    },
    {
        icon: 'QrCode',
        name: 'qr-code',
        tags: [
            'barcode',
            'scan',
            'link',
            'url',
            'information',
            'digital',
        ],
        categories: [
            'development',
            'social',
        ],
    },
    {
        icon: 'Radical',
        name: 'radical',
        tags: [
            'calculate',
            'formula',
            'math',
            'operator',
            'root',
            'square',
            'symbol',
        ],
        categories: [
            'development',
            'math',
        ],
    },
    {
        icon: 'Router',
        name: 'router',
        tags: [
            'computer',
            'server',
            'cloud',
        ],
        categories: [
            'development',
            'devices',
            'connectivity',
            'home',
        ],
    },
    {
        icon: 'Rss',
        name: 'rss',
        tags: [
            'feed',
            'subscribe',
            'news',
            'updates',
            'notifications',
            'content',
            'blog',
            'articles',
            'broadcast',
            'syndication',
            'reader',
            'channels',
            'posts',
            'publishing',
            'digest',
            'alert',
            'following',
            'inbox',
            'newsletter',
            'weblog',
            'podcast',
        ],
        categories: [
            'development',
            'social',
        ],
    },
    {
        icon: 'ServerCog',
        name: 'server-cog',
        tags: [
            'cloud',
            'storage',
            'computing',
            'cog',
            'gear',
        ],
        categories: [
            'development',
            'devices',
        ],
    },
    {
        icon: 'ServerCrash',
        name: 'server-crash',
        tags: [
            'cloud',
            'storage',
            'problem',
            'error',
        ],
        categories: [
            'development',
            'devices',
        ],
    },
    {
        icon: 'ServerOff',
        name: 'server-off',
        tags: [
            'cloud',
            'storage',
        ],
        categories: [
            'development',
            'devices',
        ],
    },
    {
        icon: 'Server',
        name: 'server',
        tags: [
            'cloud',
            'storage',
        ],
        categories: [
            'development',
            'devices',
        ],
    },
    {
        icon: 'Slash',
        name: 'slash',
        tags: [
            'divide',
            'division',
            'or',
            '/',
        ],
        categories: [
            'development',
            'math',
        ],
    },
    {
        icon: 'Split',
        name: 'split',
        tags: [
            'break',
            'disband',
            'divide',
            'separate',
            'branch',
            'disunite',
        ],
        categories: [
            'development',
            'arrows',
        ],
    },
    {
        icon: 'SquareDashedBottomCode',
        name: 'square-dashed-bottom-code',
        tags: [
            'rectangle',
            'aspect ratio',
            '1:1',
            'shape',
            'snippet',
            'code',
            'coding',
        ],
        categories: [
            'development',
            'files',
        ],
    },
    {
        icon: 'SquareDashedBottom',
        name: 'square-dashed-bottom',
        tags: [
            'rectangle',
            'aspect ratio',
            '1:1',
            'shape',
            'snippet',
            'code',
            'coding',
        ],
        categories: [
            'development',
            'files',
        ],
    },
    {
        icon: 'SquareDot',
        name: 'square-dot',
        tags: [
            'git',
            'diff',
            'modified',
            '.',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'SquareFunction',
        name: 'square-function',
        tags: [
            'programming',
            'code',
            'automation',
            'math',
        ],
        categories: [
            'development',
            'math',
        ],
    },
    {
        icon: 'SquarePi',
        name: 'square-pi',
        tags: [
            'constant',
            'code',
            'coding',
            'programming',
            'symbol',
            'trigonometry',
            'geometry',
            'formula',
        ],
        categories: [
            'development',
            'math',
        ],
    },
    {
        icon: 'SquareRadical',
        name: 'square-radical',
        tags: [
            'calculate',
            'formula',
            'math',
            'operator',
            'root',
            'square',
            'symbol',
        ],
        categories: [
            'development',
            'math',
        ],
    },
    {
        icon: 'SquareSlash',
        name: 'square-slash',
        tags: [
            'git',
            'diff',
            'ignored',
            'divide',
            'division',
            'shortcut',
            'or',
            '/',
        ],
        categories: [
            'development',
            'math',
        ],
    },
    {
        icon: 'SquareTerminal',
        name: 'square-terminal',
        tags: [
            'code',
            'command line',
            'prompt',
            'shell',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'Terminal',
        name: 'terminal',
        tags: [
            'code',
            'command line',
            'prompt',
            'shell',
        ],
        categories: [
            'development',
        ],
    },
    {
        icon: 'Variable',
        name: 'variable',
        tags: [
            'code',
            'coding',
            'programming',
            'symbol',
            'calculate',
            'algebra',
            'x',
            'parentheses',
            'parenthesis',
            'brackets',
            'parameter',
            '(',
            ')',
        ],
        categories: [
            'development',
            'math',
        ],
    },
    {
        icon: 'WebhookOff',
        name: 'webhook-off',
        tags: [
            'push api',
            'interface',
            'callback',
        ],
        categories: [
            'development',
            'social',
            'account',
        ],
    },
    {
        icon: 'Webhook',
        name: 'webhook',
        tags: [
            'push api',
            'interface',
            'callback',
        ],
        categories: [
            'development',
            'social',
            'account',
        ],
    },
    {
        icon: 'Workflow',
        name: 'workflow',
        tags: [
            'action',
            'continuous integration',
            'ci',
            'automation',
            'devops',
            'network',
            'node',
            'connection',
        ],
        categories: [
            'development',
        ],
    },
];
export default icons;
