// Icons with primary category: devices
const icons = [
    {
        icon: 'AlarmClockCheck',
        name: 'alarm-clock-check',
        tags: [
            'done',
            'todo',
            'tick',
            'complete',
            'task',
        ],
        categories: [
            'devices',
            'notifications',
            'time',
        ],
    },
    {
        icon: 'AlarmClockMinus',
        name: 'alarm-clock-minus',
        tags: [
            'remove',
        ],
        categories: [
            'devices',
            'notifications',
            'time',
        ],
    },
    {
        icon: 'AlarmClockOff',
        name: 'alarm-clock-off',
        tags: [
            'morning',
            'turn-off',
        ],
        categories: [
            'devices',
            'notifications',
            'time',
        ],
    },
    {
        icon: 'AlarmClockPlus',
        name: 'alarm-clock-plus',
        tags: [
            'add',
        ],
        categories: [
            'devices',
            'notifications',
            'time',
        ],
    },
    {
        icon: 'AlarmClock',
        name: 'alarm-clock',
        tags: [
            'morning',
        ],
        categories: [
            'devices',
            'notifications',
            'time',
        ],
    },
    {
        icon: 'Antenna',
        name: 'antenna',
        tags: [
            'signal',
            'connection',
            'connectivity',
            'tv',
            'television',
            'broadcast',
            'live',
            'frequency',
            'tune',
            'scan',
            'channels',
            'aerial',
            'receiver',
            'transmission',
            'transducer',
            'terrestrial',
            'satellite',
            'cable',
        ],
        categories: [
            'devices',
            'multimedia',
            'communication',
        ],
    },
    {
        icon: 'BatteryPlus',
        name: 'battery-plus',
        tags: [
            'power',
            'electricity',
            'energy',
            'accumulator',
            'charge',
            'plus',
            'economy',
            'health',
            'add',
            'new',
            'maximum',
            'upgrade',
            'extra',
            '+',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'BellElectric',
        name: 'bell-electric',
        tags: [
            'fire alarm',
            'flames',
            'smoke',
            'firefighter',
            'fireman',
            'department',
            'brigade',
            'station',
            'emergency',
            'alert',
            'safety',
            'school bell',
            'period break',
            'recess',
            'doorbell',
            'entrance',
            'entry',
            'ring',
            'reception',
        ],
        categories: [
            'devices',
            'notifications',
            'home',
        ],
    },
    {
        icon: 'BoomBox',
        name: 'boom-box',
        tags: [
            'radio',
            'speakers',
            'audio',
            'music',
            'sound',
            'broadcast',
            'live',
            'frequency',
        ],
        categories: [
            'devices',
            'multimedia',
            'social',
        ],
    },
    {
        icon: 'Cast',
        name: 'cast',
        tags: [
            'chromecast',
            'airplay',
            'screen',
        ],
        categories: [
            'devices',
            'connectivity',
        ],
    },
    {
        icon: 'Computer',
        name: 'computer',
        tags: [
            'pc',
            'chassis',
            'codespaces',
            'github',
        ],
        categories: [
            'devices',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'Cpu',
        name: 'cpu',
        tags: [
            'processor',
            'cores',
            'technology',
            'computer',
            'chip',
            'circuit',
            'memory',
            'ram',
            'specs',
            'gigahertz',
            'ghz',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'DatabaseBackup',
        name: 'database-backup',
        tags: [
            'storage',
            'memory',
            'bytes',
            'servers',
            'backup',
            'timemachine',
            'rotate',
            'arrow',
            'left',
        ],
        categories: [
            'devices',
            'arrows',
            'design',
            'development',
            'photography',
        ],
    },
    {
        icon: 'DatabaseZap',
        name: 'database-zap',
        tags: [
            'cache busting',
            'storage',
            'memory',
            'bytes',
            'servers',
            'power',
            'crash',
        ],
        categories: [
            'devices',
            'development',
        ],
    },
    {
        icon: 'Database',
        name: 'database',
        tags: [
            'storage',
            'memory',
            'container',
            'tin',
            'pot',
            'bytes',
            'servers',
        ],
        categories: [
            'devices',
            'development',
        ],
    },
    {
        icon: 'Disc2',
        name: 'disc-2',
        tags: [
            'album',
            'music',
            'vinyl',
            'record',
            'cd',
            'dvd',
            'format',
            'dj',
            'spin',
            'rotate',
            'rpm',
        ],
        categories: [
            'devices',
            'multimedia',
        ],
    },
    {
        icon: 'Disc3',
        name: 'disc-3',
        tags: [
            'album',
            'music',
            'vinyl',
            'record',
            'cd',
            'dvd',
            'format',
            'dj',
            'spin',
            'rotate',
            'rpm',
        ],
        categories: [
            'devices',
            'multimedia',
        ],
    },
    {
        icon: 'DiscAlbum',
        name: 'disc-album',
        tags: [
            'album',
            'music',
            'songs',
            'format',
            'cd',
            'dvd',
            'vinyl',
            'sleeve',
            'cover',
            'platinum',
            'compilation',
            'ep',
            'recording',
            'playback',
            'spin',
            'rotate',
            'rpm',
            'dj',
        ],
        categories: [
            'devices',
            'multimedia',
        ],
    },
    {
        icon: 'Disc',
        name: 'disc',
        tags: [
            'album',
            'music',
            'songs',
            'format',
            'cd',
            'dvd',
            'vinyl',
            'sleeve',
            'cover',
            'platinum',
            'compilation',
            'ep',
            'recording',
            'playback',
            'spin',
            'rotate',
            'rpm',
            'dj',
        ],
        categories: [
            'devices',
            'multimedia',
        ],
    },
    {
        icon: 'Gpu',
        name: 'gpu',
        tags: [
            'processor',
            'cores',
            'technology',
            'computer',
            'chip',
            'circuit',
            'specs',
            'graphics processing unit',
            'video card',
            'display adapter',
            'gddr',
            'rendering',
            'digital image processing',
            'crypto mining',
        ],
        categories: [
            'devices',
            'gaming',
        ],
    },
    {
        icon: 'HdmiPort',
        name: 'hdmi-port',
        tags: [
            'socket',
            'plug',
            'slot',
            'controller',
            'connector',
            'interface',
            'console',
            'signal',
            'audio',
            'video',
            'visual',
            'av',
            'data',
            'input',
            'output',
        ],
        categories: [
            'devices',
            'multimedia',
            'gaming',
        ],
    },
    {
        icon: 'KeyboardOff',
        name: 'keyboard-off',
        tags: [
            'unkeys',
            'layout',
            'spell',
            'settings',
            'mouse',
        ],
        categories: [
            'devices',
            'text',
            'development',
        ],
    },
    {
        icon: 'LaptopMinimalCheck',
        name: 'laptop-minimal-check',
        tags: [
            'computer',
            'screen',
            'remote',
            'success',
            'done',
            'todo',
            'tick',
            'complete',
            'task',
        ],
        categories: [
            'devices',
            'notifications',
        ],
    },
    {
        icon: 'LaptopMinimal',
        name: 'laptop-minimal',
        tags: [
            'computer',
            'screen',
            'remote',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'Laptop',
        name: 'laptop',
        tags: [
            'computer',
            'screen',
            'remote',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'MemoryStick',
        name: 'memory-stick',
        tags: [
            'ram',
            'random access',
            'technology',
            'computer',
            'chip',
            'circuit',
            'specs',
            'capacity',
            'gigabytes',
            'gb',
        ],
        categories: [
            'devices',
            'gaming',
        ],
    },
    {
        icon: 'MicOff',
        name: 'mic-off',
        tags: [
            'record',
            'sound',
            'mute',
            'microphone',
        ],
        categories: [
            'devices',
            'communication',
            'connectivity',
            'multimedia',
        ],
    },
    {
        icon: 'MicVocal',
        name: 'mic-vocal',
        tags: [
            'lyrics',
            'voice',
            'listen',
            'sound',
            'music',
            'radio',
            'podcast',
            'karaoke',
            'singing',
            'microphone',
        ],
        categories: [
            'devices',
            'multimedia',
        ],
    },
    {
        icon: 'Mic',
        name: 'mic',
        tags: [
            'record',
            'sound',
            'listen',
            'radio',
            'podcast',
            'microphone',
        ],
        categories: [
            'devices',
            'communication',
            'connectivity',
            'multimedia',
        ],
    },
    {
        icon: 'Microchip',
        name: 'microchip',
        tags: [
            'processor',
            'cores',
            'technology',
            'computer',
            'chip',
            'integrated circuit',
            'memory',
            'ram',
            'specs',
            'gpu',
            'gigahertz',
            'ghz',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'MouseOff',
        name: 'mouse-off',
        tags: [
            'device',
            'scroll',
            'click',
            'disabled',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'Mouse',
        name: 'mouse',
        tags: [
            'device',
            'scroll',
            'click',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'PcCase',
        name: 'pc-case',
        tags: [
            'computer',
            'chassis',
        ],
        categories: [
            'devices',
            'gaming',
        ],
    },
    {
        icon: 'Plug2',
        name: 'plug-2',
        tags: [
            'electricity',
            'energy',
            'socket',
            'outlet',
        ],
        categories: [
            'devices',
            'development',
        ],
    },
    {
        icon: 'PlugZap',
        name: 'plug-zap',
        tags: [
            'electricity',
            'energy',
            'electronics',
            'charge',
            'charging',
            'battery',
            'connect',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'Plug',
        name: 'plug',
        tags: [
            'electricity',
            'energy',
            'electronics',
            'socket',
            'outlet',
        ],
        categories: [
            'devices',
            'development',
        ],
    },
    {
        icon: 'PrinterCheck',
        name: 'printer-check',
        tags: [
            'fax',
            'office',
            'device',
            'success',
            'printed',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'Printer',
        name: 'printer',
        tags: [
            'fax',
            'office',
            'device',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'RadioReceiver',
        name: 'radio-receiver',
        tags: [
            'device',
            'music',
            'connect',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'RadioTower',
        name: 'radio-tower',
        tags: [
            'signal',
            'broadcast',
            'connectivity',
            'live',
            'frequency',
        ],
        categories: [
            'devices',
            'multimedia',
            'social',
        ],
    },
    {
        icon: 'Radio',
        name: 'radio',
        tags: [
            'signal',
            'broadcast',
            'connectivity',
            'live',
            'frequency',
        ],
        categories: [
            'devices',
            'multimedia',
            'social',
        ],
    },
    {
        icon: 'RectangleGoggles',
        name: 'rectangle-goggles',
        tags: [
            'vr',
            'virtual',
            'augmented',
            'reality',
            'headset',
            'goggles',
        ],
        categories: [
            'devices',
            'gaming',
            'multimedia',
            'connectivity',
        ],
    },
    {
        icon: 'ScanLine',
        name: 'scan-line',
        tags: [
            'checkout',
            'till',
            'cart',
            'transaction',
            'purchase',
            'buy',
            'product',
            'packaging',
            'retail',
            'consumer',
            'qr-code',
            'dashed',
        ],
        categories: [
            'devices',
            'shopping',
        ],
    },
    {
        icon: 'Scan',
        name: 'scan',
        tags: [
            'qr-code',
            'barcode',
            'checkout',
            'augmented reality',
            'ar',
            'target',
            'surveillance',
            'camera',
            'lens',
            'focus',
            'frame',
            'select',
            'box',
            'boundary',
            'bounds',
            'area',
            'square',
            'dashed',
        ],
        categories: [
            'devices',
            'shopping',
            'security',
            'social',
            'gaming',
        ],
    },
    {
        icon: 'TabletSmartphone',
        name: 'tablet-smartphone',
        tags: [
            'responsive',
            'screens',
            'browser',
            'testing',
            'mobile',
        ],
        categories: [
            'devices',
            'design',
            'development',
            'tools',
        ],
    },
    {
        icon: 'Tablet',
        name: 'tablet',
        tags: [
            'device',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'Toilet',
        name: 'toilet',
        tags: [
            'toilet',
            'potty',
            'bathroom',
            'washroom',
        ],
        categories: [
            'devices',
            'home',
        ],
    },
    {
        icon: 'TouchpadOff',
        name: 'touchpad-off',
        tags: [
            'trackpad',
            'cursor',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'Touchpad',
        name: 'touchpad',
        tags: [
            'trackpad',
            'cursor',
        ],
        categories: [
            'devices',
        ],
    },
    {
        icon: 'TvMinimalPlay',
        name: 'tv-minimal-play',
        tags: [
            'flatscreen',
            'television',
            'stream',
            'display',
            'widescreen',
            'high-definition',
            'hd',
            '1080p',
            '4k',
            '8k',
            'smart',
            'digital',
            'video',
            'movie',
            'live',
            'ott',
            'running',
            'start',
            'film',
            'home cinema',
            'entertainment',
            'showtime',
            'channels',
            'catchup',
        ],
        categories: [
            'devices',
            'multimedia',
        ],
    },
    {
        icon: 'TvMinimal',
        name: 'tv-minimal',
        tags: [
            'flatscreen',
            'television',
            'stream',
            'display',
            'widescreen',
            'high-definition',
            'hd',
            '1080p',
            '4k',
            '8k',
            'smart',
            'digital',
            'video',
            'home cinema',
            'entertainment',
            'showtime',
            'channels',
            'catchup',
        ],
        categories: [
            'devices',
            'multimedia',
        ],
    },
    {
        icon: 'Tv',
        name: 'tv',
        tags: [
            'television',
            'stream',
            'display',
            'widescreen',
            'high-definition',
            'hd',
            '1080p',
            '4k',
            '8k',
            'smart',
            'digital',
            'video',
            'entertainment',
            'showtime',
            'channels',
            'terrestrial',
            'satellite',
            'cable',
            'broadcast',
            'live',
            'frequency',
            'tune',
            'scan',
            'aerial',
            'receiver',
            'transmission',
            'signal',
            'connection',
            'connectivity',
        ],
        categories: [
            'devices',
            'multimedia',
            'communication',
        ],
    },
    {
        icon: 'Unplug',
        name: 'unplug',
        tags: [
            'electricity',
            'energy',
            'electronics',
            'socket',
            'outlet',
            'disconnect',
        ],
        categories: [
            'devices',
            'development',
        ],
    },
    {
        icon: 'Usb',
        name: 'usb',
        tags: [
            'universal',
            'serial',
            'bus',
            'controller',
            'connector',
            'interface',
        ],
        categories: [
            'devices',
            'multimedia',
            'home',
        ],
    },
    {
        icon: 'VibrateOff',
        name: 'vibrate-off',
        tags: [
            'smartphone',
            'notification',
            'rumble',
            'haptic feedback',
            'notifications',
            'screen',
        ],
        categories: [
            'devices',
            'connectivity',
            'account',
        ],
    },
    {
        icon: 'Vibrate',
        name: 'vibrate',
        tags: [
            'smartphone',
            'notification',
            'rumble',
            'haptic feedback',
            'screen',
        ],
        categories: [
            'devices',
            'connectivity',
            'account',
            'notifications',
        ],
    },
    {
        icon: 'VideoOff',
        name: 'video-off',
        tags: [
            'camera',
            'movie',
            'film',
        ],
        categories: [
            'devices',
            'communication',
            'connectivity',
            'photography',
        ],
    },
    {
        icon: 'Video',
        name: 'video',
        tags: [
            'camera',
            'movie',
            'film',
            'recording',
            'motion picture',
            'camcorder',
            'reel',
        ],
        categories: [
            'devices',
            'communication',
            'connectivity',
            'photography',
        ],
    },
    {
        icon: 'Videotape',
        name: 'videotape',
        tags: [
            'vhs',
            'movie',
            'film',
            'recording',
            'motion picture',
            'showreel',
            'cassette',
        ],
        categories: [
            'devices',
            'communication',
            'connectivity',
            'photography',
            'files',
        ],
    },
];
export default icons;
