// Icons with primary category: finance
const icons = [
    {
        icon: 'BanknoteArrowDown',
        name: 'banknote-arrow-down',
        tags: [
            'bill',
            'currency',
            'money',
            'payment',
            'funds',
            'transaction',
            'cash',
            'finance',
            'withdraw',
            'expense',
            'out',
            'payout',
            'refund',
            'debit',
            'spending',
            'decrease',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'BanknoteArrowUp',
        name: 'banknote-arrow-up',
        tags: [
            'bill',
            'currency',
            'money',
            'payment',
            'funds',
            'transaction',
            'cash',
            'finance',
            'deposit',
            'earnings',
            'income',
            'in',
            'credit',
            'prepaid',
            'growth',
            'increase',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'BanknoteX',
        name: 'banknote-x',
        tags: [
            'bill',
            'currency',
            'money',
            'payment',
            'funds',
            'transaction',
            'cash',
            'finance',
            'error',
            'failed',
            'rejected',
            'canceled',
            'declined',
            'lost',
            'delete',
            'remove',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'Banknote',
        name: 'banknote',
        tags: [
            'currency',
            'money',
            'payment',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'CircleDollarSign',
        name: 'circle-dollar-sign',
        tags: [
            'monetization',
            'marketing',
            'currency',
            'money',
            'payment',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'Currency',
        name: 'currency',
        tags: [
            'finance',
            'money',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'DollarSign',
        name: 'dollar-sign',
        tags: [
            'currency',
            'money',
            'payment',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'Euro',
        name: 'euro',
        tags: [
            'currency',
            'money',
            'payment',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'HandCoins',
        name: 'hand-coins',
        tags: [
            'savings',
            'banking',
            'money',
            'finance',
            'offers',
            'mortgage',
            'payment',
            'received',
            'wage',
            'payroll',
            'allowance',
            'pocket money',
            'handout',
            'pennies',
        ],
        categories: [
            'finance',
            'account',
        ],
    },
    {
        icon: 'IndianRupee',
        name: 'indian-rupee',
        tags: [
            'currency',
            'money',
            'payment',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'JapaneseYen',
        name: 'japanese-yen',
        tags: [
            'currency',
            'money',
            'payment',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'Landmark',
        name: 'landmark',
        tags: [
            'bank',
            'building',
            'capitol',
            'finance',
            'money',
            'government',
            'institution',
        ],
        categories: [
            'finance',
            'navigation',
            'buildings',
        ],
    },
    {
        icon: 'PhilippinePeso',
        name: 'philippine-peso',
        tags: [
            'currency',
            'peso',
            'money',
            'php',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'PiggyBank',
        name: 'piggy-bank',
        tags: [
            'money',
            'savings',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'PoundSterling',
        name: 'pound-sterling',
        tags: [
            'currency',
            'money',
            'payment',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'ReceiptCent',
        name: 'receipt-cent',
        tags: [
            'bill',
            'voucher',
            'slip',
            'check',
            'counterfoil',
            'currency',
            'cents',
            'dollar',
            'usd',
            '$',
            '¢',
        ],
        categories: [
            'finance',
            'travel',
        ],
    },
    {
        icon: 'ReceiptEuro',
        name: 'receipt-euro',
        tags: [
            'bill',
            'voucher',
            'slip',
            'check',
            'counterfoil',
            'currency',
            '€',
        ],
        categories: [
            'finance',
            'travel',
        ],
    },
    {
        icon: 'ReceiptIndianRupee',
        name: 'receipt-indian-rupee',
        tags: [
            'bill',
            'voucher',
            'slip',
            'check',
            'counterfoil',
            'currency',
            'inr',
            '₹',
        ],
        categories: [
            'finance',
            'travel',
        ],
    },
    {
        icon: 'ReceiptJapaneseYen',
        name: 'receipt-japanese-yen',
        tags: [
            'bill',
            'voucher',
            'slip',
            'check',
            'counterfoil',
            'currency',
            'jpy',
            '¥',
        ],
        categories: [
            'finance',
            'travel',
        ],
    },
    {
        icon: 'ReceiptPoundSterling',
        name: 'receipt-pound-sterling',
        tags: [
            'bill',
            'voucher',
            'slip',
            'check',
            'counterfoil',
            'british',
            'currency',
            'gbp',
            '£',
        ],
        categories: [
            'finance',
            'travel',
        ],
    },
    {
        icon: 'ReceiptRussianRuble',
        name: 'receipt-russian-ruble',
        tags: [
            'bill',
            'voucher',
            'slip',
            'check',
            'counterfoil',
            'currency',
            'rub',
            '₽',
        ],
        categories: [
            'finance',
            'travel',
        ],
    },
    {
        icon: 'ReceiptSwissFranc',
        name: 'receipt-swiss-franc',
        tags: [
            'bill',
            'voucher',
            'slip',
            'check',
            'counterfoil',
            'currency',
            'chf',
            '₣',
        ],
        categories: [
            'finance',
            'travel',
        ],
    },
    {
        icon: 'ReceiptText',
        name: 'receipt-text',
        tags: [
            'bill',
            'voucher',
            'slip',
            'check',
            'counterfoil',
            'details',
            'small print',
            'terms',
            'conditions',
            'contract',
        ],
        categories: [
            'finance',
            'travel',
        ],
    },
    {
        icon: 'Receipt',
        name: 'receipt',
        tags: [
            'bill',
            'voucher',
            'slip',
            'check',
            'counterfoil',
            'currency',
            'dollar',
            'usd',
            '$',
        ],
        categories: [
            'finance',
            'travel',
        ],
    },
    {
        icon: 'RussianRuble',
        name: 'russian-ruble',
        tags: [
            'currency',
            'money',
            'payment',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'SaudiRiyal',
        name: 'saudi-riyal',
        tags: [
            'currency',
            'money',
            'payment',
        ],
        categories: [
            'finance',
        ],
    },
    {
        icon: 'SwissFranc',
        name: 'swiss-franc',
        tags: [
            'currency',
            'money',
            'payment',
        ],
        categories: [
            'finance',
        ],
    },
];
export default icons;
