// Icons with primary category: home
const icons = [
    {
        icon: 'AirVent',
        name: 'air-vent',
        tags: [
            'air conditioner',
            'ac',
            'central air',
            'cooling',
            'climate-control',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'AlarmSmoke',
        name: 'alarm-smoke',
        tags: [
            'fire',
            'alert',
            'warning',
            'detector',
            'carbon monoxide',
            'safety',
            'equipment',
            'amenities',
        ],
        categories: [
            'home',
            'devices',
            'travel',
        ],
    },
    {
        icon: 'Armchair',
        name: 'armchair',
        tags: [
            'sofa',
            'furniture',
            'leisure',
            'lounge',
            'loveseat',
            'couch',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'BedDouble',
        name: 'bed-double',
        tags: [
            'sleep',
            'hotel',
            'furniture',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'BedSingle',
        name: 'bed-single',
        tags: [
            'sleep',
            'hotel',
            'furniture',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'Bed',
        name: 'bed',
        tags: [
            'sleep',
            'hotel',
            'furniture',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'Blinds',
        name: 'blinds',
        tags: [
            'shades',
            'screen',
            'curtain',
            'shutter',
            'roller blind',
            'window',
            'lighting',
            'household',
            'home',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'BrushCleaning',
        name: 'brush-cleaning',
        tags: [
            'cleaning',
            'utensil',
            'housekeeping',
            'tool',
            'sweeping',
            'scrubbing',
            'hygiene',
            'maintenance',
            'household',
            'cleaner',
            'chores',
            'equipment',
            'sanitation',
            'bristles',
            'handle',
            'home care',
            'sanitize',
            'purify',
            'wash',
            'disinfect',
            'sterilize',
            'scrub',
            'polish',
            'decontaminate',
            'wipe',
            'spotless',
            'remove',
            'empty',
            'erase',
            'purge',
            'eliminate',
        ],
        categories: [
            'home',
            'tools',
            'design',
        ],
    },
    {
        icon: 'DoorClosedLocked',
        name: 'door-closed-locked',
        tags: [
            'entrance',
            'entry',
            'exit',
            'ingress',
            'egress',
            'gate',
            'gateway',
            'emergency exit',
            'lock',
        ],
        categories: [
            'home',
            'travel',
            'security',
        ],
    },
    {
        icon: 'DoorClosed',
        name: 'door-closed',
        tags: [
            'entrance',
            'entry',
            'exit',
            'ingress',
            'egress',
            'gate',
            'gateway',
            'emergency exit',
        ],
        categories: [
            'home',
            'travel',
            'security',
        ],
    },
    {
        icon: 'DoorOpen',
        name: 'door-open',
        tags: [
            'entrance',
            'entry',
            'exit',
            'ingress',
            'egress',
            'gate',
            'gateway',
            'emergency exit',
        ],
        categories: [
            'home',
            'travel',
            'security',
        ],
    },
    {
        icon: 'Fan',
        name: 'fan',
        tags: [
            'air',
            'cooler',
            'ventilation',
            'ventilator',
            'blower',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'Fence',
        name: 'fence',
        tags: [
            'picket',
            'panels',
            'woodwork',
            'diy',
            'materials',
            'suburban',
            'garden',
            'property',
            'territory',
        ],
        categories: [
            'home',
            'buildings',
        ],
    },
    {
        icon: 'FireExtinguisher',
        name: 'fire-extinguisher',
        tags: [
            'flames',
            'smoke',
            'foam',
            'water',
            'spray',
            'hose',
            'firefighter',
            'fireman',
            'department',
            'brigade',
            'station',
            'emergency',
            'suppress',
            'compressed',
            'tank',
            'cylinder',
            'safety',
            'equipment',
            'amenities',
        ],
        categories: [
            'home',
            'tools',
            'travel',
        ],
    },
    {
        icon: 'Heater',
        name: 'heater',
        tags: [
            'heating',
            'warmth',
            'comfort',
            'fire',
            'stove',
            'electric',
            'electronics',
            'amenities',
        ],
        categories: [
            'home',
            'devices',
            'travel',
        ],
    },
    {
        icon: 'HouseWifi',
        name: 'house-wifi',
        tags: [
            'home',
            'living',
            'building',
            'wifi',
            'connectivity',
        ],
        categories: [
            'home',
            'buildings',
            'connectivity',
        ],
    },
    {
        icon: 'LampCeiling',
        name: 'lamp-ceiling',
        tags: [
            'lighting',
            'household',
            'home',
            'furniture',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'LampDesk',
        name: 'lamp-desk',
        tags: [
            'lighting',
            'household',
            'office',
            'desk',
            'home',
            'furniture',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'LampFloor',
        name: 'lamp-floor',
        tags: [
            'lighting',
            'household',
            'floor',
            'home',
            'furniture',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'LampWallDown',
        name: 'lamp-wall-down',
        tags: [
            'lighting',
            'household',
            'wall',
            'home',
            'furniture',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'LampWallUp',
        name: 'lamp-wall-up',
        tags: [
            'lighting',
            'household',
            'wall',
            'home',
            'furniture',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'Lamp',
        name: 'lamp',
        tags: [
            'lighting',
            'household',
            'home',
            'furniture',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'RockingChair',
        name: 'rocking-chair',
        tags: [
            'chair',
            'furniture',
            'seat',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'ShowerHead',
        name: 'shower-head',
        tags: [
            'shower',
            'bath',
            'bathroom',
            'amenities',
            'services',
        ],
        categories: [
            'home',
            'travel',
        ],
    },
    {
        icon: 'SoapDispenserDroplet',
        name: 'soap-dispenser-droplet',
        tags: [
            'wash',
            'baht',
            'water',
            'liquid',
            'fluid',
            'wet',
            'moisture',
            'damp',
            'bead',
            'globule',
        ],
        categories: [
            'home',
            'travel',
        ],
    },
    {
        icon: 'Sofa',
        name: 'sofa',
        tags: [
            'armchair',
            'furniture',
            'leisure',
            'lounge',
            'loveseat',
            'couch',
        ],
        categories: [
            'home',
        ],
    },
    {
        icon: 'WashingMachine',
        name: 'washing-machine',
        tags: [
            'tumble dryer',
            'amenities',
            'electronics',
            'cycle',
            'clothes',
            'rinse',
            'spin',
            'drum',
        ],
        categories: [
            'home',
            'devices',
            'travel',
        ],
    },
];
export default icons;
