// Icons with primary category: layout
const icons = [
    {
        icon: 'AlignCenterHorizontal',
        name: 'align-center-horizontal',
        tags: [
            'items',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignCenterVertical',
        name: 'align-center-vertical',
        tags: [
            'items',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignEndHorizontal',
        name: 'align-end-horizontal',
        tags: [
            'items',
            'bottom',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignEndVertical',
        name: 'align-end-vertical',
        tags: [
            'items',
            'right',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignHorizontalDistributeCenter',
        name: 'align-horizontal-distribute-center',
        tags: [
            'items',
            'flex',
            'justify',
            'space',
            'evenly',
            'around',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignHorizontalDistributeEnd',
        name: 'align-horizontal-distribute-end',
        tags: [
            'right',
            'items',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignHorizontalDistributeStart',
        name: 'align-horizontal-distribute-start',
        tags: [
            'left',
            'items',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignHorizontalJustifyCenter',
        name: 'align-horizontal-justify-center',
        tags: [
            'center',
            'items',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignHorizontalJustifyEnd',
        name: 'align-horizontal-justify-end',
        tags: [
            'right',
            'items',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignHorizontalJustifyStart',
        name: 'align-horizontal-justify-start',
        tags: [
            'left',
            'items',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignHorizontalSpaceAround',
        name: 'align-horizontal-space-around',
        tags: [
            'center',
            'items',
            'flex',
            'justify',
            'distribute',
            'between',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignHorizontalSpaceBetween',
        name: 'align-horizontal-space-between',
        tags: [
            'around',
            'items',
            'bottom',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignStartHorizontal',
        name: 'align-start-horizontal',
        tags: [
            'top',
            'items',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignStartVertical',
        name: 'align-start-vertical',
        tags: [
            'left',
            'items',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignVerticalDistributeCenter',
        name: 'align-vertical-distribute-center',
        tags: [
            'items',
            'flex',
            'justify',
            'space',
            'evenly',
            'around',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignVerticalDistributeEnd',
        name: 'align-vertical-distribute-end',
        tags: [
            'bottom',
            'items',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignVerticalDistributeStart',
        name: 'align-vertical-distribute-start',
        tags: [
            'top',
            'items',
            'flex',
            'justify',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignVerticalJustifyCenter',
        name: 'align-vertical-justify-center',
        tags: [
            'center',
            'items',
            'flex',
            'justify',
            'distribute',
            'between',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignVerticalJustifyEnd',
        name: 'align-vertical-justify-end',
        tags: [
            'bottom',
            'items',
            'flex',
            'justify',
            'distribute',
            'between',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignVerticalJustifyStart',
        name: 'align-vertical-justify-start',
        tags: [
            'top',
            'items',
            'flex',
            'justify',
            'distribute',
            'between',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignVerticalSpaceAround',
        name: 'align-vertical-space-around',
        tags: [
            'center',
            'items',
            'flex',
            'justify',
            'distribute',
            'between',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AlignVerticalSpaceBetween',
        name: 'align-vertical-space-between',
        tags: [
            'center',
            'items',
            'flex',
            'justify',
            'distribute',
            'between',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'AppWindowMac',
        name: 'app-window-mac',
        tags: [
            'application',
            'menu bar',
            'pane',
            'preferences',
            'macos',
            'osx',
            'executable',
        ],
        categories: [
            'layout',
            'design',
            'development',
            'files',
        ],
    },
    {
        icon: 'AppWindow',
        name: 'app-window',
        tags: [
            'application',
            'menu bar',
            'pane',
            'executable',
        ],
        categories: [
            'layout',
            'design',
            'development',
            'files',
        ],
    },
    {
        icon: 'BetweenHorizontalEnd',
        name: 'between-horizontal-end',
        tags: [
            'insert',
            'add',
            'left',
            'slot',
            'squeeze',
            'space',
            'vertical',
            'grid',
            'table',
            'rows',
            'cells',
            'excel',
            'spreadsheet',
            'accountancy',
            'data',
            'enter',
            'entry',
            'entries',
            'blocks',
            'rectangles',
            'chevron',
        ],
        categories: [
            'layout',
            'design',
            'tools',
        ],
    },
    {
        icon: 'BetweenHorizontalStart',
        name: 'between-horizontal-start',
        tags: [
            'insert',
            'add',
            'right',
            'slot',
            'squeeze',
            'space',
            'vertical',
            'grid',
            'table',
            'rows',
            'cells',
            'excel',
            'spreadsheet',
            'accountancy',
            'data',
            'enter',
            'entry',
            'entries',
            'blocks',
            'rectangles',
            'chevron',
        ],
        categories: [
            'layout',
            'design',
            'tools',
        ],
    },
    {
        icon: 'BetweenVerticalEnd',
        name: 'between-vertical-end',
        tags: [
            'insert',
            'add',
            'top',
            'slot',
            'squeeze',
            'space',
            'vertical',
            'grid',
            'table',
            'columns',
            'cells',
            'data',
            'enter',
            'entry',
            'entries',
            'blocks',
            'rectangles',
            'chevron',
        ],
        categories: [
            'layout',
            'design',
            'tools',
        ],
    },
    {
        icon: 'BetweenVerticalStart',
        name: 'between-vertical-start',
        tags: [
            'insert',
            'add',
            'bottom',
            'slot',
            'squeeze',
            'space',
            'vertical',
            'grid',
            'table',
            'columns',
            'cells',
            'data',
            'enter',
            'entry',
            'entries',
            'blocks',
            'rectangles',
            'chevron',
        ],
        categories: [
            'layout',
            'design',
            'tools',
        ],
    },
    {
        icon: 'CircleEllipsis',
        name: 'circle-ellipsis',
        tags: [
            'ellipsis',
            'et cetera',
            'etc',
            'loader',
            'loading',
            'progress',
            'pending',
            'throbber',
            'menu',
            'options',
            'operator',
            'code',
            'spread',
            'rest',
            'more',
            'further',
            'extra',
            'overflow',
            'dots',
            '…',
            '...',
        ],
        categories: [
            'layout',
            'development',
        ],
    },
    {
        icon: 'Columns2',
        name: 'columns-2',
        tags: [
            'lines',
            'list',
            'queue',
            'preview',
            'panel',
            'parallel',
            'series',
            'split',
            'vertical',
            'horizontal',
            'half',
            'center',
            'middle',
            'even',
            'sidebar',
            'drawer',
            'gutter',
            'fold',
            'reflow',
            'typography',
            'pagination',
            'pages',
        ],
        categories: [
            'layout',
            'design',
            'text',
        ],
    },
    {
        icon: 'Columns3Cog',
        name: 'columns-3-cog',
        tags: [
            'columns',
            'settings',
            'customize',
            'table',
            'grid',
            'adjust',
            'configuration',
            'panel',
            'layout',
        ],
        categories: [
            'layout',
            'design',
        ],
    },
    {
        icon: 'Columns3',
        name: 'columns-3',
        tags: [
            'lines',
            'list',
            'queue',
            'preview',
            'parallel',
            'series',
            'split',
            'vertical',
            'horizontal',
            'thirds',
            'triple',
            'center',
            'middle',
            'alignment',
            'even',
            'sidebars',
            'drawers',
            'gutters',
            'fold',
            'reflow',
            'typography',
            'pagination',
            'pages',
        ],
        categories: [
            'layout',
            'design',
            'text',
        ],
    },
    {
        icon: 'Columns4',
        name: 'columns-4',
        tags: [
            'lines',
            'list',
            'queue',
            'preview',
            'parallel',
            'series',
            'split',
            'vertical',
            'horizontal',
            'thirds',
            'triple',
            'center',
            'middle',
            'alignment',
            'even',
            'sidebars',
            'drawers',
            'gutters',
            'fold',
            'reflow',
            'typography',
            'pagination',
            'pages',
            'prison',
            'jail',
            'bars',
            'sentence',
            'police',
            'cops',
            'cell',
            'crime',
            'criminal',
            'justice',
            'law',
            'enforcement',
            'grill',
        ],
        categories: [
            'layout',
            'design',
            'text',
            'security',
        ],
    },
    {
        icon: 'Dock',
        name: 'dock',
        tags: [
            'desktop',
            'applications',
            'launch',
            'home',
            'menu bar',
            'bottom',
            'line',
            'macos',
            'osx',
        ],
        categories: [
            'layout',
            'design',
            'development',
            'files',
        ],
    },
    {
        icon: 'EllipsisVertical',
        name: 'ellipsis-vertical',
        tags: [
            'menu',
            'options',
            'spread',
            'more',
            'further',
            'extra',
            'overflow',
            'dots',
            '…',
            '...',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'Ellipsis',
        name: 'ellipsis',
        tags: [
            'et cetera',
            'etc',
            'loader',
            'loading',
            'progress',
            'pending',
            'throbber',
            'menu',
            'options',
            'operator',
            'code',
            'coding',
            'spread',
            'rest',
            'more',
            'further',
            'extra',
            'overflow',
            'dots',
            '…',
            '...',
        ],
        categories: [
            'layout',
            'development',
        ],
    },
    {
        icon: 'Fullscreen',
        name: 'fullscreen',
        tags: [
            'expand',
            'zoom',
            'preview',
            'focus',
            'camera',
            'lens',
            'image',
        ],
        categories: [
            'layout',
            'multimedia',
            'design',
            'photography',
        ],
    },
    {
        icon: 'FunnelPlus',
        name: 'funnel-plus',
        tags: [
            'filter',
            'hopper',
            'add',
            'create',
            'new',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'FunnelX',
        name: 'funnel-x',
        tags: [
            'filter',
            'hopper',
            'remove',
            'delete',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'Funnel',
        name: 'funnel',
        tags: [
            'filter',
            'hopper',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'GalleryHorizontalEnd',
        name: 'gallery-horizontal-end',
        tags: [
            'carousel',
            'pictures',
            'images',
            'scroll',
            'swipe',
            'album',
            'portfolio',
            'history',
            'versions',
            'backup',
            'time machine',
        ],
        categories: [
            'layout',
            'design',
            'development',
            'photography',
            'multimedia',
            'files',
        ],
    },
    {
        icon: 'GalleryHorizontal',
        name: 'gallery-horizontal',
        tags: [
            'carousel',
            'pictures',
            'images',
            'scroll',
            'swipe',
            'album',
            'portfolio',
        ],
        categories: [
            'layout',
            'design',
            'development',
            'photography',
            'multimedia',
        ],
    },
    {
        icon: 'GalleryThumbnails',
        name: 'gallery-thumbnails',
        tags: [
            'carousel',
            'pictures',
            'images',
            'album',
            'portfolio',
            'preview',
        ],
        categories: [
            'layout',
            'design',
            'development',
            'photography',
            'multimedia',
        ],
    },
    {
        icon: 'GalleryVerticalEnd',
        name: 'gallery-vertical-end',
        tags: [
            'carousel',
            'pictures',
            'images',
            'scroll',
            'swipe',
            'album',
            'portfolio',
            'history',
            'versions',
            'backup',
            'time machine',
        ],
        categories: [
            'layout',
            'design',
            'development',
            'photography',
            'multimedia',
            'files',
        ],
    },
    {
        icon: 'GalleryVertical',
        name: 'gallery-vertical',
        tags: [
            'carousel',
            'pictures',
            'images',
            'scroll',
            'swipe',
            'album',
            'portfolio',
        ],
        categories: [
            'layout',
            'design',
            'development',
            'photography',
            'multimedia',
        ],
    },
    {
        icon: 'GripHorizontal',
        name: 'grip-horizontal',
        tags: [
            'grab',
            'dots',
            'handle',
            'move',
            'drag',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'GripVertical',
        name: 'grip-vertical',
        tags: [
            'grab',
            'dots',
            'handle',
            'move',
            'drag',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'Grip',
        name: 'grip',
        tags: [
            'grab',
            'dots',
            'handle',
            'move',
            'drag',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'LayoutPanelTop',
        name: 'layout-panel-top',
        tags: [
            'window',
            'webpage',
            'block',
            'section',
            'grid',
            'template',
            'structure',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'LayoutTemplate',
        name: 'layout-template',
        tags: [
            'window',
            'webpage',
            'block',
            'section',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'Maximize',
        name: 'maximize',
        tags: [
            'fullscreen',
            'expand',
            'dashed',
        ],
        categories: [
            'layout',
            'design',
        ],
    },
    {
        icon: 'Menu',
        name: 'menu',
        tags: [
            'bars',
            'navigation',
            'hamburger',
            'options',
        ],
        categories: [
            'layout',
            'account',
        ],
    },
    {
        icon: 'Minimize',
        name: 'minimize',
        tags: [
            'exit fullscreen',
            'close',
            'shrink',
        ],
        categories: [
            'layout',
            'design',
        ],
    },
    {
        icon: 'PanelBottomClose',
        name: 'panel-bottom-close',
        tags: [
            'drawer',
            'dock',
            'hide',
            'chevron',
            'down',
        ],
        categories: [
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'PanelBottomDashed',
        name: 'panel-bottom-dashed',
        tags: [
            'drawer',
            'dock',
            'show',
            'reveal',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'PanelBottomOpen',
        name: 'panel-bottom-open',
        tags: [
            'drawer',
            'dock',
            'show',
            'reveal',
            'chevron',
            'up',
        ],
        categories: [
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'PanelBottom',
        name: 'panel-bottom',
        tags: [
            'drawer',
            'dock',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'PanelLeftClose',
        name: 'panel-left-close',
        tags: [
            'primary',
            'drawer',
            'hide',
            'chevron',
            '<',
        ],
        categories: [
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'PanelLeftDashed',
        name: 'panel-left-dashed',
        tags: [
            'sidebar',
            'primary',
            'drawer',
            'show',
            'reveal',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'PanelLeftOpen',
        name: 'panel-left-open',
        tags: [
            'primary',
            'drawer',
            'show',
            'reveal',
            'chevron',
            'right',
            '>',
        ],
        categories: [
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'PanelLeft',
        name: 'panel-left',
        tags: [
            'primary',
            'drawer',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'PanelRightClose',
        name: 'panel-right-close',
        tags: [
            'sidebar',
            'secondary',
            'drawer',
            'hide',
            'chevron',
            '>',
        ],
        categories: [
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'PanelRightDashed',
        name: 'panel-right-dashed',
        tags: [
            'sidebar',
            'secondary',
            'drawer',
            'show',
            'reveal',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'PanelRightOpen',
        name: 'panel-right-open',
        tags: [
            'sidebar',
            'secondary',
            'drawer',
            'show',
            'reveal',
            'chevron',
            'left',
            '<',
        ],
        categories: [
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'PanelRight',
        name: 'panel-right',
        tags: [
            'sidebar',
            'secondary',
            'drawer',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'PanelTopClose',
        name: 'panel-top-close',
        tags: [
            'menu bar',
            'drawer',
            'hide',
            'chevron',
            'up',
        ],
        categories: [
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'PanelTopDashed',
        name: 'panel-top-dashed',
        tags: [
            'menu bar',
            'drawer',
            'show',
            'reveal',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'PanelTopOpen',
        name: 'panel-top-open',
        tags: [
            'menu bar',
            'drawer',
            'show',
            'reveal',
            'chevron',
            'down',
        ],
        categories: [
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'PanelTop',
        name: 'panel-top',
        tags: [
            'drawer',
            'browser',
            'webpage',
        ],
        categories: [
            'layout',
            'design',
            'development',
        ],
    },
    {
        icon: 'PanelsLeftBottom',
        name: 'panels-left-bottom',
        tags: [
            'drawers',
            'sidebar',
            'primary',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'PanelsRightBottom',
        name: 'panels-right-bottom',
        tags: [
            'drawers',
            'sidebar',
            'secondary',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'PanelsTopLeft',
        name: 'panels-top-left',
        tags: [
            'menu bar',
            'sidebar',
            'primary',
            'drawers',
            'window',
            'webpage',
            'projects',
            'overview',
        ],
        categories: [
            'layout',
            'design',
            'development',
        ],
    },
    {
        icon: 'Proportions',
        name: 'proportions',
        tags: [
            'screens',
            'sizes',
            'rotate',
            'rotation',
            'adjust',
            'aspect ratio',
            '16:9',
            'widescreen',
            '4:3',
            'resolution',
            'responsive',
            'mobile',
            'desktop',
            'dimensions',
            'monitor',
            'orientation',
            'portrait',
            'landscape',
        ],
        categories: [
            'layout',
            'design',
            'photography',
            'devices',
        ],
    },
    {
        icon: 'Ratio',
        name: 'ratio',
        tags: [
            'screens',
            'sizes',
            'rotate',
            'rotation',
            'adjust',
            'aspect ratio',
            'proportions',
            '16:9',
            'widescreen',
            '4:3',
            'resolution',
            'responsive',
            'mobile',
            'desktop',
            'dimensions',
            'monitor',
            'orientation',
            'portrait',
            'landscape',
        ],
        categories: [
            'layout',
            'design',
            'photography',
        ],
    },
    {
        icon: 'RotateCcwSquare',
        name: 'rotate-ccw-square',
        tags: [
            'left',
            'counter-clockwise',
            'rotate',
            'image',
            '90',
            '45',
            'degrees',
            '°',
        ],
        categories: [
            'layout',
            'design',
            'photography',
            'tools',
            'arrows',
        ],
    },
    {
        icon: 'RotateCwSquare',
        name: 'rotate-cw-square',
        tags: [
            'right',
            'clockwise',
            'rotate',
            'image',
            '90',
            '45',
            'degrees',
            '°',
        ],
        categories: [
            'layout',
            'design',
            'photography',
            'tools',
            'arrows',
        ],
    },
    {
        icon: 'Rows2',
        name: 'rows-2',
        tags: [
            'lines',
            'list',
            'queue',
            'preview',
            'panel',
            'paragraphs',
            'parallel',
            'series',
            'split',
            'vertical',
            'horizontal',
            'half',
            'center',
            'middle',
            'even',
            'drawer',
        ],
        categories: [
            'layout',
            'design',
            'text',
        ],
    },
    {
        icon: 'Rows3',
        name: 'rows-3',
        tags: [
            'lines',
            'list',
            'queue',
            'preview',
            'paragraphs',
            'parallel',
            'series',
            'split',
            'vertical',
            'horizontal',
            'half',
            'center',
            'middle',
            'even',
            'drawers',
        ],
        categories: [
            'layout',
            'design',
            'text',
        ],
    },
    {
        icon: 'Rows4',
        name: 'rows-4',
        tags: [
            'lines',
            'list',
            'queue',
            'preview',
            'paragraphs',
            'parallel',
            'series',
            'split',
            'vertical',
            'horizontal',
            'half',
            'center',
            'middle',
            'even',
            'drawers',
            'grill',
        ],
        categories: [
            'layout',
            'design',
            'text',
        ],
    },
    {
        icon: 'Shrink',
        name: 'shrink',
        tags: [
            'scale',
            'fullscreen',
        ],
        categories: [
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'SquareMenu',
        name: 'square-menu',
        tags: [
            'bars',
            'navigation',
            'hamburger',
            'options',
            'menu bar',
            'panel',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'SquareSplitHorizontal',
        name: 'square-split-horizontal',
        tags: [
            'split',
            'divide',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'SquareSplitVertical',
        name: 'square-split-vertical',
        tags: [
            'split',
            'divide',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'SquareSquare',
        name: 'square-square',
        tags: [
            'float',
            'center',
            'rectangle',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'StretchHorizontal',
        name: 'stretch-horizontal',
        tags: [
            'items',
            'flex',
            'justify',
            'distribute',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'StretchVertical',
        name: 'stretch-vertical',
        tags: [
            'items',
            'flex',
            'justify',
            'distribute',
        ],
        categories: [
            'layout',
        ],
    },
    {
        icon: 'ToggleLeft',
        name: 'toggle-left',
        tags: [
            'on',
            'off',
            'switch',
            'boolean',
        ],
        categories: [
            'layout',
            'account',
            'development',
        ],
    },
    {
        icon: 'ToggleRight',
        name: 'toggle-right',
        tags: [
            'on',
            'off',
            'switch',
            'boolean',
        ],
        categories: [
            'layout',
            'account',
            'development',
        ],
    },
];
export default icons;
