// Icons with primary category: math
const icons = [
    {
        icon: 'Calculator',
        name: 'calculator',
        tags: [
            'count',
            'calculating machine',
        ],
        categories: [
            'math',
            'devices',
        ],
    },
    {
        icon: 'CircleDivide',
        name: 'circle-divide',
        tags: [
            'calculate',
            'math',
            '÷',
            '/',
        ],
        categories: [
            'math',
        ],
    },
    {
        icon: 'CircleEqual',
        name: 'circle-equal',
        tags: [
            'calculate',
            'shape',
            '=',
        ],
        categories: [
            'math',
        ],
    },
    {
        icon: 'CircleMinus',
        name: 'circle-minus',
        tags: [
            'subtract',
            'remove',
            'decrease',
            'reduce',
            'calculate',
            'line',
            'operator',
            'code',
            'coding',
            'minimum',
            'downgrade',
            '-',
        ],
        categories: [
            'math',
        ],
    },
    {
        icon: 'CirclePlus',
        name: 'circle-plus',
        tags: [
            'add',
            'new',
            'increase',
            'increment',
            'positive',
            'calculate',
            'crosshair',
            'aim',
            'target',
            'scope',
            'sight',
            'reticule',
            'maximum',
            'upgrade',
            'extra',
            'operator',
            'join',
            'concatenate',
            'code',
            'coding',
            '+',
        ],
        categories: [
            'math',
            'development',
            'cursors',
            'gaming',
        ],
    },
    {
        icon: 'CircleX',
        name: 'circle-x',
        tags: [
            'cancel',
            'close',
            'delete',
            'remove',
            'times',
            'clear',
            'error',
            'incorrect',
            'wrong',
            'mistake',
            'failure',
            'linter',
            'multiply',
            'multiplication',
        ],
        categories: [
            'math',
            'development',
        ],
    },
    {
        icon: 'Divide',
        name: 'divide',
        tags: [
            'calculate',
            'math',
            'division',
            'operator',
            'code',
            '÷',
            '/',
        ],
        categories: [
            'math',
            'development',
        ],
    },
    {
        icon: 'DraftingCompass',
        name: 'drafting-compass',
        tags: [
            'geometry',
            'trigonometry',
            'radius',
            'diameter',
            'circumference',
            'calculate',
            'measure',
            'arc',
            'curve',
            'draw',
            'sketch',
        ],
        categories: [
            'math',
            'design',
            'tools',
        ],
    },
    {
        icon: 'EqualApproximately',
        name: 'equal-approximately',
        tags: [
            'about',
            'calculate',
            'math',
            'operater',
        ],
        categories: [
            'math',
        ],
    },
    {
        icon: 'EqualNot',
        name: 'equal-not',
        tags: [
            'calculate',
            'off',
            'math',
            'operator',
            'code',
            '≠',
        ],
        categories: [
            'math',
            'development',
        ],
    },
    {
        icon: 'Equal',
        name: 'equal',
        tags: [
            'calculate',
            'math',
            'operator',
            'assignment',
            'code',
            '=',
        ],
        categories: [
            'math',
            'development',
        ],
    },
    {
        icon: 'Minus',
        name: 'minus',
        tags: [
            'subtract',
            'remove',
            'decrease',
            'decrement',
            'reduce',
            'negative',
            'calculate',
            'line',
            'divider',
            'separator',
            'horizontal rule',
            'hr',
            'html',
            'markup',
            'markdown',
            '---',
            'toolbar',
            'operator',
            'code',
            'coding',
            'minimum',
            'downgrade',
        ],
        categories: [
            'math',
            'development',
            'text',
            'tools',
        ],
    },
    {
        icon: 'OctagonX',
        name: 'octagon-x',
        tags: [
            'delete',
            'stop',
            'alert',
            'warning',
            'times',
            'clear',
            'math',
        ],
        categories: [
            'math',
            'notifications',
        ],
    },
    {
        icon: 'Omega',
        name: 'omega',
        tags: [
            'greek',
            'symbol',
            'mathematics',
            'education',
            'physics',
            'engineering',
            'ohms',
            'electrical resistance',
            'angular frequency',
            'dynamical systems',
            'astronomy',
            'constellations',
            'philosophy',
        ],
        categories: [
            'math',
            'development',
            'text',
            'science',
        ],
    },
    {
        icon: 'Percent',
        name: 'percent',
        tags: [
            'percentage',
            'modulo',
            'modulus',
            'remainder',
            '%',
            'sale',
            'discount',
            'offer',
            'marketing',
        ],
        categories: [
            'math',
            'development',
            'finance',
            'shopping',
        ],
    },
    {
        icon: 'Plus',
        name: 'plus',
        tags: [
            'add',
            'new',
            'increase',
            'increment',
            'positive',
            'calculate',
            'toolbar',
            'crosshair',
            'aim',
            'target',
            'scope',
            'sight',
            'reticule',
            'maximum',
            'upgrade',
            'extra',
            '+',
        ],
        categories: [
            'math',
            'tools',
            'development',
            'text',
            'cursors',
            'gaming',
        ],
    },
    {
        icon: 'SquareDivide',
        name: 'square-divide',
        tags: [
            'calculate',
            'math',
            '÷',
            '/',
        ],
        categories: [
            'math',
        ],
    },
    {
        icon: 'SquareEqual',
        name: 'square-equal',
        tags: [
            'calculate',
            '=',
        ],
        categories: [
            'math',
        ],
    },
    {
        icon: 'SquareMinus',
        name: 'square-minus',
        tags: [
            'subtract',
            'remove',
            'decrease',
            'reduce',
            'calculator',
            'button',
            'keyboard',
            'line',
            'divider',
            'separator',
            'horizontal rule',
            'hr',
            'html',
            'markup',
            'markdown',
            '---',
            'toolbar',
            'operator',
            'code',
            'coding',
            'minimum',
            'downgrade',
        ],
        categories: [
            'math',
            'development',
            'text',
            'tools',
            'devices',
        ],
    },
    {
        icon: 'SquarePlus',
        name: 'square-plus',
        tags: [
            'add',
            'new',
            'increase',
            'increment',
            'positive',
            'calculate',
            'calculator',
            'button',
            'keyboard',
            'toolbar',
            'maximum',
            'upgrade',
            'extra',
            'operator',
            'join',
            'concatenate',
            'code',
            'coding',
            '+',
        ],
        categories: [
            'math',
            'tools',
            'development',
            'text',
        ],
    },
    {
        icon: 'SquareX',
        name: 'square-x',
        tags: [
            'cancel',
            'close',
            'delete',
            'remove',
            'times',
            'clear',
            'math',
            'multiply',
            'multiplication',
        ],
        categories: [
            'math',
            'notifications',
        ],
    },
    {
        icon: 'Tally1',
        name: 'tally-1',
        tags: [
            'count',
            'score',
            'enumerate',
            'days',
            'one',
            '1',
            'first',
            'bar',
            'prison',
            'cell',
            'sentence',
        ],
        categories: [
            'math',
            'gaming',
        ],
    },
    {
        icon: 'Tally2',
        name: 'tally-2',
        tags: [
            'count',
            'score',
            'enumerate',
            'days',
            'two',
            '2',
            'second',
            'double',
            'bars',
            'prison',
            'cell',
            'sentence',
        ],
        categories: [
            'math',
            'gaming',
        ],
    },
    {
        icon: 'Tally3',
        name: 'tally-3',
        tags: [
            'count',
            'score',
            'enumerate',
            'days',
            'three',
            '3',
            'third',
            'triple',
            'bars',
            'prison',
            'cell',
            'sentence',
        ],
        categories: [
            'math',
            'gaming',
        ],
    },
    {
        icon: 'Tally4',
        name: 'tally-4',
        tags: [
            'count',
            'score',
            'enumerate',
            'days',
            '4',
            'fourth',
            'quadruple',
            'bars',
            'prison',
            'cell',
            'sentence',
        ],
        categories: [
            'math',
            'gaming',
        ],
    },
    {
        icon: 'Tally5',
        name: 'tally-5',
        tags: [
            'count',
            'score',
            'enumerate',
            'days',
            'five',
            '5',
            'fifth',
            'bars',
            'prison',
            'cell',
            'sentence',
            'slash',
            '/',
        ],
        categories: [
            'math',
            'gaming',
        ],
    },
    {
        icon: 'Weight',
        name: 'weight',
        tags: [
            'mass',
            'heavy',
            'lead',
            'metal',
            'measure',
            'geometry',
            'scales',
            'balance',
        ],
        categories: [
            'math',
        ],
    },
];
export default icons;
