// Icons with primary category: medical
const icons = [
    {
        icon: 'Activity',
        name: 'activity',
        tags: [
            'pulse',
            'action',
            'motion',
            'movement',
            'exercise',
            'fitness',
            'healthcare',
            'heart rate monitor',
            'vital signs',
            'vitals',
            'emergency room',
            'er',
            'intensive care',
            'hospital',
            'defibrillator',
            'earthquake',
            'siesmic',
            'magnitude',
            'richter scale',
            'aftershock',
            'tremor',
            'shockwave',
            'audio',
            'waveform',
            'synthesizer',
            'synthesiser',
            'music',
        ],
        categories: [
            'medical',
            'account',
            'social',
            'science',
            'multimedia',
        ],
    },
    {
        icon: 'Ambulance',
        name: 'ambulance',
        tags: [
            'ambulance',
            'emergency',
            'medical',
            'vehicle',
            'siren',
            'healthcare',
            'transportation',
            'rescue',
            'urgent',
            'first aid',
        ],
        categories: [
            'medical',
            'transportation',
        ],
    },
    {
        icon: 'Bandage',
        name: 'bandage',
        tags: [
            'plaster',
            'band-aid',
            'first aid',
            'medical',
            'health',
            'wound',
            'injury',
            'care',
            'treatment',
            'healing',
            'protection',
            'emergency',
            'aid',
            'safety',
        ],
        categories: [
            'medical',
        ],
    },
    {
        icon: 'Brain',
        name: 'brain',
        tags: [
            'medical',
            'mind',
            'intellect',
            'cerebral',
            'consciousness',
            'genius',
            'artificial intelligence',
            'ai',
        ],
        categories: [
            'medical',
            'science',
        ],
    },
    {
        icon: 'BriefcaseMedical',
        name: 'briefcase-medical',
        tags: [
            'doctor',
            'medicine',
            'first aid',
        ],
        categories: [
            'medical',
            'transportation',
        ],
    },
    {
        icon: 'DnaOff',
        name: 'dna-off',
        tags: [
            'gene',
            'gmo free',
            'helix',
            'heredity',
            'chromosome',
            'nucleic acid',
        ],
        categories: [
            'medical',
            'food-beverage',
        ],
    },
    {
        icon: 'Dna',
        name: 'dna',
        tags: [
            'gene',
            'gmo',
            'helix',
            'heredity',
            'chromosome',
            'nucleic acid',
        ],
        categories: [
            'medical',
        ],
    },
    {
        icon: 'EarOff',
        name: 'ear-off',
        tags: [
            'hearing',
            'hard of hearing',
            'hearing loss',
            'deafness',
            'noise',
            'silence',
            'audio',
            'accessibility',
        ],
        categories: [
            'medical',
            'accessibility',
        ],
    },
    {
        icon: 'Ear',
        name: 'ear',
        tags: [
            'hearing',
            'noise',
            'audio',
            'accessibility',
        ],
        categories: [
            'medical',
            'accessibility',
        ],
    },
    {
        icon: 'HeartMinus',
        name: 'heart-minus',
        tags: [
            'unlike',
            'unfavorite',
            'remove',
            'damage',
            'ui & ux',
        ],
        categories: [
            'medical',
            'account',
            'multimedia',
            'gaming',
            'social',
        ],
    },
    {
        icon: 'HeartPlus',
        name: 'heart-plus',
        tags: [
            'plus',
            'like',
            'favorite',
            'add',
            'health',
            'support',
        ],
        categories: [
            'medical',
            'account',
            'multimedia',
            'gaming',
            'social',
        ],
    },
    {
        icon: 'HeartPulse',
        name: 'heart-pulse',
        tags: [
            'heartbeat',
            'pulse',
            'health',
            'medical',
            'blood pressure',
            'cardiac',
            'systole',
            'diastole',
        ],
        categories: [
            'medical',
        ],
    },
    {
        icon: 'Heart',
        name: 'heart',
        tags: [
            'like',
            'love',
            'emotion',
            'suit',
            'playing',
            'cards',
        ],
        categories: [
            'medical',
            'social',
            'multimedia',
            'emoji',
            'gaming',
            'shapes',
        ],
    },
    {
        icon: 'Hospital',
        name: 'hospital',
        tags: [
            'infirmary',
            'sanatorium',
            'healthcare',
            'doctor',
            'hospice',
            'clinic',
            'emergency room',
            'ward',
            'building',
            'medical',
            'vet',
        ],
        categories: [
            'medical',
            'buildings',
            'navigation',
            'travel',
        ],
    },
    {
        icon: 'MarsStroke',
        name: 'mars-stroke',
        tags: [
            'gender',
            'androgyne',
            'transgender',
        ],
        categories: [
            'medical',
        ],
    },
    {
        icon: 'Mars',
        name: 'mars',
        tags: [
            'gender',
            'sex',
            'male',
            'masculine',
            'man',
            'boy',
        ],
        categories: [
            'medical',
        ],
    },
    {
        icon: 'NonBinary',
        name: 'non-binary',
        tags: [
            'gender',
            'nonbinary',
            'enby',
        ],
        categories: [
            'medical',
        ],
    },
    {
        icon: 'PillBottle',
        name: 'pill-bottle',
        tags: [
            'medicine',
            'medication',
            'prescription',
            'drug',
            'supplement',
            'vitamin',
            'capsule',
            'jar',
            'container',
            'healthcare',
            'pharmaceutical',
            'tablet',
        ],
        categories: [
            'medical',
        ],
    },
    {
        icon: 'Pill',
        name: 'pill',
        tags: [
            'medicine',
            'medication',
            'drug',
            'prescription',
            'tablet',
            'pharmacy',
        ],
        categories: [
            'medical',
        ],
    },
    {
        icon: 'ScanHeart',
        name: 'scan-heart',
        tags: [
            'health',
            'heart rate',
            'pulse',
            'monitoring',
            'healthiness',
            'screening',
            'dashed',
        ],
        categories: [
            'medical',
        ],
    },
    {
        icon: 'Siren',
        name: 'siren',
        tags: [
            'police',
            'ambulance',
            'emergency',
            'security',
            'alert',
            'alarm',
            'light',
        ],
        categories: [
            'medical',
        ],
    },
    {
        icon: 'SquareActivity',
        name: 'square-activity',
        tags: [
            'pulse',
            'action',
            'motion',
            'movement',
            'exercise',
            'fitness',
            'healthcare',
            'heart rate monitor',
            'vital signs',
            'vitals',
            'emergency room',
            'er',
            'intensive care',
            'hospital',
            'defibrillator',
            'earthquake',
            'siesmic',
            'magnitude',
            'richter scale',
            'aftershock',
            'tremor',
            'shockwave',
            'audio',
            'waveform',
            'synthesizer',
            'synthesiser',
            'music',
        ],
        categories: [
            'medical',
            'social',
            'science',
            'multimedia',
        ],
    },
    {
        icon: 'Tablets',
        name: 'tablets',
        tags: [
            'medicine',
            'medication',
            'drug',
            'prescription',
            'pills',
            'pharmacy',
        ],
        categories: [
            'medical',
        ],
    },
    {
        icon: 'Transgender',
        name: 'transgender',
        tags: [
            'gender',
            'inclusive',
        ],
        categories: [
            'medical',
            'accessibility',
        ],
    },
    {
        icon: 'VenusAndMars',
        name: 'venus-and-mars',
        tags: [
            'gender',
            'sex',
            'intersex',
            'androgynous',
            'hermaphrodite',
        ],
        categories: [
            'medical',
        ],
    },
    {
        icon: 'Venus',
        name: 'venus',
        tags: [
            'gender',
            'sex',
            'female',
            'feminine',
            'woman',
            'girl',
        ],
        categories: [
            'medical',
        ],
    },
];
export default icons;
