// Icons with primary category: multimedia
const icons = [
    {
        icon: 'Airplay',
        name: 'airplay',
        tags: [
            'stream',
            'cast',
            'mirroring',
            'screen',
            'monitor',
            'macos',
            'osx',
        ],
        categories: [
            'multimedia',
            'connectivity',
            'devices',
            'brands',
        ],
    },
    {
        icon: 'AudioLines',
        name: 'audio-lines',
        tags: [
            'graphic equaliser',
            'sound',
            'noise',
            'listen',
            'hearing',
            'hertz',
            'frequency',
            'wavelength',
            'vibrate',
            'sine',
            'synthesizer',
            'synthesiser',
            'levels',
            'track',
            'music',
            'playback',
            'radio',
            'broadcast',
            'airwaves',
            'voice',
            'vocals',
            'singer',
            'song',
        ],
        categories: [
            'multimedia',
            'communication',
        ],
    },
    {
        icon: 'AudioWaveform',
        name: 'audio-waveform',
        tags: [
            'sound',
            'noise',
            'listen',
            'hearing',
            'hertz',
            'frequency',
            'wavelength',
            'vibrate',
            'sine',
            'synthesizer',
            'synthesiser',
            'levels',
            'track',
            'music',
            'playback',
            'radio',
            'broadcast',
            'airwaves',
            'voice',
            'vocals',
            'singer',
            'song',
        ],
        categories: [
            'multimedia',
            'communication',
        ],
    },
    {
        icon: 'BookAudio',
        name: 'book-audio',
        tags: [
            'audiobook',
            'reading',
            'listening',
            'sound',
            'story',
            'fiction',
            'novel',
            'information',
            'knowledge',
            'education',
            'student',
            'study',
            'learning',
            'research',
        ],
        categories: [
            'multimedia',
            'text',
        ],
    },
    {
        icon: 'BookHeadphones',
        name: 'book-headphones',
        tags: [
            'audiobook',
            'reading',
            'listening',
            'sound',
            'story',
            'fiction',
            'novel',
            'information',
            'knowledge',
            'education',
            'student',
            'study',
            'learning',
            'research',
        ],
        categories: [
            'multimedia',
            'text',
        ],
    },
    {
        icon: 'CaptionsOff',
        name: 'captions-off',
        tags: [
            'closed captions',
            'subtitles',
            'subhead',
            'transcription',
            'transcribe',
            'dialogue',
            'accessibility',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'Captions',
        name: 'captions',
        tags: [
            'closed captions',
            'subtitles',
            'subhead',
            'transcription',
            'transcribe',
            'dialogue',
            'accessibility',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'CirclePause',
        name: 'circle-pause',
        tags: [
            'music',
            'audio',
            'stop',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'CirclePlay',
        name: 'circle-play',
        tags: [
            'music',
            'start',
            'run',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'CircleStop',
        name: 'circle-stop',
        tags: [
            'media',
            'music',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'Clapperboard',
        name: 'clapperboard',
        tags: [
            'movie',
            'film',
            'video',
            'camera',
            'cinema',
            'cut',
            'action',
            'television',
            'tv',
            'show',
            'entertainment',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'DiamondMinus',
        name: 'diamond-minus',
        tags: [
            'keyframe',
            'subtract',
            'remove',
            'decrease',
            'reduce',
            'calculator',
            'button',
            'keyboard',
            'line',
            'divider',
            'separator',
            'horizontal rule',
            'hr',
            'html',
            'markup',
            'markdown',
            '---',
            'toolbar',
            'operator',
            'code',
            'coding',
            'minimum',
            'downgrade',
        ],
        categories: [
            'multimedia',
            'photography',
            'tools',
            'devices',
        ],
    },
    {
        icon: 'DiamondPlus',
        name: 'diamond-plus',
        tags: [
            'keyframe',
            'add',
            'new',
            'increase',
            'increment',
            'positive',
            'calculate',
            'toolbar',
            'crosshair',
            'aim',
            'target',
            'scope',
            'sight',
            'reticule',
            'maximum',
            'upgrade',
            'extra',
            '+',
        ],
        categories: [
            'multimedia',
            'photography',
            'tools',
            'devices',
        ],
    },
    {
        icon: 'Drama',
        name: 'drama',
        tags: [
            'drama',
            'masks',
            'theater',
            'theatre',
            'entertainment',
            'show',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'Drum',
        name: 'drum',
        tags: [
            'drummer',
            'kit',
            'sticks',
            'instrument',
            'beat',
            'bang',
            'bass',
            'backing track',
            'band',
            'play',
            'performance',
            'concert',
            'march',
            'music',
            'audio',
            'sound',
            'noise',
            'loud',
        ],
        categories: [
            'multimedia',
            'devices',
        ],
    },
    {
        icon: 'FastForward',
        name: 'fast-forward',
        tags: [
            'music',
        ],
        categories: [
            'multimedia',
            'arrows',
        ],
    },
    {
        icon: 'Guitar',
        name: 'guitar',
        tags: [
            'acoustic',
            'instrument',
            'strings',
            'riff',
            'rock',
            'band',
            'country',
            'concert',
            'performance',
            'play',
            'lead',
            'loud',
            'music',
            'audio',
            'sound',
            'noise',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'HeadphoneOff',
        name: 'headphone-off',
        tags: [
            'music',
            'audio',
            'sound',
            'mute',
            'off',
        ],
        categories: [
            'multimedia',
            'connectivity',
            'communication',
            'devices',
            'gaming',
        ],
    },
    {
        icon: 'Headphones',
        name: 'headphones',
        tags: [
            'music',
            'audio',
            'sound',
        ],
        categories: [
            'multimedia',
            'connectivity',
            'devices',
            'files',
            'gaming',
        ],
    },
    {
        icon: 'Headset',
        name: 'headset',
        tags: [
            'music',
            'audio',
            'sound',
            'gaming',
            'headphones',
            'headset',
            'call',
            'center',
            'phone',
            'telephone',
            'voip',
            'video',
        ],
        categories: [
            'multimedia',
            'connectivity',
            'devices',
            'files',
            'gaming',
        ],
    },
    {
        icon: 'Infinity',
        name: 'infinity',
        tags: [
            'unlimited',
            'forever',
            'loop',
            'math',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'KeyboardMusic',
        name: 'keyboard-music',
        tags: [
            'music',
            'audio',
            'sound',
            'noise',
            'notes',
            'keys',
            'chord',
            'octave',
            'midi',
            'controller',
            'instrument',
            'electric',
            'signal',
            'digital',
            'studio',
            'production',
            'producer',
            'pianist',
            'piano',
            'play',
            'performance',
            'concert',
        ],
        categories: [
            'multimedia',
            'devices',
        ],
    },
    {
        icon: 'ListEnd',
        name: 'list-end',
        tags: [
            'queue',
            'bottom',
            'end',
            'playlist',
        ],
        categories: [
            'multimedia',
            'text',
        ],
    },
    {
        icon: 'ListMinus',
        name: 'list-minus',
        tags: [
            'playlist',
            'remove',
            'song',
            'subtract',
            'delete',
            'unqueue',
        ],
        categories: [
            'multimedia',
            'text',
        ],
    },
    {
        icon: 'ListMusic',
        name: 'list-music',
        tags: [
            'playlist',
            'queue',
            'music',
            'audio',
            'playback',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'ListPlus',
        name: 'list-plus',
        tags: [
            'playlist',
            'add',
            'song',
            'track',
            'new',
        ],
        categories: [
            'multimedia',
            'text',
        ],
    },
    {
        icon: 'ListRestart',
        name: 'list-restart',
        tags: [
            'reset',
            'refresh',
            'reload',
            'playlist',
            'replay',
        ],
        categories: [
            'multimedia',
            'text',
        ],
    },
    {
        icon: 'ListStart',
        name: 'list-start',
        tags: [
            'queue',
            'top',
            'start',
            'next',
            'playlist',
        ],
        categories: [
            'multimedia',
            'text',
        ],
    },
    {
        icon: 'ListVideo',
        name: 'list-video',
        tags: [
            'playlist',
            'video',
            'playback',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'ListX',
        name: 'list-x',
        tags: [
            'playlist',
            'subtract',
            'remove',
            'delete',
            'unqueue',
        ],
        categories: [
            'multimedia',
            'text',
        ],
    },
    {
        icon: 'MegaphoneOff',
        name: 'megaphone-off',
        tags: [
            'advertisement',
            'attention',
            'alert',
            'notification',
            'disable',
            'silent',
        ],
        categories: [
            'multimedia',
            'notifications',
        ],
    },
    {
        icon: 'Megaphone',
        name: 'megaphone',
        tags: [
            'advertisement',
            'attention',
            'alert',
            'notification',
        ],
        categories: [
            'multimedia',
            'notifications',
        ],
    },
    {
        icon: 'Music2',
        name: 'music-2',
        tags: [
            'quaver',
            'eighth note',
            'note',
        ],
        categories: [
            'multimedia',
            'files',
        ],
    },
    {
        icon: 'Music3',
        name: 'music-3',
        tags: [
            'crotchet',
            'minim',
            'quarter note',
            'half note',
            'note',
        ],
        categories: [
            'multimedia',
            'files',
        ],
    },
    {
        icon: 'Music4',
        name: 'music-4',
        tags: [
            'semiquaver',
            'sixteenth note',
            'note',
        ],
        categories: [
            'multimedia',
            'files',
        ],
    },
    {
        icon: 'Music',
        name: 'music',
        tags: [
            'note',
            'quaver',
            'eighth note',
        ],
        categories: [
            'multimedia',
            'files',
        ],
    },
    {
        icon: 'Newspaper',
        name: 'newspaper',
        tags: [
            'news',
            'feed',
            'home',
            'magazine',
            'article',
            'headline',
        ],
        categories: [
            'multimedia',
            'communication',
        ],
    },
    {
        icon: 'OctagonPause',
        name: 'octagon-pause',
        tags: [
            'music',
            'audio',
            'stop',
        ],
        categories: [
            'multimedia',
            'shapes',
        ],
    },
    {
        icon: 'Pause',
        name: 'pause',
        tags: [
            'music',
            'stop',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'Piano',
        name: 'piano',
        tags: [
            'music',
            'audio',
            'sound',
            'noise',
            'notes',
            'chord',
            'keys',
            'octave',
            'acoustic',
            'instrument',
            'play',
            'pianist',
            'performance',
            'concert',
        ],
        categories: [
            'multimedia',
            'devices',
        ],
    },
    {
        icon: 'PictureInPicture2',
        name: 'picture-in-picture-2',
        tags: [
            'display',
            'play',
            'video',
            'pop out',
            'always on top',
            'window',
            'inset',
            'multitask',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'PictureInPicture',
        name: 'picture-in-picture',
        tags: [
            'display',
            'play',
            'video',
            'pop out',
            'always on top',
            'window',
            'inset',
            'multitask',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'Podcast',
        name: 'podcast',
        tags: [
            'audio',
            'music',
            'mic',
            'talk',
            'voice',
            'subscribe',
            'subscription',
            'stream',
        ],
        categories: [
            'multimedia',
            'social',
        ],
    },
    {
        icon: 'Presentation',
        name: 'presentation',
        tags: [
            'screen',
            'whiteboard',
            'marker pens',
            'markers',
            'blackboard',
            'chalk',
            'easel',
            'school',
            'learning',
            'lesson',
            'office',
            'meeting',
            'project',
            'planning',
        ],
        categories: [
            'multimedia',
            'photography',
            'devices',
            'communication',
            'design',
        ],
    },
    {
        icon: 'Projector',
        name: 'projector',
        tags: [
            'cinema',
            'film',
            'movie',
            'home video',
            'presentation',
            'slideshow',
            'office',
            'meeting',
            'project',
            'planning',
        ],
        categories: [
            'multimedia',
            'photography',
            'devices',
            'communication',
        ],
    },
    {
        icon: 'Repeat1',
        name: 'repeat-1',
        tags: [
            'replay',
        ],
        categories: [
            'multimedia',
        ],
    },
    {
        icon: 'Shuffle',
        name: 'shuffle',
        tags: [
            'music',
            'random',
            'reorder',
        ],
        categories: [
            'multimedia',
            'arrows',
        ],
    },
    {
        icon: 'SkipBack',
        name: 'skip-back',
        tags: [
            'arrow',
            'previous',
            'music',
        ],
        categories: [
            'multimedia',
            'arrows',
        ],
    },
    {
        icon: 'SkipForward',
        name: 'skip-forward',
        tags: [
            'arrow',
            'skip',
            'next',
            'music',
        ],
        categories: [
            'multimedia',
            'arrows',
        ],
    },
    {
        icon: 'Speaker',
        name: 'speaker',
        tags: [
            'sound',
            'audio',
            'music',
            'tweeter',
            'subwoofer',
            'bass',
            'production',
            'producer',
            'dj',
        ],
        categories: [
            'multimedia',
            'devices',
        ],
    },
    {
        icon: 'StarOff',
        name: 'star-off',
        tags: [
            'dislike',
            'unlike',
            'remove',
            'unrate',
        ],
        categories: [
            'multimedia',
            'social',
        ],
    },
    {
        icon: 'StepBack',
        name: 'step-back',
        tags: [
            'arrow',
            'previous',
            'music',
            'left',
            'reverse',
        ],
        categories: [
            'multimedia',
            'arrows',
        ],
    },
    {
        icon: 'StepForward',
        name: 'step-forward',
        tags: [
            'arrow',
            'next',
            'music',
            'right',
            'continue',
        ],
        categories: [
            'multimedia',
            'arrows',
        ],
    },
    {
        icon: 'Youtube',
        name: 'youtube',
        tags: [
            'logo',
            'social',
            'video',
            'play',
        ],
        categories: [
            'multimedia',
            'social',
            'brands',
        ],
    },
];
export default icons;
