// Icons with primary category: navigation
const icons = [
    {
        icon: 'Binoculars',
        name: 'binoculars',
        tags: [
            'field glasses',
            'lorgnette',
            'pince-nez',
            'observation',
            'sightseeing',
            'nature',
            'wildlife',
            'birdwatching',
            'scouting',
            'surveillance',
            'search',
            'discovery',
            'monitoring',
            'lookout',
            'viewpoint',
            'travel',
            'tourism',
            'research',
        ],
        categories: [
            'navigation',
            'nature',
            'photography',
            'science',
            'travel',
            'development',
        ],
    },
    {
        icon: 'Compass',
        name: 'compass',
        tags: [
            'direction',
            'north',
            'east',
            'south',
            'west',
            'safari',
            'browser',
        ],
        categories: [
            'navigation',
            'travel',
        ],
    },
    {
        icon: 'Dumbbell',
        name: 'dumbbell',
        tags: [
            'barbell',
            'weight',
            'workout',
            'gym',
        ],
        categories: [
            'navigation',
            'sports',
        ],
    },
    {
        icon: 'Earth',
        name: 'earth',
        tags: [
            'world',
            'browser',
            'language',
            'translate',
            'globe',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'FerrisWheel',
        name: 'ferris-wheel',
        tags: [
            'big wheel',
            'daisy wheel',
            'observation',
            'attraction',
            'entertainment',
            'amusement park',
            'theme park',
            'funfair',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'Footprints',
        name: 'footprints',
        tags: [
            'steps',
            'walking',
            'foot',
            'feet',
            'trail',
            'shoe',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'Gavel',
        name: 'gavel',
        tags: [
            'hammer',
            'mallet',
        ],
        categories: [
            'navigation',
            'tools',
        ],
    },
    {
        icon: 'Globe',
        name: 'globe',
        tags: [
            'world',
            'browser',
            'language',
            'translate',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'LocateFixed',
        name: 'locate-fixed',
        tags: [
            'map',
            'gps',
            'location',
            'cross',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'LocateOff',
        name: 'locate-off',
        tags: [
            'map',
            'gps',
            'location',
            'cross',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'Locate',
        name: 'locate',
        tags: [
            'map',
            'gps',
            'location',
            'cross',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'LocationEdit',
        name: 'location-edit',
        tags: [
            'location',
            'waypoint',
            'marker',
            'drop',
            'edit',
        ],
        categories: [
            'navigation',
            'travel',
            'account',
        ],
    },
    {
        icon: 'MapPinCheckInside',
        name: 'map-pin-check-inside',
        tags: [
            'location',
            'waypoint',
            'marker',
            'drop',
            'done',
            'tick',
            'complete',
            'task',
            'added',
        ],
        categories: [
            'navigation',
            'travel',
            'account',
        ],
    },
    {
        icon: 'MapPinCheck',
        name: 'map-pin-check',
        tags: [
            'location',
            'waypoint',
            'marker',
            'drop',
            'done',
            'tick',
            'complete',
            'task',
            'added',
        ],
        categories: [
            'navigation',
            'travel',
            'account',
        ],
    },
    {
        icon: 'MapPinHouse',
        name: 'map-pin-house',
        tags: [
            'location',
            'waypoint',
            'marker',
            'drop',
            'home',
            'living',
            'building',
            'residence',
            'architecture',
            'address',
            'poi',
            'real estate',
            'property',
            'navigation',
            'destination',
            'geolocation',
            'place',
            'landmark',
        ],
        categories: [
            'navigation',
            'travel',
            'account',
        ],
    },
    {
        icon: 'MapPinMinusInside',
        name: 'map-pin-minus-inside',
        tags: [
            'location',
            'waypoint',
            'marker',
            'drop',
            'delete',
            'remove',
            'erase',
        ],
        categories: [
            'navigation',
            'travel',
            'account',
        ],
    },
    {
        icon: 'MapPinMinus',
        name: 'map-pin-minus',
        tags: [
            'location',
            'waypoint',
            'marker',
            'drop',
            'delete',
            'remove',
            'erase',
        ],
        categories: [
            'navigation',
            'travel',
            'account',
        ],
    },
    {
        icon: 'MapPinOff',
        name: 'map-pin-off',
        tags: [
            'location',
            'waypoint',
            'marker',
            'remove',
        ],
        categories: [
            'navigation',
            'travel',
        ],
    },
    {
        icon: 'MapPinPlusInside',
        name: 'map-pin-plus-inside',
        tags: [
            'location',
            'waypoint',
            'marker',
            'drop',
            'add',
            'create',
            'new',
        ],
        categories: [
            'navigation',
            'travel',
            'account',
        ],
    },
    {
        icon: 'MapPinPlus',
        name: 'map-pin-plus',
        tags: [
            'location',
            'waypoint',
            'marker',
            'drop',
            'add',
            'create',
            'new',
        ],
        categories: [
            'navigation',
            'travel',
            'account',
        ],
    },
    {
        icon: 'MapPinXInside',
        name: 'map-pin-x-inside',
        tags: [
            'location',
            'waypoint',
            'marker',
            'drop',
            'delete',
            'remove',
            'erase',
        ],
        categories: [
            'navigation',
            'travel',
            'account',
        ],
    },
    {
        icon: 'MapPinX',
        name: 'map-pin-x',
        tags: [
            'location',
            'waypoint',
            'marker',
            'drop',
            'delete',
            'remove',
            'erase',
        ],
        categories: [
            'navigation',
            'travel',
            'account',
        ],
    },
    {
        icon: 'MapPin',
        name: 'map-pin',
        tags: [
            'location',
            'waypoint',
            'marker',
            'drop',
        ],
        categories: [
            'navigation',
            'travel',
            'account',
        ],
    },
    {
        icon: 'MapPinned',
        name: 'map-pinned',
        tags: [
            'location',
            'waypoint',
            'marker',
            'drop',
        ],
        categories: [
            'navigation',
            'travel',
            'account',
        ],
    },
    {
        icon: 'MapPlus',
        name: 'map-plus',
        tags: [
            'location',
            'navigation',
            'travel',
            'new',
            'add',
            'create',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'Navigation2Off',
        name: 'navigation-2-off',
        tags: [
            'location',
            'travel',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'Navigation2',
        name: 'navigation-2',
        tags: [
            'location',
            'travel',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'NavigationOff',
        name: 'navigation-off',
        tags: [
            'location',
            'travel',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'Navigation',
        name: 'navigation',
        tags: [
            'location',
            'travel',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'PinOff',
        name: 'pin-off',
        tags: [
            'unpin',
            'map',
            'unlock',
            'unfix',
            'unsave',
            'remove',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'Pin',
        name: 'pin',
        tags: [
            'save',
            'map',
            'lock',
            'fix',
        ],
        categories: [
            'navigation',
            'account',
        ],
    },
    {
        icon: 'Radar',
        name: 'radar',
        tags: [
            'scan',
            'sonar',
            'detect',
            'find',
            'locate',
        ],
        categories: [
            'navigation',
            'security',
            'communication',
        ],
    },
    {
        icon: 'RollerCoaster',
        name: 'roller-coaster',
        tags: [
            'attraction',
            'entertainment',
            'amusement park',
            'theme park',
            'funfair',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'RouteOff',
        name: 'route-off',
        tags: [
            'path',
            'journey',
            'planner',
            'points',
            'stops',
            'stations',
            'reset',
            'clear',
            'cancelled',
            'closed',
            'blocked',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'Route',
        name: 'route',
        tags: [
            'path',
            'journey',
            'planner',
            'points',
            'stops',
            'stations',
        ],
        categories: [
            'navigation',
        ],
    },
    {
        icon: 'Scale',
        name: 'scale',
        tags: [
            'balance',
            'legal',
            'license',
            'right',
            'rule',
            'law',
        ],
        categories: [
            'navigation',
        ],
    },
];
export default icons;
