// Icons with primary category: science
const icons = [
    {
        icon: 'Atom',
        name: 'atom',
        tags: [
            'atomic',
            'nuclear',
            'physics',
            'particle',
            'element',
            'molecule',
            'electricity',
            'energy',
            'chemistry',
        ],
        categories: [
            'science',
        ],
    },
    {
        icon: 'Beaker',
        name: 'beaker',
        tags: [
            'cup',
            'lab',
            'chemistry',
            'experiment',
            'test',
        ],
        categories: [
            'science',
            'gaming',
        ],
    },
    {
        icon: 'Biohazard',
        name: 'biohazard',
        tags: [
            'fallout',
            'waste',
            'biology',
            'chemistry',
            'chemical',
            'element',
        ],
        categories: [
            'science',
        ],
    },
    {
        icon: 'BrainCircuit',
        name: 'brain-circuit',
        tags: [
            'mind',
            'intellect',
            'artificial intelligence',
            'ai',
            'deep learning',
            'machine learning',
            'computing',
        ],
        categories: [
            'science',
            'development',
        ],
    },
    {
        icon: 'BrainCog',
        name: 'brain-cog',
        tags: [
            'mind',
            'intellect',
            'artificial intelligence',
            'ai',
            'deep learning',
            'machine learning',
            'computing',
        ],
        categories: [
            'science',
            'development',
        ],
    },
    {
        icon: 'CircuitBoard',
        name: 'circuit-board',
        tags: [
            'computing',
            'electricity',
            'electronics',
        ],
        categories: [
            'science',
            'development',
        ],
    },
    {
        icon: 'Eclipse',
        name: 'eclipse',
        tags: [
            'lunar',
            'solar',
            'crescent moon',
            'sun',
            'earth',
            'day',
            'night',
            'planet',
            'space',
            'mode',
            'dark',
            'light',
            'toggle',
            'switch',
            'color',
            'css',
            'styles',
            'display',
            'accessibility',
            'contrast',
            'brightness',
            'blend',
            'shade',
        ],
        categories: [
            'science',
            'design',
            'development',
            'accessibility',
            'photography',
        ],
    },
    {
        icon: 'FlaskConicalOff',
        name: 'flask-conical-off',
        tags: [
            'beaker',
            'erlenmeyer',
            'non toxic',
            'lab',
            'chemistry',
            'experiment',
            'test',
        ],
        categories: [
            'science',
            'gaming',
        ],
    },
    {
        icon: 'FlaskConical',
        name: 'flask-conical',
        tags: [
            'beaker',
            'erlenmeyer',
            'lab',
            'chemistry',
            'experiment',
            'test',
        ],
        categories: [
            'science',
            'gaming',
        ],
    },
    {
        icon: 'FlaskRound',
        name: 'flask-round',
        tags: [
            'beaker',
            'lab',
            'chemistry',
            'experiment',
            'test',
        ],
        categories: [
            'science',
            'gaming',
        ],
    },
    {
        icon: 'Microscope',
        name: 'microscope',
        tags: [
            'medical',
            'education',
            'science',
            'imaging',
            'research',
        ],
        categories: [
            'science',
            'medical',
        ],
    },
    {
        icon: 'Orbit',
        name: 'orbit',
        tags: [
            'planet',
            'space',
            'physics',
            'satellites',
            'moons',
        ],
        categories: [
            'science',
        ],
    },
    {
        icon: 'Radiation',
        name: 'radiation',
        tags: [
            'radioactive',
            'nuclear',
            'fallout',
            'waste',
            'atomic',
            'physics',
            'particle',
            'element',
            'molecule',
        ],
        categories: [
            'science',
        ],
    },
    {
        icon: 'Stethoscope',
        name: 'stethoscope',
        tags: [
            'phonendoscope',
            'medical',
            'heart',
            'lungs',
            'sound',
        ],
        categories: [
            'science',
            'medical',
        ],
    },
    {
        icon: 'Syringe',
        name: 'syringe',
        tags: [
            'medicine',
            'medical',
            'needle',
            'pump',
            'plunger',
            'nozzle',
            'blood',
        ],
        categories: [
            'science',
            'medical',
        ],
    },
    {
        icon: 'Telescope',
        name: 'telescope',
        tags: [
            'astronomy',
            'space',
            'discovery',
            'exploration',
            'explore',
            'vision',
            'perspective',
            'focus',
            'stargazing',
            'observe',
            'view',
        ],
        categories: [
            'science',
            'development',
            'tools',
        ],
    },
    {
        icon: 'TestTubeDiagonal',
        name: 'test-tube-diagonal',
        tags: [
            'tube',
            'vial',
            'phial',
            'flask',
            'ampoule',
            'ampule',
            'lab',
            'chemistry',
            'experiment',
            'test',
        ],
        categories: [
            'science',
        ],
    },
    {
        icon: 'TestTube',
        name: 'test-tube',
        tags: [
            'tube',
            'vial',
            'phial',
            'flask',
            'ampoule',
            'ampule',
            'lab',
            'chemistry',
            'experiment',
            'test',
        ],
        categories: [
            'science',
        ],
    },
    {
        icon: 'TestTubes',
        name: 'test-tubes',
        tags: [
            'tubes',
            'vials',
            'phials',
            'flasks',
            'ampoules',
            'ampules',
            'lab',
            'chemistry',
            'experiment',
            'test',
        ],
        categories: [
            'science',
        ],
    },
];
export default icons;
