// Icons with primary category: security
const icons = [
    {
        icon: 'Bomb',
        name: 'bomb',
        tags: [
            'fatal',
            'error',
            'crash',
            'blockbuster',
            'mine',
            'explosion',
            'explode',
            'explosive',
        ],
        categories: [
            'security',
            'tools',
        ],
    },
    {
        icon: 'BrickWallFire',
        name: 'brick-wall-fire',
        tags: [
            'firewall',
            'security',
            'bricks',
            'mortar',
            'cement',
            'materials',
            'construction',
            'builder',
            'labourer',
            'quantity surveyor',
            'blocks',
            'stone',
            'campfire',
            'camping',
            'wilderness',
            'outdoors',
            'lit',
            'warmth',
            'wood',
            'twigs',
            'sticks',
        ],
        categories: [
            'security',
            'home',
            'connectivity',
        ],
    },
    {
        icon: 'Cctv',
        name: 'cctv',
        tags: [
            'camera',
            'surveillance',
            'recording',
            'film',
            'videotape',
            'crime',
            'watching',
        ],
        categories: [
            'security',
            'devices',
            'communication',
            'connectivity',
            'photography',
        ],
    },
    {
        icon: 'EarthLock',
        name: 'earth-lock',
        tags: [
            'vpn',
            'private',
            'privacy',
            'network',
            'world',
            'browser',
            'security',
            'encryption',
            'protection',
            'connection',
        ],
        categories: [
            'security',
            'development',
            'devices',
        ],
    },
    {
        icon: 'GlobeLock',
        name: 'globe-lock',
        tags: [
            'vpn',
            'private',
            'privacy',
            'network',
            'world',
            'browser',
            'security',
            'encryption',
            'protection',
            'connection',
        ],
        categories: [
            'security',
            'development',
            'devices',
        ],
    },
    {
        icon: 'IdCard',
        name: 'id-card',
        tags: [
            'card',
            'badge',
            'identity',
            'authentication',
            'secure',
        ],
        categories: [
            'security',
            'account',
        ],
    },
    {
        icon: 'KeyRound',
        name: 'key-round',
        tags: [
            'password',
            'login',
            'authentication',
            'secure',
            'unlock',
        ],
        categories: [
            'security',
            'account',
        ],
    },
    {
        icon: 'KeySquare',
        name: 'key-square',
        tags: [
            'password',
            'login',
            'authentication',
            'secure',
            'unlock',
            'car key',
        ],
        categories: [
            'security',
            'account',
        ],
    },
    {
        icon: 'Key',
        name: 'key',
        tags: [
            'password',
            'login',
            'authentication',
            'secure',
            'unlock',
            'keychain',
            'key ring',
            'fob',
        ],
        categories: [
            'security',
            'account',
        ],
    },
    {
        icon: 'LockKeyholeOpen',
        name: 'lock-keyhole-open',
        tags: [
            'security',
        ],
        categories: [
            'security',
        ],
    },
    {
        icon: 'LockKeyhole',
        name: 'lock-keyhole',
        tags: [
            'security',
            'password',
            'secure',
            'admin',
        ],
        categories: [
            'security',
        ],
    },
    {
        icon: 'LockOpen',
        name: 'lock-open',
        tags: [
            'security',
        ],
        categories: [
            'security',
        ],
    },
    {
        icon: 'Lock',
        name: 'lock',
        tags: [
            'security',
            'password',
            'secure',
            'admin',
        ],
        categories: [
            'security',
        ],
    },
    {
        icon: 'RotateCcwKey',
        name: 'rotate-ccw-key',
        tags: [
            'password',
            'key',
            'refresh',
            'change',
        ],
        categories: [
            'security',
            'account',
        ],
    },
    {
        icon: 'Vault',
        name: 'vault',
        tags: [
            'safe',
            'lockbox',
            'deposit',
            'locker',
            'coffer',
            'strongbox',
            'safety',
            'secure',
            'storage',
            'valuables',
            'bank',
        ],
        categories: [
            'security',
            'travel',
            'home',
        ],
    },
    {
        icon: 'Waypoints',
        name: 'waypoints',
        tags: [
            'indirection',
            'vpn',
            'virtual private network',
            'proxy',
            'connections',
            'bounce',
            'reroute',
            'path',
            'journey',
            'planner',
            'stops',
            'stations',
            'shared',
            'spread',
            'viral',
        ],
        categories: [
            'security',
            'account',
            'navigation',
            'development',
            'social',
        ],
    },
];
export default icons;
