// Icons with primary category: shapes
const icons = [
    {
        icon: 'Box',
        name: 'box',
        tags: [
            'cube',
            'package',
            'container',
            'storage',
            'geometry',
            '3d',
            'isometric',
        ],
        categories: [
            'shapes',
            'gaming',
            'development',
            'math',
        ],
    },
    {
        icon: 'Boxes',
        name: 'boxes',
        tags: [
            'cubes',
            'packages',
            'parts',
            'group',
            'units',
            'collection',
            'cluster',
            'geometry',
        ],
        categories: [
            'shapes',
            'gaming',
            'development',
        ],
    },
    {
        icon: 'CircleOff',
        name: 'circle-off',
        tags: [
            'diameter',
            'zero',
            'Ø',
            'nothing',
            'null',
            'void',
            'cancel',
            'ban',
            'no',
            'stop',
            'forbidden',
            'prohibited',
            'error',
            'incorrect',
            'mistake',
            'wrong',
            'failure',
        ],
        categories: [
            'shapes',
        ],
    },
    {
        icon: 'CircleSlash2',
        name: 'circle-slash-2',
        tags: [
            'diameter',
            'zero',
            'ø',
            'nothing',
            'null',
            'void',
            'ban',
            'math',
            'divide',
            'division',
            'half',
            'split',
            '/',
            'average',
            'avg',
            'mean',
            'median',
            'normal',
        ],
        categories: [
            'shapes',
            'math',
            'development',
        ],
    },
    {
        icon: 'CircleSmall',
        name: 'circle-small',
        tags: [
            'shape',
            'bullet',
            'gender',
            'genderless',
        ],
        categories: [
            'shapes',
            'medical',
        ],
    },
    {
        icon: 'Circle',
        name: 'circle',
        tags: [
            'off',
            'zero',
            'record',
            'shape',
        ],
        categories: [
            'shapes',
        ],
    },
    {
        icon: 'Club',
        name: 'club',
        tags: [
            'shape',
            'suit',
            'playing',
            'cards',
        ],
        categories: [
            'shapes',
            'gaming',
        ],
    },
    {
        icon: 'Cone',
        name: 'cone',
        tags: [
            'conical',
            'triangle',
            'triangular',
            'geometry',
            'filter',
            'funnel',
            'hopper',
            'spotlight',
            'searchlight',
        ],
        categories: [
            'shapes',
            'math',
        ],
    },
    {
        icon: 'Cross',
        name: 'cross',
        tags: [
            'healthcare',
            'first aid',
        ],
        categories: [
            'shapes',
        ],
    },
    {
        icon: 'Cuboid',
        name: 'cuboid',
        tags: [
            'brick',
            'block',
            'container',
            'storage',
            'geometry',
            'rectangular',
            'hexahedron',
        ],
        categories: [
            'shapes',
            'math',
            'buildings',
        ],
    },
    {
        icon: 'Cylinder',
        name: 'cylinder',
        tags: [
            'shape',
            'elliptical',
            'geometry',
            'container',
            'storage',
            'tin',
            'pot',
        ],
        categories: [
            'shapes',
            'design',
            'math',
        ],
    },
    {
        icon: 'Diameter',
        name: 'diameter',
        tags: [
            'shape',
            'circle',
            'geometry',
            'trigonometry',
            'width',
            'height',
            'size',
            'calculate',
            'measure',
        ],
        categories: [
            'shapes',
            'math',
            'design',
            'tools',
        ],
    },
    {
        icon: 'Diamond',
        name: 'diamond',
        tags: [
            'square',
            'rectangle',
            'oblique',
            'rhombus',
            'shape',
            'suit',
            'playing',
            'cards',
        ],
        categories: [
            'shapes',
            'gaming',
        ],
    },
    {
        icon: 'Dot',
        name: 'dot',
        tags: [
            'interpunct',
            'interpoint',
            'middot',
            'step',
            'punctuation',
            'period',
            'full stop',
            'end',
            'finish',
            'final',
            'characters',
            'font',
            'typography',
            'type',
            'center',
            '.',
        ],
        categories: [
            'shapes',
            'text',
        ],
    },
    {
        icon: 'Hexagon',
        name: 'hexagon',
        tags: [
            'shape',
            'node.js',
            'logo',
        ],
        categories: [
            'shapes',
            'brands',
            'development',
        ],
    },
    {
        icon: 'Octagon',
        name: 'octagon',
        tags: [
            'stop',
            'shape',
        ],
        categories: [
            'shapes',
        ],
    },
    {
        icon: 'Pentagon',
        name: 'pentagon',
        tags: [
            'shape',
        ],
        categories: [
            'shapes',
        ],
    },
    {
        icon: 'Pyramid',
        name: 'pyramid',
        tags: [
            'prism',
            'triangle',
            'triangular',
            'hierarchy',
            'structure',
            'geometry',
            'ancient',
            'egyptian',
            'landmark',
            'tourism',
        ],
        categories: [
            'shapes',
            'math',
            'travel',
        ],
    },
    {
        icon: 'Radius',
        name: 'radius',
        tags: [
            'shape',
            'circle',
            'geometry',
            'trigonometry',
            'radii',
            'calculate',
            'measure',
            'size',
        ],
        categories: [
            'shapes',
            'math',
            'design',
            'tools',
        ],
    },
    {
        icon: 'RectangleHorizontal',
        name: 'rectangle-horizontal',
        tags: [
            'rectangle',
            'aspect ratio',
            '16:9',
            'horizontal',
            'shape',
        ],
        categories: [
            'shapes',
            'design',
        ],
    },
    {
        icon: 'RectangleVertical',
        name: 'rectangle-vertical',
        tags: [
            'rectangle',
            'aspect ratio',
            '9:16',
            'vertical',
            'shape',
        ],
        categories: [
            'shapes',
            'design',
        ],
    },
    {
        icon: 'Shapes',
        name: 'shapes',
        tags: [
            'triangle',
            'equilateral',
            'square',
            'circle',
            'classification',
            'different',
            'collection',
            'toy',
            'blocks',
            'learning',
        ],
        categories: [
            'shapes',
            'gaming',
        ],
    },
    {
        icon: 'Spade',
        name: 'spade',
        tags: [
            'shape',
            'suit',
            'playing',
            'cards',
        ],
        categories: [
            'shapes',
            'gaming',
        ],
    },
    {
        icon: 'Sparkle',
        name: 'sparkle',
        tags: [
            'star',
            'effect',
            'filter',
            'night',
            'magic',
            'shiny',
            'glitter',
            'twinkle',
            'celebration',
        ],
        categories: [
            'shapes',
        ],
    },
    {
        icon: 'Square',
        name: 'square',
        tags: [
            'rectangle',
            'aspect ratio',
            '1:1',
            'shape',
        ],
        categories: [
            'shapes',
        ],
    },
    {
        icon: 'Squircle',
        name: 'squircle',
        tags: [
            'shape',
        ],
        categories: [
            'shapes',
        ],
    },
    {
        icon: 'Tangent',
        name: 'tangent',
        tags: [
            'tangential',
            'shape',
            'circle',
            'geometry',
            'trigonometry',
            'bezier curve',
        ],
        categories: [
            'shapes',
            'math',
            'design',
            'tools',
        ],
    },
    {
        icon: 'Torus',
        name: 'torus',
        tags: [
            'donut',
            'doughnut',
            'ring',
            'hollow',
            '3d',
            'fast food',
            'junk food',
            'snack',
            'treat',
            'sweet',
            'sugar',
            'dessert',
        ],
        categories: [
            'shapes',
            'design',
            'tools',
            'food-beverage',
        ],
    },
    {
        icon: 'TriangleDashed',
        name: 'triangle-dashed',
        tags: [
            'equilateral',
            'delta',
            'shape',
            'pyramid',
            'hierarchy',
            'dashed',
        ],
        categories: [
            'shapes',
        ],
    },
    {
        icon: 'TriangleRight',
        name: 'triangle-right',
        tags: [
            'volume',
            'controls',
            'controller',
            'tv remote',
            'geometry',
            'delta',
            'ramp',
            'slope',
            'incline',
            'increase',
        ],
        categories: [
            'shapes',
            'math',
        ],
    },
    {
        icon: 'Triangle',
        name: 'triangle',
        tags: [
            'equilateral',
            'delta',
            'shape',
            'pyramid',
            'hierarchy',
        ],
        categories: [
            'shapes',
        ],
    },
    {
        icon: 'Ungroup',
        name: 'ungroup',
        tags: [
            'cubes',
            'packages',
            'parts',
            'units',
            'collection',
            'cluster',
            'separate',
        ],
        categories: [
            'shapes',
            'files',
        ],
    },
];
export default icons;
