// Icons with primary category: shopping
const icons = [
    {
        icon: 'BadgeCent',
        name: 'badge-cent',
        tags: [
            'discount',
            'offer',
            'sale',
            'voucher',
            'tag',
            'monetization',
            'marketing',
            'finance',
            'financial',
            'exchange',
            'transaction',
            'payment',
            'cents',
            'dollar',
            'usd',
            '$',
            '¢',
        ],
        categories: [
            'shopping',
            'finance',
        ],
    },
    {
        icon: 'BadgeDollarSign',
        name: 'badge-dollar-sign',
        tags: [
            'discount',
            'offer',
            'sale',
            'voucher',
            'tag',
            'monetization',
            'marketing',
            'finance',
            'financial',
            'exchange',
            'transaction',
            'payment',
            'usd',
            '$',
        ],
        categories: [
            'shopping',
            'finance',
        ],
    },
    {
        icon: 'BadgeEuro',
        name: 'badge-euro',
        tags: [
            'discount',
            'offer',
            'sale',
            'voucher',
            'tag',
            'monetization',
            'marketing',
            'finance',
            'financial',
            'exchange',
            'transaction',
            'payment',
            '€',
        ],
        categories: [
            'shopping',
            'finance',
        ],
    },
    {
        icon: 'BadgeIndianRupee',
        name: 'badge-indian-rupee',
        tags: [
            'discount',
            'offer',
            'sale',
            'voucher',
            'tag',
            'monetization',
            'marketing',
            'finance',
            'financial',
            'exchange',
            'transaction',
            'payment',
            'inr',
            '₹',
        ],
        categories: [
            'shopping',
            'finance',
        ],
    },
    {
        icon: 'BadgeJapaneseYen',
        name: 'badge-japanese-yen',
        tags: [
            'discount',
            'offer',
            'sale',
            'voucher',
            'tag',
            'monetization',
            'marketing',
            'finance',
            'financial',
            'exchange',
            'transaction',
            'payment',
            'jpy',
            '¥',
        ],
        categories: [
            'shopping',
            'finance',
        ],
    },
    {
        icon: 'BadgePoundSterling',
        name: 'badge-pound-sterling',
        tags: [
            'discount',
            'offer',
            'sale',
            'voucher',
            'tag',
            'monetization',
            'marketing',
            'finance',
            'financial',
            'exchange',
            'transaction',
            'payment',
            'british',
            'gbp',
            '£',
        ],
        categories: [
            'shopping',
            'finance',
        ],
    },
    {
        icon: 'BadgeRussianRuble',
        name: 'badge-russian-ruble',
        tags: [
            'discount',
            'offer',
            'sale',
            'voucher',
            'tag',
            'monetization',
            'marketing',
            'finance',
            'financial',
            'exchange',
            'transaction',
            'payment',
            'rub',
            '₽',
        ],
        categories: [
            'shopping',
            'finance',
        ],
    },
    {
        icon: 'BadgeSwissFranc',
        name: 'badge-swiss-franc',
        tags: [
            'discount',
            'offer',
            'sale',
            'voucher',
            'tag',
            'monetization',
            'marketing',
            'finance',
            'financial',
            'exchange',
            'transaction',
            'payment',
            'chf',
            '₣',
        ],
        categories: [
            'shopping',
            'finance',
        ],
    },
    {
        icon: 'Barcode',
        name: 'barcode',
        tags: [
            'scan',
            'checkout',
            'till',
            'cart',
            'transaction',
            'purchase',
            'buy',
            'product',
            'packaging',
            'retail',
            'consumer',
        ],
        categories: [
            'shopping',
        ],
    },
    {
        icon: 'ScanBarcode',
        name: 'scan-barcode',
        tags: [
            'checkout',
            'till',
            'cart',
            'transaction',
            'purchase',
            'buy',
            'product',
            'packaging',
            'retail',
            'consumer',
        ],
        categories: [
            'shopping',
            'devices',
        ],
    },
    {
        icon: 'Shirt',
        name: 'shirt',
        tags: [
            't-shirt',
            'shopping',
            'store',
            'clothing',
            'clothes',
        ],
        categories: [
            'shopping',
        ],
    },
    {
        icon: 'ShoppingBag',
        name: 'shopping-bag',
        tags: [
            'ecommerce',
            'cart',
            'purchase',
            'store',
        ],
        categories: [
            'shopping',
        ],
    },
    {
        icon: 'ShoppingBasket',
        name: 'shopping-basket',
        tags: [
            'cart',
            'e-commerce',
            'store',
            'purchase',
            'products',
            'items',
            'ingredients',
        ],
        categories: [
            'shopping',
        ],
    },
    {
        icon: 'ShoppingCart',
        name: 'shopping-cart',
        tags: [
            'trolley',
            'cart',
            'basket',
            'e-commerce',
            'store',
            'purchase',
            'products',
            'items',
            'ingredients',
        ],
        categories: [
            'shopping',
        ],
    },
];
export default icons;
