// Icons with primary category: social
const icons = [
    {
        icon: 'BadgeCheck',
        name: 'badge-check',
        tags: [
            'verified',
            'check',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'BadgeMinus',
        name: 'badge-minus',
        tags: [
            'verified',
            'unverified',
            'delete',
            'remove',
            'erase',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'BadgePercent',
        name: 'badge-percent',
        tags: [
            'verified',
            'unverified',
            'sale',
            'discount',
            'offer',
            'marketing',
            'sticker',
            'price tag',
        ],
        categories: [
            'social',
            'finance',
            'shopping',
            'math',
        ],
    },
    {
        icon: 'BadgePlus',
        name: 'badge-plus',
        tags: [
            'verified',
            'unverified',
            'add',
            'create',
            'new',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'BadgeX',
        name: 'badge-x',
        tags: [
            'verified',
            'unverified',
            'lost',
            'delete',
            'remove',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'BookHeart',
        name: 'book-heart',
        tags: [
            'diary',
            'romance',
            'novel',
            'journal',
            'entry',
            'entries',
            'personal',
            'private',
            'secret',
            'crush',
            'like',
            'love',
            'emotion',
            'feminine',
            'girls',
            'teens',
            'teenager',
            'therapy',
            'theraputic',
            'therapist',
            'planner',
            'organizer',
            'organiser',
            'notes',
            'notepad',
            'stationery',
            'sketchbook',
            'writing',
            'written',
            'reading',
            'favorite',
            'favourite',
            'high school',
        ],
        categories: [
            'social',
            'text',
            'gaming',
        ],
    },
    {
        icon: 'CirclePercent',
        name: 'circle-percent',
        tags: [
            'verified',
            'unverified',
            'sale',
            'discount',
            'offer',
            'marketing',
            'sticker',
            'price tag',
        ],
        categories: [
            'social',
            'finance',
            'shopping',
            'math',
        ],
    },
    {
        icon: 'DiamondPercent',
        name: 'diamond-percent',
        tags: [
            'verified',
            'unverified',
            'sale',
            'discount',
            'offer',
            'marketing',
            'sticker',
            'price tag',
        ],
        categories: [
            'social',
            'finance',
            'shopping',
            'math',
        ],
    },
    {
        icon: 'Facebook',
        name: 'facebook',
        tags: [
            'logo',
            'social',
        ],
        categories: [
            'social',
            'brands',
        ],
    },
    {
        icon: 'HandHeart',
        name: 'hand-heart',
        tags: [
            'love',
            'like',
            'emotion',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'HeartOff',
        name: 'heart-off',
        tags: [
            'unlike',
            'dislike',
            'hate',
            'emotion',
        ],
        categories: [
            'social',
            'multimedia',
        ],
    },
    {
        icon: 'Linkedin',
        name: 'linkedin',
        tags: [
            'logo',
            'social media',
            'social',
        ],
        categories: [
            'social',
            'brands',
        ],
    },
    {
        icon: 'MessageCircleDashed',
        name: 'message-circle-dashed',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'draft',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageCircleHeart',
        name: 'message-circle-heart',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'positive',
            'like',
            'love',
            'interest',
            'valentine',
            'dating',
            'date',
            'speech bubble',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageCircleMore',
        name: 'message-circle-more',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'typing',
            'writing',
            'responding',
            'ellipsis',
            'etc',
            'et cetera',
            '...',
            '…',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageCircleOff',
        name: 'message-circle-off',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'clear',
            'close',
            'delete',
            'remove',
            'cancel',
            'silence',
            'mute',
            'moderate',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageCirclePlus',
        name: 'message-circle-plus',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'add',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageCircleQuestion',
        name: 'message-circle-question',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'help',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageCircleReply',
        name: 'message-circle-reply',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'reply',
            'response',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageCircleWarning',
        name: 'message-circle-warning',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'report',
            'abuse',
            'offense',
            'alert',
            'danger',
            'caution',
            'protected',
            'exclamation mark',
        ],
        categories: [
            'social',
            'notifications',
        ],
    },
    {
        icon: 'MessageCircle',
        name: 'message-circle',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageSquareDashed',
        name: 'message-square-dashed',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'draft',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageSquareDot',
        name: 'message-square-dot',
        tags: [
            'unread',
            'unresolved',
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
        ],
        categories: [
            'social',
            'notifications',
        ],
    },
    {
        icon: 'MessageSquareHeart',
        name: 'message-square-heart',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'positive',
            'like',
            'love',
            'interest',
            'valentine',
            'dating',
            'date',
            'speech bubble',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageSquareLock',
        name: 'message-square-lock',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'secure',
            'encrypted',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageSquareMore',
        name: 'message-square-more',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'typing',
            'writing',
            'responding',
            'ellipsis',
            'etc',
            'et cetera',
            '...',
            '…',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageSquareOff',
        name: 'message-square-off',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'clear',
            'close',
            'delete',
            'remove',
            'cancel',
            'silence',
            'mute',
            'moderate',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageSquarePlus',
        name: 'message-square-plus',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'add',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageSquareQuote',
        name: 'message-square-quote',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'blockquote',
            'quotation',
            'indent',
            'reply',
            'response',
        ],
        categories: [
            'social',
            'text',
        ],
    },
    {
        icon: 'MessageSquareReply',
        name: 'message-square-reply',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'reply',
            'response',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageSquareShare',
        name: 'message-square-share',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'network',
            'forward',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageSquareText',
        name: 'message-square-text',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageSquareWarning',
        name: 'message-square-warning',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'report',
            'abuse',
            'offense',
            'alert',
            'danger',
            'caution',
            'protected',
            'exclamation mark',
        ],
        categories: [
            'social',
            'notifications',
        ],
    },
    {
        icon: 'MessageSquareX',
        name: 'message-square-x',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
            'clear',
            'close',
            'delete',
            'remove',
            'cancel',
            'silence',
            'mute',
            'moderate',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessageSquare',
        name: 'message-square',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubble',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'MessagesSquare',
        name: 'messages-square',
        tags: [
            'comment',
            'chat',
            'conversation',
            'dialog',
            'feedback',
            'speech bubbles',
            'copy',
            'multiple',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'Ribbon',
        name: 'ribbon',
        tags: [
            'awareness',
            'strip',
            'band',
            'tape',
            'strap',
            'cordon',
        ],
        categories: [
            'social',
            'medical',
            'emoji',
        ],
    },
    {
        icon: 'SquarePercent',
        name: 'square-percent',
        tags: [
            'verified',
            'unverified',
            'sale',
            'discount',
            'offer',
            'marketing',
            'sticker',
            'price tag',
        ],
        categories: [
            'social',
            'finance',
            'shopping',
            'math',
        ],
    },
    {
        icon: 'StarHalf',
        name: 'star-half',
        tags: [
            'bookmark',
            'favorite',
            'like',
            'review',
            'rating',
        ],
        categories: [
            'social',
            'multimedia',
        ],
    },
    {
        icon: 'Sticker',
        name: 'sticker',
        tags: [
            'reaction',
            'emotion',
            'smile',
            'happy',
            'feedback',
        ],
        categories: [
            'social',
        ],
    },
    {
        icon: 'Vote',
        name: 'vote',
        tags: [
            'vote',
            'poll',
            'ballot',
            'political',
            'social',
            'check',
            'tick',
        ],
        categories: [
            'social',
        ],
    },
];
export default icons;
