// Icons with primary category: sports
const icons = [
    {
        icon: 'Medal',
        name: 'medal',
        tags: [
            'prize',
            'sports',
            'winner',
            'trophy',
            'award',
            'achievement',
        ],
        categories: [
            'sports',
            'gaming',
        ],
    },
    {
        icon: 'Trophy',
        name: 'trophy',
        tags: [
            'prize',
            'sports',
            'winner',
            'achievement',
            'award',
            'champion',
            'celebration',
            'victory',
        ],
        categories: [
            'sports',
            'gaming',
        ],
    },
    {
        icon: 'Volleyball',
        name: 'volleyball',
        tags: [
            'beach',
            'sand',
            'net',
            'holiday',
            'vacation',
            'summer',
            'soccer',
            'football',
            'futbol',
            'kick',
            'pitch',
            'goal',
            'score',
            'bounce',
            'leather',
            'wool',
            'yarn',
            'knitting',
            'sewing',
            'thread',
            'embroidery',
            'textile',
        ],
        categories: [
            'sports',
            'gaming',
            'travel',
        ],
    },
    {
        icon: 'WavesLadder',
        name: 'waves-ladder',
        tags: [
            'swimming',
            'water',
            'pool',
            'lifeguard',
            'ocean',
            '🌊',
            '🏊‍♂️',
            '🏊‍♀️',
            '🏊',
            '🥽',
        ],
        categories: [
            'sports',
            'home',
        ],
    },
];
export default icons;
