// Icons with primary category: text
const icons = [
    {
        icon: 'AArrowDown',
        name: 'a-arrow-down',
        tags: [
            'letter',
            'font size',
            'text',
            'formatting',
            'smaller',
        ],
        categories: [
            'text',
            'design',
        ],
    },
    {
        icon: 'AArrowUp',
        name: 'a-arrow-up',
        tags: [
            'letter',
            'font size',
            'text',
            'formatting',
            'larger',
            'bigger',
        ],
        categories: [
            'text',
            'design',
        ],
    },
    {
        icon: 'ALargeSmall',
        name: 'a-large-small',
        tags: [
            'letter',
            'font size',
            'text',
            'formatting',
        ],
        categories: [
            'text',
            'design',
        ],
    },
    {
        icon: 'AlignCenter',
        name: 'align-center',
        tags: [
            'text',
            'alignment',
            'center',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'AlignJustify',
        name: 'align-justify',
        tags: [
            'text',
            'alignment',
            'justified',
            'menu',
            'list',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'AlignLeft',
        name: 'align-left',
        tags: [
            'text',
            'alignment',
            'left',
            'list',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'AlignRight',
        name: 'align-right',
        tags: [
            'text',
            'alignment',
            'right',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Ampersand',
        name: 'ampersand',
        tags: [
            'and',
            'typography',
            'operator',
            'join',
            'concatenate',
            'code',
            '&',
        ],
        categories: [
            'text',
            'development',
        ],
    },
    {
        icon: 'Ampersands',
        name: 'ampersands',
        tags: [
            'and',
            'operator',
            'then',
            'code',
            '&&',
        ],
        categories: [
            'text',
            'development',
        ],
    },
    {
        icon: 'ArrowDown01',
        name: 'arrow-down-0-1',
        tags: [
            'filter',
            'sort',
            'ascending',
            'descending',
            'increasing',
            'decreasing',
            'rising',
            'falling',
            'numerical',
        ],
        categories: [
            'text',
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'ArrowDown10',
        name: 'arrow-down-1-0',
        tags: [
            'filter',
            'sort',
            'ascending',
            'descending',
            'increasing',
            'decreasing',
            'rising',
            'falling',
            'numerical',
        ],
        categories: [
            'text',
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'ArrowDownAZ',
        name: 'arrow-down-a-z',
        tags: [
            'filter',
            'sort',
            'ascending',
            'descending',
            'increasing',
            'decreasing',
            'rising',
            'falling',
            'alphabetical',
        ],
        categories: [
            'text',
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'ArrowDownNarrowWide',
        name: 'arrow-down-narrow-wide',
        tags: [
            'filter',
            'sort',
            'ascending',
            'descending',
            'increasing',
            'decreasing',
            'rising',
            'falling',
        ],
        categories: [
            'text',
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'ArrowDownWideNarrow',
        name: 'arrow-down-wide-narrow',
        tags: [
            'filter',
            'sort',
            'ascending',
            'descending',
            'increasing',
            'decreasing',
            'rising',
            'falling',
        ],
        categories: [
            'text',
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'ArrowDownZA',
        name: 'arrow-down-z-a',
        tags: [
            'filter',
            'sort',
            'ascending',
            'descending',
            'increasing',
            'decreasing',
            'rising',
            'falling',
            'alphabetical',
            'reverse',
        ],
        categories: [
            'text',
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'ArrowUp01',
        name: 'arrow-up-0-1',
        tags: [
            'filter',
            'sort',
            'ascending',
            'descending',
            'increasing',
            'decreasing',
            'rising',
            'falling',
            'numerical',
        ],
        categories: [
            'text',
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'ArrowUp10',
        name: 'arrow-up-1-0',
        tags: [
            'filter',
            'sort',
            'ascending',
            'descending',
            'increasing',
            'decreasing',
            'rising',
            'falling',
            'numerical',
        ],
        categories: [
            'text',
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'ArrowUpAZ',
        name: 'arrow-up-a-z',
        tags: [
            'filter',
            'sort',
            'ascending',
            'descending',
            'increasing',
            'decreasing',
            'rising',
            'falling',
            'alphabetical',
        ],
        categories: [
            'text',
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'ArrowUpNarrowWide',
        name: 'arrow-up-narrow-wide',
        tags: [
            'filter',
            'sort',
            'ascending',
            'descending',
            'increasing',
            'decreasing',
            'rising',
            'falling',
        ],
        categories: [
            'text',
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'ArrowUpWideNarrow',
        name: 'arrow-up-wide-narrow',
        tags: [
            'filter',
            'sort',
            'ascending',
            'descending',
            'increasing',
            'decreasing',
            'rising',
            'falling',
        ],
        categories: [
            'text',
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'ArrowUpZA',
        name: 'arrow-up-z-a',
        tags: [
            'filter',
            'sort',
            'ascending',
            'descending',
            'increasing',
            'decreasing',
            'rising',
            'falling',
            'alphabetical',
            'reverse',
        ],
        categories: [
            'text',
            'layout',
            'arrows',
        ],
    },
    {
        icon: 'Asterisk',
        name: 'asterisk',
        tags: [
            'reference',
            'times',
            'multiply',
            'multiplication',
            'operator',
            'code',
            'glob pattern',
            'wildcard',
            '*',
        ],
        categories: [
            'text',
            'math',
            'development',
        ],
    },
    {
        icon: 'AtSign',
        name: 'at-sign',
        tags: [
            'mention',
            'at',
            'email',
            'message',
            '@',
        ],
        categories: [
            'text',
            'account',
        ],
    },
    {
        icon: 'Baseline',
        name: 'baseline',
        tags: [
            'text',
            'format',
            'color',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Binary',
        name: 'binary',
        tags: [
            'code',
            'digits',
            'computer',
            'zero',
            'one',
            'boolean',
        ],
        categories: [
            'text',
            'development',
        ],
    },
    {
        icon: 'Bold',
        name: 'bold',
        tags: [
            'text',
            'strong',
            'format',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'BookA',
        name: 'book-a',
        tags: [
            'dictionary',
            'define',
            'definition',
            'thesaurus',
            'encyclopedia',
            'encyclopaedia',
            'reading',
            'booklet',
            'magazine',
            'leaflet',
            'pamphlet',
            'tome',
            'library',
            'writing',
            'written',
            'writer',
            'author',
            'story',
            'script',
            'fiction',
            'novel',
            'information',
            'knowledge',
            'education',
            'high school',
            'university',
            'college',
            'academy',
            'student',
            'study',
            'learning',
            'homework',
            'research',
            'language',
            'translate',
            'alphabetical',
            'a-z',
            'ordered',
        ],
        categories: [
            'text',
            'gaming',
        ],
    },
    {
        icon: 'BookCheck',
        name: 'book-check',
        tags: [
            'read',
            'booklet',
            'magazine',
            'leaflet',
            'pamphlet',
            'library',
            'written',
            'authored',
            'published',
            'informed',
            'knowledgeable',
            'educated',
            'schooled',
            'homework',
            'examined',
            'tested',
            'marked',
            'passed',
            'graduated',
            'studied',
            'learned',
            'lesson',
            'researched',
            'documented',
            'revealed',
            'blank',
            'plain language',
            'true',
            'truth',
            'verified',
            'corrected',
            'task',
            'todo',
            'done',
            'completed',
            'finished',
            'ticked',
        ],
        categories: [
            'text',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'BookMarked',
        name: 'book-marked',
        tags: [
            'dictionary',
            'reading',
            'booklet',
            'magazine',
            'leaflet',
            'pamphlet',
            'tome',
            'library',
            'writing',
            'written',
            'writer',
            'author',
            'story',
            'script',
            'fiction',
            'novel',
            'information',
            'knowledge',
            'education',
            'high school',
            'university',
            'college',
            'academy',
            'student',
            'study',
            'learning',
            'homework',
            'research',
            'documentation',
            'saved',
            'later',
            'future',
            'reference',
            'index',
            'code',
            'coding',
            'version control',
            'git',
            'repository',
        ],
        categories: [
            'text',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'BookOpenCheck',
        name: 'book-open-check',
        tags: [
            'read',
            'pages',
            'booklet',
            'magazine',
            'leaflet',
            'pamphlet',
            'library',
            'written',
            'authored',
            'published',
            'informed',
            'knowledgeable',
            'educated',
            'schooled',
            'homework',
            'examined',
            'tested',
            'marked',
            'passed',
            'graduated',
            'studied',
            'learned',
            'lesson',
            'researched',
            'documented',
            'revealed',
            'blank',
            'plain language',
            'true',
            'truth',
            'verified',
            'corrected',
            'task',
            'todo',
            'done',
            'completed',
            'finished',
            'ticked',
        ],
        categories: [
            'text',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'BookOpenText',
        name: 'book-open-text',
        tags: [
            'reading',
            'pages',
            'booklet',
            'magazine',
            'leaflet',
            'pamphlet',
            'library',
            'writing',
            'written',
            'writer',
            'author',
            'story',
            'script',
            'fiction',
            'novel',
            'information',
            'knowledge',
            'education',
            'high school',
            'university',
            'college',
            'academy',
            'student',
            'study',
            'learning',
            'homework',
            'research',
            'documentation',
            'revealed',
        ],
        categories: [
            'text',
            'development',
        ],
    },
    {
        icon: 'BookOpen',
        name: 'book-open',
        tags: [
            'reading',
            'pages',
            'booklet',
            'magazine',
            'leaflet',
            'pamphlet',
            'library',
            'writing',
            'written',
            'writer',
            'author',
            'story',
            'script',
            'screenplay',
            'fiction',
            'novel',
            'information',
            'knowledge',
            'education',
            'high school',
            'university',
            'college',
            'academy',
            'student',
            'study',
            'learning',
            'homework',
            'research',
            'documentation',
            'revealed',
            'blank',
            'plain',
        ],
        categories: [
            'text',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'BookText',
        name: 'book-text',
        tags: [
            'reading',
            'booklet',
            'magazine',
            'leaflet',
            'pamphlet',
            'tome',
            'library',
            'writing',
            'written',
            'writer',
            'author',
            'story',
            'script',
            'fiction',
            'novel',
            'information',
            'knowledge',
            'education',
            'high school',
            'university',
            'college',
            'academy',
            'student',
            'study',
            'learning',
            'homework',
            'research',
            'documentation',
        ],
        categories: [
            'text',
            'gaming',
        ],
    },
    {
        icon: 'BookType',
        name: 'book-type',
        tags: [
            'thesaurus',
            'synonym',
            'reading',
            'booklet',
            'magazine',
            'leaflet',
            'pamphlet',
            'tome',
            'library',
            'writing',
            'written',
            'writer',
            'author',
            'story',
            'script',
            'fiction',
            'novel',
            'information',
            'knowledge',
            'education',
            'high school',
            'university',
            'college',
            'academy',
            'student',
            'study',
            'learning',
            'homework',
            'research',
            'language',
            'translate',
            'typography',
            'fonts',
            'collection',
        ],
        categories: [
            'text',
            'design',
            'gaming',
        ],
    },
    {
        icon: 'BookX',
        name: 'book-x',
        tags: [
            'code',
            'coding',
            'version control',
            'git',
            'repository',
            'remove',
            'delete',
            'reading',
            'misinformation',
            'disinformation',
            'misinformed',
            'charlatan',
            'sophistry',
            'false',
            'lies',
            'untruth',
            'propaganda',
            'censored',
            'cancelled',
            'forbidden',
            'prohibited',
            'banned',
            'uneducated',
            're-education',
            'unlearn',
        ],
        categories: [
            'text',
            'gaming',
        ],
    },
    {
        icon: 'Book',
        name: 'book',
        tags: [
            'reading',
            'paperback',
            'booklet',
            'magazine',
            'leaflet',
            'pamphlet',
            'tome',
            'library',
            'writing',
            'written',
            'writer',
            'author',
            'story',
            'script',
            'fiction',
            'novel',
            'information',
            'knowledge',
            'education',
            'high school',
            'university',
            'college',
            'academy',
            'student',
            'study',
            'learning',
            'homework',
            'research',
            'documentation',
        ],
        categories: [
            'text',
            'development',
            'gaming',
        ],
    },
    {
        icon: 'Brush',
        name: 'brush',
        tags: [
            'clean',
            'sweep',
            'refactor',
            'remove',
            'draw',
            'paint',
            'color',
            'artist',
        ],
        categories: [
            'text',
            'design',
            'tools',
        ],
    },
    {
        icon: 'CaseLower',
        name: 'case-lower',
        tags: [
            'text',
            'letters',
            'characters',
            'font',
            'typography',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'CaseSensitive',
        name: 'case-sensitive',
        tags: [
            'text',
            'letters',
            'characters',
            'font',
            'typography',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'CaseUpper',
        name: 'case-upper',
        tags: [
            'text',
            'letters',
            'characters',
            'font',
            'typography',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'ClipboardCheck',
        name: 'clipboard-check',
        tags: [
            'copied',
            'pasted',
            'done',
            'todo',
            'tick',
            'complete',
            'task',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'ClipboardCopy',
        name: 'clipboard-copy',
        tags: [
            'copy',
            'paste',
        ],
        categories: [
            'text',
            'arrows',
        ],
    },
    {
        icon: 'ClipboardList',
        name: 'clipboard-list',
        tags: [
            'copy',
            'paste',
            'tasks',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'ClipboardMinus',
        name: 'clipboard-minus',
        tags: [
            'copy',
            'delete',
            'remove',
            'erase',
            'document',
            'medical',
            'report',
            'doctor',
        ],
        categories: [
            'text',
            'medical',
        ],
    },
    {
        icon: 'ClipboardPaste',
        name: 'clipboard-paste',
        tags: [
            'copy',
            'paste',
        ],
        categories: [
            'text',
            'arrows',
        ],
    },
    {
        icon: 'ClipboardPenLine',
        name: 'clipboard-pen-line',
        tags: [
            'paste',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'ClipboardPen',
        name: 'clipboard-pen',
        tags: [
            'paste',
            'signature',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'ClipboardPlus',
        name: 'clipboard-plus',
        tags: [
            'copy',
            'paste',
            'add',
            'create',
            'new',
            'document',
            'medical',
            'report',
            'doctor',
        ],
        categories: [
            'text',
            'medical',
        ],
    },
    {
        icon: 'ClipboardType',
        name: 'clipboard-type',
        tags: [
            'paste',
            'format',
            'text',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'ClipboardX',
        name: 'clipboard-x',
        tags: [
            'copy',
            'paste',
            'discard',
            'remove',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Clipboard',
        name: 'clipboard',
        tags: [
            'copy',
            'paste',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'CodeXml',
        name: 'code-xml',
        tags: [
            'source',
            'programming',
            'html',
            'xml',
        ],
        categories: [
            'text',
            'development',
        ],
    },
    {
        icon: 'Code',
        name: 'code',
        tags: [
            'source',
            'programming',
            'html',
            'xml',
        ],
        categories: [
            'text',
            'development',
        ],
    },
    {
        icon: 'CopyCheck',
        name: 'copy-check',
        tags: [
            'clone',
            'duplicate',
            'done',
            'multiple',
        ],
        categories: [
            'text',
            'notifications',
        ],
    },
    {
        icon: 'CopyMinus',
        name: 'copy-minus',
        tags: [
            'clone',
            'duplicate',
            'remove',
            'delete',
            'collapse',
            'subtract',
            'multiple',
            '-',
        ],
        categories: [
            'text',
            'math',
        ],
    },
    {
        icon: 'CopyPlus',
        name: 'copy-plus',
        tags: [
            'clone',
            'duplicate',
            'add',
            'multiple',
            'expand',
            '+',
        ],
        categories: [
            'text',
            'math',
        ],
    },
    {
        icon: 'CopySlash',
        name: 'copy-slash',
        tags: [
            'clone',
            'duplicate',
            'cancel',
            'ban',
            'no',
            'stop',
            'forbidden',
            'prohibited',
            'error',
            'multiple',
            'divide',
            'division',
            'split',
            'or',
            '/',
        ],
        categories: [
            'text',
            'development',
            'math',
        ],
    },
    {
        icon: 'Copy',
        name: 'copy',
        tags: [
            'clone',
            'duplicate',
            'multiple',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Copyleft',
        name: 'copyleft',
        tags: [
            'licence',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Copyright',
        name: 'copyright',
        tags: [
            'licence',
            'license',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'CreativeCommons',
        name: 'creative-commons',
        tags: [
            'licence',
            'license',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Delete',
        name: 'delete',
        tags: [
            'backspace',
            'remove',
        ],
        categories: [
            'text',
            'arrows',
        ],
    },
    {
        icon: 'Eraser',
        name: 'eraser',
        tags: [
            'pencil',
            'drawing',
            'undo',
            'delete',
            'clear',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Expand',
        name: 'expand',
        tags: [
            'scale',
            'fullscreen',
            'maximize',
            'minimize',
            'contract',
        ],
        categories: [
            'text',
            'arrows',
        ],
    },
    {
        icon: 'Grid2x2Check',
        name: 'grid-2x2-check',
        tags: [
            'table',
            'rows',
            'columns',
            'blocks',
            'plot',
            'land',
            'geometry',
            'measure',
            'data',
            'size',
            'width',
            'height',
            'distance',
            'surface area',
            'square meter',
            'acre',
        ],
        categories: [
            'text',
            'layout',
            'math',
        ],
    },
    {
        icon: 'Grid2x2Plus',
        name: 'grid-2x2-plus',
        tags: [
            'table',
            'rows',
            'columns',
            'blocks',
            'plot',
            'land',
            'geometry',
            'measure',
            'data',
            'size',
            'width',
            'height',
            'distance',
            'surface area',
            'square meter',
            'acre',
        ],
        categories: [
            'text',
            'layout',
            'math',
        ],
    },
    {
        icon: 'Grid2x2X',
        name: 'grid-2x2-x',
        tags: [
            'table',
            'rows',
            'columns',
            'data',
            'blocks',
            'plot',
            'land',
            'geometry',
            'measure',
            'size',
            'width',
            'height',
            'distance',
            'surface area',
            'square meter',
            'acre',
        ],
        categories: [
            'text',
            'layout',
            'math',
        ],
    },
    {
        icon: 'Grid2x2',
        name: 'grid-2x2',
        tags: [
            'table',
            'rows',
            'columns',
            'blocks',
            'plot',
            'land',
            'geometry',
            'measure',
            'size',
            'width',
            'height',
            'distance',
            'surface area',
            'square meter',
            'acre',
            'window',
            'skylight',
        ],
        categories: [
            'text',
            'layout',
            'design',
            'math',
        ],
    },
    {
        icon: 'Grid3x3',
        name: 'grid-3x3',
        tags: [
            'table',
            'rows',
            'columns',
        ],
        categories: [
            'text',
            'layout',
            'design',
        ],
    },
    {
        icon: 'Hash',
        name: 'hash',
        tags: [
            'hashtag',
            'number',
            'pound',
        ],
        categories: [
            'text',
            'social',
        ],
    },
    {
        icon: 'Heading1',
        name: 'heading-1',
        tags: [
            'h1',
            'html',
            'markup',
            'markdown',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Heading2',
        name: 'heading-2',
        tags: [
            'h2',
            'html',
            'markup',
            'markdown',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Heading3',
        name: 'heading-3',
        tags: [
            'h3',
            'html',
            'markup',
            'markdown',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Heading4',
        name: 'heading-4',
        tags: [
            'h4',
            'html',
            'markup',
            'markdown',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Heading5',
        name: 'heading-5',
        tags: [
            'h5',
            'html',
            'markup',
            'markdown',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Heading6',
        name: 'heading-6',
        tags: [
            'h6',
            'html',
            'markup',
            'markdown',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Heading',
        name: 'heading',
        tags: [
            'h1',
            'html',
            'markup',
            'markdown',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Highlighter',
        name: 'highlighter',
        tags: [
            'mark',
            'text',
        ],
        categories: [
            'text',
            'design',
        ],
    },
    {
        icon: 'IndentDecrease',
        name: 'indent-decrease',
        tags: [
            'text',
            'tab',
        ],
        categories: [
            'text',
            'development',
        ],
    },
    {
        icon: 'IndentIncrease',
        name: 'indent-increase',
        tags: [
            'text',
            'tab',
        ],
        categories: [
            'text',
            'development',
        ],
    },
    {
        icon: 'Italic',
        name: 'italic',
        tags: [
            'oblique',
            'text',
            'format',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Keyboard',
        name: 'keyboard',
        tags: [
            'layout',
            'spell',
            'settings',
            'mouse',
        ],
        categories: [
            'text',
            'devices',
            'development',
        ],
    },
    {
        icon: 'Languages',
        name: 'languages',
        tags: [
            'translate',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'LetterText',
        name: 'letter-text',
        tags: [
            'drop cap',
            'text',
            'format',
            'typography',
            'letter',
            'font size',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'LibraryBig',
        name: 'library-big',
        tags: [
            'books',
            'reading',
            'written',
            'authors',
            'stories',
            'fiction',
            'novels',
            'information',
            'knowledge',
            'education',
            'high school',
            'university',
            'college',
            'academy',
            'learning',
            'study',
            'research',
            'collection',
            'vinyl',
            'records',
            'albums',
            'music',
            'package',
        ],
        categories: [
            'text',
            'photography',
            'multimedia',
            'navigation',
            'development',
        ],
    },
    {
        icon: 'Library',
        name: 'library',
        tags: [
            'books',
            'reading',
            'written',
            'authors',
            'stories',
            'fiction',
            'novels',
            'information',
            'knowledge',
            'education',
            'high school',
            'university',
            'college',
            'academy',
            'learning',
            'study',
            'research',
            'collection',
            'vinyl',
            'records',
            'albums',
            'music',
            'package',
        ],
        categories: [
            'text',
            'photography',
            'multimedia',
            'navigation',
            'development',
        ],
    },
    {
        icon: 'Ligature',
        name: 'ligature',
        tags: [
            'text',
            'font',
            'typography',
            'alternates',
            'alternatives',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Link2Off',
        name: 'link-2-off',
        tags: [
            'unchain',
            'chain',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Link2',
        name: 'link-2',
        tags: [
            'chain',
            'url',
        ],
        categories: [
            'text',
            'account',
        ],
    },
    {
        icon: 'Link',
        name: 'link',
        tags: [
            'chain',
            'url',
        ],
        categories: [
            'text',
            'account',
        ],
    },
    {
        icon: 'ListCheck',
        name: 'list-check',
        tags: [
            'done',
            'check',
            'tick',
            'complete',
            'list',
            'to-do',
            'bom',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'ListChecks',
        name: 'list-checks',
        tags: [
            'todo',
            'done',
            'check',
            'tick',
            'complete',
            'tasks',
            'items',
            'pending',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'ListCollapse',
        name: 'list-collapse',
        tags: [
            'items',
            'collapse',
            'expand',
            'details',
            'disclosure',
            'show',
            'hide',
            'toggle',
            'accordion',
            'more',
            'less',
            'fold',
            'unfold',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'ListFilterPlus',
        name: 'list-filter-plus',
        tags: [
            'filter',
            'plus',
            'options',
            'add',
        ],
        categories: [
            'text',
            'layout',
        ],
    },
    {
        icon: 'ListFilter',
        name: 'list-filter',
        tags: [
            'options',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'ListOrdered',
        name: 'list-ordered',
        tags: [
            'number',
            'order',
            'queue',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'ListTodo',
        name: 'list-todo',
        tags: [
            'todo',
            'done',
            'check',
            'tick',
            'complete',
            'tasks',
            'items',
            'pending',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'List',
        name: 'list',
        tags: [
            'options',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Logs',
        name: 'logs',
        tags: [
            'options',
            'list',
            'menu',
            'order',
            'queue',
            'tasks',
            'logs',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Mail',
        name: 'mail',
        tags: [
            'email',
            'message',
            'letter',
            'unread',
        ],
        categories: [
            'text',
            'account',
            'mail',
        ],
    },
    {
        icon: 'Map',
        name: 'map',
        tags: [
            'location',
            'navigation',
            'travel',
        ],
        categories: [
            'text',
            'navigation',
        ],
    },
    {
        icon: 'NotebookPen',
        name: 'notebook-pen',
        tags: [
            'pencil',
            'notepad',
            'notes',
            'noted',
            'stationery',
            'sketchbook',
            'organizer',
            'organiser',
            'planner',
            'diary',
            'journal',
            'writing',
            'write',
            'written',
            'reading',
            'high school',
            'university',
            'college',
            'academy',
            'student',
            'study',
            'research',
            'homework',
            'eraser',
            'rubber',
        ],
        categories: [
            'text',
            'social',
        ],
    },
    {
        icon: 'NotebookText',
        name: 'notebook-text',
        tags: [
            'notepad',
            'notes',
            'pages',
            'paper',
            'stationery',
            'sketchbook',
            'organizer',
            'organiser',
            'planner',
            'diary',
            'journal',
            'writing',
            'write',
            'written',
            'reading',
            'high school',
            'university',
            'college',
            'academy',
            'student',
            'study',
            'research',
            'homework',
            'lines',
            'opened',
        ],
        categories: [
            'text',
            'social',
        ],
    },
    {
        icon: 'Notebook',
        name: 'notebook',
        tags: [
            'notepad',
            'notes',
            'stationery',
            'sketchbook',
            'moleskine',
            'closure',
            'strap',
            'band',
            'elastic',
            'organizer',
            'organiser',
            'planner',
            'diary',
            'journal',
            'writing',
            'written',
            'writer',
            'reading',
            'high school',
            'university',
            'college',
            'academy',
            'student',
            'study',
            'homework',
            'research',
        ],
        categories: [
            'text',
            'communication',
            'social',
            'design',
        ],
    },
    {
        icon: 'NotepadTextDashed',
        name: 'notepad-text-dashed',
        tags: [
            'notebook',
            'notes',
            'pages',
            'paper',
            'stationery',
            'diary',
            'journal',
            'writing',
            'write',
            'written',
            'draft',
            'template',
            'lines',
        ],
        categories: [
            'text',
            'social',
        ],
    },
    {
        icon: 'NotepadText',
        name: 'notepad-text',
        tags: [
            'notebook',
            'notes',
            'pages',
            'paper',
            'stationery',
            'sketchbook',
            'organizer',
            'organiser',
            'planner',
            'diary',
            'journal',
            'writing',
            'write',
            'written',
            'reading',
            'high school',
            'university',
            'college',
            'academy',
            'student',
            'study',
            'homework',
            'research',
            'lines',
            'opened',
        ],
        categories: [
            'text',
            'social',
        ],
    },
    {
        icon: 'PaintRoller',
        name: 'paint-roller',
        tags: [
            'brush',
            'color',
            'colour',
            'decoration',
            'diy',
        ],
        categories: [
            'text',
            'design',
            'home',
            'tools',
        ],
    },
    {
        icon: 'PaintbrushVertical',
        name: 'paintbrush-vertical',
        tags: [
            'brush',
            'paintbrush',
            'design',
            'color',
            'colour',
            'decoration',
            'diy',
        ],
        categories: [
            'text',
            'design',
            'photography',
            'home',
            'tools',
        ],
    },
    {
        icon: 'Paintbrush',
        name: 'paintbrush',
        tags: [
            'brush',
            'paintbrush',
            'design',
            'color',
            'colour',
            'decoration',
            'diy',
        ],
        categories: [
            'text',
            'design',
            'photography',
            'home',
            'tools',
        ],
    },
    {
        icon: 'Palette',
        name: 'palette',
        tags: [
            'colors',
            'colours',
            'theme',
            'scheme',
            'paint',
            'watercolor',
            'watercolour',
            'artist',
        ],
        categories: [
            'text',
            'design',
            'photography',
        ],
    },
    {
        icon: 'Paperclip',
        name: 'paperclip',
        tags: [
            'attachment',
            'file',
        ],
        categories: [
            'text',
            'design',
            'files',
            'mail',
        ],
    },
    {
        icon: 'PenLine',
        name: 'pen-line',
        tags: [
            'pencil',
            'change',
            'create',
            'draw',
            'writer',
            'writing',
            'biro',
            'ink',
            'marker',
            'felt tip',
            'stationery',
            'artist',
        ],
        categories: [
            'text',
            'design',
            'tools',
        ],
    },
    {
        icon: 'PenOff',
        name: 'pen-off',
        tags: [
            'disabled',
            'inactive',
            'non-editable',
            'locked',
            'read-only',
            'unmodifiable',
            'frozen',
            'restricted',
            'pencil',
            'change',
            'create',
            'draw',
            'writer',
            'writing',
            'biro',
            'ink',
            'marker',
            'felt tip',
            'stationery',
            'artist',
        ],
        categories: [
            'text',
            'design',
            'tools',
        ],
    },
    {
        icon: 'PenTool',
        name: 'pen-tool',
        tags: [
            'vector',
            'drawing',
            'path',
        ],
        categories: [
            'text',
            'design',
            'cursors',
        ],
    },
    {
        icon: 'Pen',
        name: 'pen',
        tags: [
            'pencil',
            'change',
            'create',
            'draw',
            'writer',
            'writing',
            'biro',
            'ink',
            'marker',
            'felt tip',
            'stationery',
            'artist',
        ],
        categories: [
            'text',
            'design',
            'tools',
        ],
    },
    {
        icon: 'PencilLine',
        name: 'pencil-line',
        tags: [
            'pencil',
            'change',
            'create',
            'draw',
            'sketch',
            'draft',
            'writer',
            'writing',
            'biro',
            'ink',
            'marker',
            'felt tip',
            'stationery',
            'artist',
        ],
        categories: [
            'text',
            'design',
            'tools',
        ],
    },
    {
        icon: 'Phone',
        name: 'phone',
        tags: [
            'call',
        ],
        categories: [
            'text',
            'connectivity',
            'devices',
            'communication',
        ],
    },
    {
        icon: 'PilcrowLeft',
        name: 'pilcrow-left',
        tags: [
            'direction',
            'paragraph',
            'mark',
            'paraph',
            'blind',
            'typography',
            'type',
            'text',
            'prose',
            'symbol',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'PilcrowRight',
        name: 'pilcrow-right',
        tags: [
            'direction',
            'paragraph',
            'mark',
            'paraph',
            'blind',
            'typography',
            'type',
            'text',
            'prose',
            'symbol',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Pilcrow',
        name: 'pilcrow',
        tags: [
            'paragraph',
            'mark',
            'paraph',
            'blind',
            'typography',
            'type',
            'text',
            'prose',
            'symbol',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Pipette',
        name: 'pipette',
        tags: [
            'eye dropper',
            'color picker',
            'lab',
            'chemistry',
        ],
        categories: [
            'text',
            'design',
            'science',
        ],
    },
    {
        icon: 'Quote',
        name: 'quote',
        tags: [
            'quotation',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'RectangleEllipsis',
        name: 'rectangle-ellipsis',
        tags: [
            'login',
            'password',
            'authenticate',
            '2fa',
            'field',
            'fill',
            'ellipsis',
            'et cetera',
            'etc',
            'loader',
            'loading',
            'progress',
            'pending',
            'throbber',
            'menu',
            'options',
            'operator',
            'code',
            'spread',
            'rest',
            'more',
            'further',
            'extra',
            'overflow',
            'dots',
            '…',
            '...',
        ],
        categories: [
            'text',
            'development',
        ],
    },
    {
        icon: 'Redo2',
        name: 'redo-2',
        tags: [
            'undo',
            'rerun',
            'history',
        ],
        categories: [
            'text',
            'arrows',
        ],
    },
    {
        icon: 'RedoDot',
        name: 'redo-dot',
        tags: [
            'redo',
            'history',
            'step',
            'over',
            'forward',
        ],
        categories: [
            'text',
            'arrows',
        ],
    },
    {
        icon: 'Redo',
        name: 'redo',
        tags: [
            'undo',
            'rerun',
            'history',
        ],
        categories: [
            'text',
            'arrows',
        ],
    },
    {
        icon: 'Regex',
        name: 'regex',
        tags: [
            'search',
            'text',
            'code',
        ],
        categories: [
            'text',
            'development',
        ],
    },
    {
        icon: 'RemoveFormatting',
        name: 'remove-formatting',
        tags: [
            'text',
            'font',
            'typography',
            'format',
            'x',
            'remove',
            'delete',
            'times',
            'clear',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'ReplaceAll',
        name: 'replace-all',
        tags: [
            'search',
            'substitute',
            'swap',
            'change',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Replace',
        name: 'replace',
        tags: [
            'search',
            'substitute',
            'swap',
            'change',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'SaveAll',
        name: 'save-all',
        tags: [
            'floppy disks',
            'copy',
        ],
        categories: [
            'text',
            'files',
        ],
    },
    {
        icon: 'SaveOff',
        name: 'save-off',
        tags: [
            'floppy disk',
            'unsalvageable',
        ],
        categories: [
            'text',
            'files',
        ],
    },
    {
        icon: 'Save',
        name: 'save',
        tags: [
            'floppy disk',
        ],
        categories: [
            'text',
            'files',
        ],
    },
    {
        icon: 'ScanText',
        name: 'scan-text',
        tags: [
            'recognition',
            'read',
            'translate',
            'copy',
            'lines',
        ],
        categories: [
            'text',
            'devices',
        ],
    },
    {
        icon: 'Scissors',
        name: 'scissors',
        tags: [
            'cut',
            'snip',
            'chop',
            'stationery',
            'crafts',
        ],
        categories: [
            'text',
            'design',
            'tools',
        ],
    },
    {
        icon: 'SearchCheck',
        name: 'search-check',
        tags: [
            'find',
            'scan',
            'magnifier',
            'magnifying glass',
            'found',
            'correct',
            'complete',
            'tick',
            'lens',
        ],
        categories: [
            'text',
            'social',
        ],
    },
    {
        icon: 'SearchCode',
        name: 'search-code',
        tags: [
            'find',
            'scan',
            'magnifier',
            'magnifying glass',
            'grep',
            'chevrons',
            '<>',
            'lens',
        ],
        categories: [
            'text',
            'social',
            'development',
        ],
    },
    {
        icon: 'SearchSlash',
        name: 'search-slash',
        tags: [
            'find',
            'scan',
            'magnifier',
            'magnifying glass',
            'stop',
            'clear',
            'cancel',
            'abort',
            '/',
            'lens',
        ],
        categories: [
            'text',
            'social',
        ],
    },
    {
        icon: 'SearchX',
        name: 'search-x',
        tags: [
            'find',
            'scan',
            'magnifier',
            'magnifying glass',
            'stop',
            'clear',
            'cancel',
            'abort',
            'lens',
        ],
        categories: [
            'text',
            'social',
        ],
    },
    {
        icon: 'Search',
        name: 'search',
        tags: [
            'find',
            'scan',
            'magnifier',
            'magnifying glass',
            'lens',
        ],
        categories: [
            'text',
            'social',
        ],
    },
    {
        icon: 'Section',
        name: 'section',
        tags: [
            'mark',
            'typography',
            'punctuation',
            'legal',
            'type',
            'text',
            'prose',
            'symbol',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'SeparatorHorizontal',
        name: 'separator-horizontal',
        tags: [
            'move',
            'split',
        ],
        categories: [
            'text',
            'arrows',
            'layout',
        ],
    },
    {
        icon: 'SeparatorVertical',
        name: 'separator-vertical',
        tags: [
            'move',
            'split',
        ],
        categories: [
            'text',
            'arrows',
            'layout',
        ],
    },
    {
        icon: 'Sheet',
        name: 'sheet',
        tags: [
            'spreadsheets',
            'table',
            'excel',
        ],
        categories: [
            'text',
            'files',
        ],
    },
    {
        icon: 'Sigma',
        name: 'sigma',
        tags: [
            'sum',
            'calculate',
            'formula',
            'math',
            'enumeration',
            'enumerate',
        ],
        categories: [
            'text',
            'math',
            'science',
        ],
    },
    {
        icon: 'Signature',
        name: 'signature',
        tags: [
            'text',
            'format',
            'input',
            'contract',
            'autograph',
            'handwriting',
            'sign',
            'cursive',
            'ink',
            'scribble',
            'authorize',
            'personal',
            'agreement',
            'legal',
            'document',
            'identity',
            'authentic',
            'approval',
            'verification',
            'unique',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Space',
        name: 'space',
        tags: [
            'text',
            'selection',
            'letters',
            'characters',
            'font',
            'typography',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'SpellCheck2',
        name: 'spell-check-2',
        tags: [
            'spelling',
            'error',
            'mistake',
            'oversight',
            'typo',
            'correction',
            'code',
            'linter',
            'a',
        ],
        categories: [
            'text',
            'development',
        ],
    },
    {
        icon: 'SpellCheck',
        name: 'spell-check',
        tags: [
            'spelling',
            'error',
            'mistake',
            'oversight',
            'typo',
            'correction',
            'code',
            'linter',
            'a',
        ],
        categories: [
            'text',
            'development',
        ],
    },
    {
        icon: 'SquareAsterisk',
        name: 'square-asterisk',
        tags: [
            'password',
            'secret',
            'access',
            'key',
            'multiply',
            'multiplication',
            'glob pattern',
            'wildcard',
            '*',
        ],
        categories: [
            'text',
            'security',
            'math',
            'development',
        ],
    },
    {
        icon: 'SquareBottomDashedScissors',
        name: 'square-bottom-dashed-scissors',
        tags: [
            'cut',
            'snippet',
            'chop',
            'stationery',
            'crafts',
        ],
        categories: [
            'text',
            'design',
            'tools',
            'files',
            'development',
        ],
    },
    {
        icon: 'SquareCode',
        name: 'square-code',
        tags: [
            'gist',
            'source',
            'programming',
            'html',
            'xml',
            'coding',
        ],
        categories: [
            'text',
            'development',
        ],
    },
    {
        icon: 'SquareDashed',
        name: 'square-dashed',
        tags: [
            'selection',
            'square',
            'rectangular',
            'marquee',
            'tool',
            'dashed',
            'box',
        ],
        categories: [
            'text',
            'design',
        ],
    },
    {
        icon: 'SquareLibrary',
        name: 'square-library',
        tags: [
            'books',
            'reading',
            'written',
            'authors',
            'stories',
            'fiction',
            'novels',
            'information',
            'knowledge',
            'education',
            'high school',
            'university',
            'college',
            'academy',
            'learning',
            'study',
            'research',
            'collection',
            'vinyl',
            'records',
            'albums',
            'music',
            'package',
        ],
        categories: [
            'text',
            'photography',
            'multimedia',
            'navigation',
            'development',
        ],
    },
    {
        icon: 'SquarePen',
        name: 'square-pen',
        tags: [
            'pencil',
            'edit',
            'change',
            'create',
            'draw',
            'sketch',
            'draft',
            'writer',
            'writing',
            'biro',
            'ink',
            'marker',
            'felt tip',
            'stationery',
            'artist',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'SquarePilcrow',
        name: 'square-pilcrow',
        tags: [
            'paragraph',
            'mark',
            'paraph',
            'blind',
            'typography',
            'type',
            'text',
            'prose',
            'symbol',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'SquareScissors',
        name: 'square-scissors',
        tags: [
            'cut',
            'snippet',
            'chop',
            'stationery',
            'crafts',
            'toolbar',
            'button',
        ],
        categories: [
            'text',
            'design',
            'tools',
            'files',
            'development',
        ],
    },
    {
        icon: 'SquareSigma',
        name: 'square-sigma',
        tags: [
            'sum',
            'calculate',
            'formula',
            'math',
            'enumeration',
            'enumerate',
        ],
        categories: [
            'text',
            'math',
        ],
    },
    {
        icon: 'SquareStack',
        name: 'square-stack',
        tags: [
            'versions',
            'clone',
            'copy',
            'duplicate',
            'multiple',
            'revisions',
            'version control',
            'backup',
            'history',
        ],
        categories: [
            'text',
            'files',
            'development',
        ],
    },
    {
        icon: 'StickyNote',
        name: 'sticky-note',
        tags: [
            'post-it',
            'comment',
            'annotation',
            'reaction',
            'memo',
            'reminder',
            'todo',
            'task',
            'idea',
            'brainstorm',
            'document',
            'page',
            'paper',
            'sheet',
            'stationary',
            'office',
        ],
        categories: [
            'text',
            'social',
        ],
    },
    {
        icon: 'Strikethrough',
        name: 'strikethrough',
        tags: [
            'cross out',
            'delete',
            'remove',
            'format',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Subscript',
        name: 'subscript',
        tags: [
            'text',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Superscript',
        name: 'superscript',
        tags: [
            'text',
            'exponent',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Table2',
        name: 'table-2',
        tags: [
            'spreadsheet',
            'grid',
        ],
        categories: [
            'text',
            'files',
        ],
    },
    {
        icon: 'TableCellsMerge',
        name: 'table-cells-merge',
        tags: [
            'spreadsheet',
            'grid',
            'row',
        ],
        categories: [
            'text',
            'files',
        ],
    },
    {
        icon: 'TableCellsSplit',
        name: 'table-cells-split',
        tags: [
            'spreadsheet',
            'grid',
            'row',
        ],
        categories: [
            'text',
            'files',
        ],
    },
    {
        icon: 'TableColumnsSplit',
        name: 'table-columns-split',
        tags: [
            'spreadsheet',
            'grid',
            'cut',
            'break',
            'divide',
            'separate',
            'segment',
        ],
        categories: [
            'text',
            'files',
        ],
    },
    {
        icon: 'TableOfContents',
        name: 'table-of-contents',
        tags: [
            'toc',
            'outline',
            'navigation',
            'document structure',
            'index',
            'overview',
            'sections',
            'chapters',
            'content',
            'documentation',
            'manual',
            'knowledge base',
            'faq',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'TableProperties',
        name: 'table-properties',
        tags: [
            'property list',
            'plist',
            'spreadsheet',
            'grid',
            'dictionary',
            'object',
            'hash',
        ],
        categories: [
            'text',
            'development',
            'files',
        ],
    },
    {
        icon: 'TableRowsSplit',
        name: 'table-rows-split',
        tags: [
            'spreadsheet',
            'grid',
            'cut',
            'break',
            'divide',
            'separate',
            'segment',
        ],
        categories: [
            'text',
            'files',
        ],
    },
    {
        icon: 'Table',
        name: 'table',
        tags: [
            'spreadsheet',
            'grid',
        ],
        categories: [
            'text',
            'files',
        ],
    },
    {
        icon: 'TextCursorInput',
        name: 'text-cursor-input',
        tags: [
            'select',
        ],
        categories: [
            'text',
            'layout',
        ],
    },
    {
        icon: 'TextCursor',
        name: 'text-cursor',
        tags: [
            'select',
        ],
        categories: [
            'text',
            'cursors',
        ],
    },
    {
        icon: 'TextQuote',
        name: 'text-quote',
        tags: [
            'blockquote',
            'quotation',
            'indent',
            'reply',
            'response',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'TextSearch',
        name: 'text-search',
        tags: [
            'find',
            'data',
            'copy',
            'txt',
            'pdf',
            'document',
            'scan',
            'magnifier',
            'magnifying glass',
            'lens',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'TextSelect',
        name: 'text-select',
        tags: [
            'find',
            'search',
            'selection',
            'dashed',
        ],
        categories: [
            'text',
            'cursors',
        ],
    },
    {
        icon: 'Text',
        name: 'text',
        tags: [
            'find',
            'search',
            'data',
            'txt',
            'pdf',
            'document',
        ],
        categories: [
            'text',
            'files',
            'cursors',
        ],
    },
    {
        icon: 'TypeOutline',
        name: 'type-outline',
        tags: [
            'text',
            'font',
            'typography',
            'silhouette',
            'profile',
            'contour',
            'stroke',
            'line',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Type',
        name: 'type',
        tags: [
            'text',
            'font',
            'typography',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Underline',
        name: 'underline',
        tags: [
            'text',
            'format',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Undo2',
        name: 'undo-2',
        tags: [
            'redo',
            'rerun',
            'history',
            'back',
            'return',
            'reverse',
            'revert',
            'direction',
            'u-turn',
        ],
        categories: [
            'text',
            'arrows',
        ],
    },
    {
        icon: 'UndoDot',
        name: 'undo-dot',
        tags: [
            'redo',
            'history',
            'step',
            'back',
        ],
        categories: [
            'text',
            'arrows',
        ],
    },
    {
        icon: 'Undo',
        name: 'undo',
        tags: [
            'redo',
            'rerun',
            'history',
        ],
        categories: [
            'text',
            'arrows',
        ],
    },
    {
        icon: 'Unlink2',
        name: 'unlink-2',
        tags: [
            'url',
            'unchain',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'Unlink',
        name: 'unlink',
        tags: [
            'url',
            'unchain',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'WholeWord',
        name: 'whole-word',
        tags: [
            'text',
            'selection',
            'letters',
            'characters',
            'font',
            'typography',
        ],
        categories: [
            'text',
        ],
    },
    {
        icon: 'WrapText',
        name: 'wrap-text',
        tags: [
            'words',
            'lines',
            'break',
            'paragraph',
        ],
        categories: [
            'text',
            'arrows',
        ],
    },
];
export default icons;
