// Icons with primary category: tools
const icons = [
    {
        icon: 'Axe',
        name: 'axe',
        tags: [
            'hatchet',
            'weapon',
            'chop',
            'sharp',
            'equipment',
            'fireman',
            'firefighter',
            'brigade',
            'lumberjack',
            'woodcutter',
            'logger',
            'forestry',
        ],
        categories: [
            'tools',
            'gaming',
        ],
    },
    {
        icon: 'Bolt',
        name: 'bolt',
        tags: [
            'nut',
            'screw',
            'settings',
            'preferences',
            'configuration',
            'controls',
            'edit',
            'diy',
            'fixed',
            'build',
            'construction',
            'parts',
        ],
        categories: [
            'tools',
            'home',
        ],
    },
    {
        icon: 'Drill',
        name: 'drill',
        tags: [
            'power',
            'bit',
            'head',
            'hole',
            'diy',
            'toolbox',
            'build',
            'construction',
        ],
        categories: [
            'tools',
            'home',
            'devices',
        ],
    },
    {
        icon: 'Hammer',
        name: 'hammer',
        tags: [
            'mallet',
            'nails',
            'diy',
            'toolbox',
            'build',
            'construction',
        ],
        categories: [
            'tools',
            'home',
        ],
    },
    {
        icon: 'HardHat',
        name: 'hard-hat',
        tags: [
            'helmet',
            'construction',
            'safety',
            'savety',
        ],
        categories: [
            'tools',
        ],
    },
    {
        icon: 'InspectionPanel',
        name: 'inspection-panel',
        tags: [
            'access',
            'cover',
            'tile',
            'metal',
            'materials',
            'screws',
        ],
        categories: [
            'tools',
        ],
    },
    {
        icon: 'PencilRuler',
        name: 'pencil-ruler',
        tags: [
            'edit',
            'create',
            'draw',
            'sketch',
            'draft',
            'writer',
            'writing',
            'stationery',
            'artist',
            'measurements',
            'centimeters',
            'cm',
            'millimeters',
            'mm',
            'metre',
            'foot',
            'feet',
            'inches',
            'units',
            'size',
            'length',
            'width',
            'height',
            'dimensions',
            'depth',
            'breadth',
            'extent',
        ],
        categories: [
            'tools',
            'design',
            'layout',
            'text',
        ],
    },
    {
        icon: 'Pickaxe',
        name: 'pickaxe',
        tags: [
            'mining',
            'mine',
            'land worker',
            'extraction',
            'labor',
            'construction',
            'progress',
            'advancement',
            'crafting',
            'building',
            'creation',
        ],
        categories: [
            'tools',
            'gaming',
        ],
    },
    {
        icon: 'PocketKnife',
        name: 'pocket-knife',
        tags: [
            'swiss army knife',
            'penknife',
            'multi-tool',
            'multitask',
            'blade',
            'cutter',
            'gadget',
            'corkscrew',
        ],
        categories: [
            'tools',
        ],
    },
    {
        icon: 'RulerDimensionLine',
        name: 'ruler-dimension-line',
        tags: [
            'measurements',
            'centimeters',
            'cm',
            'millimeters',
            'mm',
            'metre',
            'foot',
            'feet',
            'inches',
            'units',
            'size',
            'length',
            'width',
            'height',
            'dimensions',
            'depth',
            'breadth',
            'extent',
            'stationery',
        ],
        categories: [
            'tools',
            'design',
            'layout',
        ],
    },
    {
        icon: 'Ruler',
        name: 'ruler',
        tags: [
            'measurements',
            'centimeters',
            'cm',
            'millimeters',
            'mm',
            'metre',
            'foot',
            'feet',
            'inches',
            'units',
            'size',
            'length',
            'width',
            'height',
            'dimensions',
            'depth',
            'breadth',
            'extent',
            'stationery',
        ],
        categories: [
            'tools',
            'design',
            'layout',
        ],
    },
];
export default icons;
