// Icons with primary category: transportation
const icons = [
    {
        icon: 'Anchor',
        name: 'anchor',
        tags: [
            'ship',
        ],
        categories: [
            'transportation',
            'text',
        ],
    },
    {
        icon: 'BaggageClaim',
        name: 'baggage-claim',
        tags: [
            'baggage',
            'luggage',
            'travel',
            'cart',
            'trolley',
            'suitcase',
        ],
        categories: [
            'transportation',
            'travel',
        ],
    },
    {
        icon: 'Bike',
        name: 'bike',
        tags: [
            'bicycle',
            'transport',
            'trip',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'BriefcaseBusiness',
        name: 'briefcase-business',
        tags: [
            'work',
            'bag',
            'baggage',
            'folder',
            'portfolio',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'Briefcase',
        name: 'briefcase',
        tags: [
            'work',
            'bag',
            'baggage',
            'folder',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'BusFront',
        name: 'bus-front',
        tags: [
            'coach',
            'vehicle',
            'trip',
            'road',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'Bus',
        name: 'bus',
        tags: [
            'bus',
            'vehicle',
            'transport',
            'trip',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'CableCar',
        name: 'cable-car',
        tags: [
            'ski lift',
            'winter holiday',
            'alpine',
            'resort',
            'mountains',
        ],
        categories: [
            'transportation',
            'travel',
        ],
    },
    {
        icon: 'CarFront',
        name: 'car-front',
        tags: [
            'vehicle',
            'drive',
            'trip',
            'journey',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'CarTaxiFront',
        name: 'car-taxi-front',
        tags: [
            'cab',
            'vehicle',
            'drive',
            'trip',
            'journey',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'Car',
        name: 'car',
        tags: [
            'vehicle',
            'drive',
            'trip',
            'journey',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'Caravan',
        name: 'caravan',
        tags: [
            'trailer',
            'tow',
            'camping',
            'campsite',
            'mobile home',
            'holiday',
            'nomadic',
            'wilderness',
            'outdoors',
        ],
        categories: [
            'transportation',
            'travel',
            'nature',
        ],
    },
    {
        icon: 'CircleGauge',
        name: 'circle-gauge',
        tags: [
            'dashboard',
            'dial',
            'meter',
            'speed',
            'pressure',
            'measure',
            'level',
        ],
        categories: [
            'transportation',
            'sports',
            'science',
        ],
    },
    {
        icon: 'CircleParkingOff',
        name: 'circle-parking-off',
        tags: [
            'parking lot',
            'car park',
            'no parking',
        ],
        categories: [
            'transportation',
            'navigation',
        ],
    },
    {
        icon: 'CircleParking',
        name: 'circle-parking',
        tags: [
            'parking lot',
            'car park',
        ],
        categories: [
            'transportation',
            'navigation',
        ],
    },
    {
        icon: 'Forklift',
        name: 'forklift',
        tags: [
            'vehicle',
            'transport',
            'logistics',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'Fuel',
        name: 'fuel',
        tags: [
            'filling-station',
            'gas',
            'petrol',
            'tank',
        ],
        categories: [
            'transportation',
            'navigation',
        ],
    },
    {
        icon: 'Gauge',
        name: 'gauge',
        tags: [
            'dashboard',
            'dial',
            'meter',
            'speed',
            'pressure',
            'measure',
            'level',
        ],
        categories: [
            'transportation',
            'sports',
            'science',
        ],
    },
    {
        icon: 'OctagonMinus',
        name: 'octagon-minus',
        tags: [
            'stop',
            'forbidden',
            'subtract',
            'remove',
            'decrease',
            'reduce',
            '-',
            'traffic',
            'halt',
            'restricted',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'ParkingMeter',
        name: 'parking-meter',
        tags: [
            'driving',
            'car park',
            'pay',
            'sidewalk',
            'pavement',
        ],
        categories: [
            'transportation',
            'navigation',
        ],
    },
    {
        icon: 'PlaneLanding',
        name: 'plane-landing',
        tags: [
            'arrival',
            'plane',
            'trip',
            'airplane',
            'landing',
        ],
        categories: [
            'transportation',
            'travel',
        ],
    },
    {
        icon: 'PlaneTakeoff',
        name: 'plane-takeoff',
        tags: [
            'departure',
            'plane',
            'trip',
            'airplane',
            'takeoff',
        ],
        categories: [
            'transportation',
            'travel',
        ],
    },
    {
        icon: 'Plane',
        name: 'plane',
        tags: [
            'plane',
            'trip',
            'airplane',
        ],
        categories: [
            'transportation',
            'travel',
        ],
    },
    {
        icon: 'RailSymbol',
        name: 'rail-symbol',
        tags: [
            'railway',
            'train',
            'track',
            'line',
        ],
        categories: [
            'transportation',
            'navigation',
        ],
    },
    {
        icon: 'Sailboat',
        name: 'sailboat',
        tags: [
            'ship',
            'boat',
            'harbor',
            'harbour',
            'dock',
        ],
        categories: [
            'transportation',
            'travel',
        ],
    },
    {
        icon: 'ShipWheel',
        name: 'ship-wheel',
        tags: [
            'steering',
            'rudder',
            'boat',
            'knots',
            'nautical mile',
            'maritime',
            'sailing',
            'yacht',
            'cruise',
            'ocean liner',
            'tanker',
            'vessel',
            'navy',
            'trip',
        ],
        categories: [
            'transportation',
            'navigation',
            'travel',
        ],
    },
    {
        icon: 'Ship',
        name: 'ship',
        tags: [
            'boat',
            'knots',
            'nautical mile',
            'maritime',
            'sailing',
            'yacht',
            'cruise',
            'ocean liner',
            'tanker',
            'vessel',
            'navy',
            'trip',
        ],
        categories: [
            'transportation',
            'navigation',
            'travel',
        ],
    },
    {
        icon: 'SquareM',
        name: 'square-m',
        tags: [
            'metro',
            'subway',
            'underground',
            'track',
            'line',
        ],
        categories: [
            'transportation',
            'navigation',
        ],
    },
    {
        icon: 'SquareParkingOff',
        name: 'square-parking-off',
        tags: [
            'parking lot',
            'car park',
            'no parking',
        ],
        categories: [
            'transportation',
            'navigation',
        ],
    },
    {
        icon: 'SquareParking',
        name: 'square-parking',
        tags: [
            'parking lot',
            'car park',
        ],
        categories: [
            'transportation',
            'navigation',
        ],
    },
    {
        icon: 'TicketCheck',
        name: 'ticket-check',
        tags: [
            'entry',
            'pass',
            'voucher',
            'event',
            'concert',
            'show',
            'booked',
            'purchased',
            'receipt',
            'redeemed',
            'validated',
            'verified',
            'certified',
            'checked',
            'used',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'TicketMinus',
        name: 'ticket-minus',
        tags: [
            'entry',
            'pass',
            'voucher',
            'event',
            'concert',
            'show',
            'remove',
            'cancel',
            'unbook',
            'subtract',
            'decrease',
            '-',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'TicketPercent',
        name: 'ticket-percent',
        tags: [
            'discount',
            'reduced',
            'offer',
            'voucher',
            'entry',
            'pass',
            'event',
            'concert',
            'show',
            'book',
            'purchase',
            '%',
        ],
        categories: [
            'transportation',
            'shopping',
        ],
    },
    {
        icon: 'TicketPlus',
        name: 'ticket-plus',
        tags: [
            'entry',
            'pass',
            'voucher',
            'event',
            'concert',
            'show',
            'book',
            'purchase',
            'add',
            '+',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'TicketSlash',
        name: 'ticket-slash',
        tags: [
            'entry',
            'pass',
            'voucher',
            'event',
            'concert',
            'show',
            'redeemed',
            'used',
            'marked',
            'checked',
            'verified',
            'spoiled',
            'invalidated',
            'void',
            'denied',
            'refused',
            'banned',
            'barred',
            'forbidden',
            'prohibited',
            'cancelled',
            'cancellation',
            'refunded',
            'delete',
            'remove',
            'clear',
            'error',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'TicketX',
        name: 'ticket-x',
        tags: [
            'entry',
            'pass',
            'voucher',
            'event',
            'concert',
            'show',
            'cancelled',
            'cancellation',
            'refunded',
            'used',
            'void',
            'invalidated',
            'spoiled',
            'denied',
            'refused',
            'banned',
            'barred',
            'forbidden',
            'prohibited',
            'delete',
            'remove',
            'clear',
            'error',
            'x',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'TicketsPlane',
        name: 'tickets-plane',
        tags: [
            'plane',
            'trip',
            'airplane',
            'flight',
            'travel',
            'fly',
            'takeoff',
            'vacation',
            'passenger',
            'pass',
            'check-in',
            'airport',
        ],
        categories: [
            'transportation',
            'travel',
        ],
    },
    {
        icon: 'Tractor',
        name: 'tractor',
        tags: [
            'farming',
            'farmer',
            'ranch',
            'harvest',
            'equipment',
            'vehicle',
        ],
        categories: [
            'transportation',
            'sustainability',
            'food-beverage',
        ],
    },
    {
        icon: 'TrafficCone',
        name: 'traffic-cone',
        tags: [
            'roadworks',
            'tarmac',
            'safety',
            'block',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'TrainFrontTunnel',
        name: 'train-front-tunnel',
        tags: [
            'railway',
            'metro',
            'subway',
            'underground',
            'speed',
            'bullet',
            'fast',
            'track',
            'line',
        ],
        categories: [
            'transportation',
            'navigation',
        ],
    },
    {
        icon: 'TrainFront',
        name: 'train-front',
        tags: [
            'railway',
            'metro',
            'subway',
            'underground',
            'high-speed',
            'bullet',
            'fast',
            'track',
            'line',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'TrainTrack',
        name: 'train-track',
        tags: [
            'railway',
            'line',
        ],
        categories: [
            'transportation',
            'navigation',
        ],
    },
    {
        icon: 'TramFront',
        name: 'tram-front',
        tags: [
            'railway',
            'metro',
            'subway',
            'underground',
            'track',
            'line',
            'tourism',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'TruckElectric',
        name: 'truck-electric',
        tags: [
            'delivery',
            'van',
            'shipping',
            'haulage',
            'lorry',
            'electric',
        ],
        categories: [
            'transportation',
        ],
    },
    {
        icon: 'Truck',
        name: 'truck',
        tags: [
            'delivery',
            'van',
            'shipping',
            'haulage',
            'lorry',
        ],
        categories: [
            'transportation',
        ],
    },
];
export default icons;
